### PR TITLE
Fix: Better reporting if 'this' used in a subset type - and no crash

### LINKED ISSUE #2068: Resolver crash
The following crashes for me in 3.5.0.40314:
```
type St = s:St_ | (forall o | o in s :: o.i(this))
type St_ = map<nat,Ob>
type Ob {
    predicate i(s:St_)
}
```

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #2068
I added the corresponding test. The case of a "this" inside a subset type is not allowed, but there was no error mechanism to detect it. This PR solves that problem.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Resolver.cs [hunk 1]
```diff
@@ -14875,7 +14874,11 @@ public ResolutionContext(ICodeContext codeContext, bool isTwoState)
         if (currentClass is ClassDecl cd && cd.IsDefaultClass) {
```
Comment (robin-aws) [inline Source/DafnyCore/Resolver.cs:14874]: It looks like this case would also hit a crash, just later on in the pipeline?

File: Test/git-issues/git-issue-2068.dfy [hunk 2]
```diff
@@ -0,0 +1,8 @@
+// RUN: %dafny_0 /compile:0 "%s" > "%t"
+// RUN: %diff "%s.expect" "%t"
+
+type St = s:St_ | (forall o | o in s :: o.i(this))
```
Comment (robin-aws) [inline Test/git-issues/git-issue-2068.dfy:4]: As per my other comment, it would be great to show this fix working correctly in a few other illegal contexts as well, just for deeper testing coverage.

**Review by robin-aws — CHANGES_REQUESTED** [review]

File: Source/DafnyCore/Resolver.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/DafnyCore/Resolver.cs:14874]: How would you reproduce it?

File: Test/git-issues/git-issue-2068.dfy (hunk 2 above)
Comment (MikaelMayer) [reply Test/git-issues/git-issue-2068.dfy]: I added two other illegal context, the witness clause and a static const RHS. The static const RHS was also crashing Boogie. I was able to ensure the fixes use the same convention as for the existing code.
Of the top-level contexts, there is no other case to my knowledge where "this" should be disallowed.

File: Source/DafnyCore/Resolver.cs (hunk 1 above)
Comment (robin-aws) [reply Source/DafnyCore/Resolver.cs:14883]: I didn't have any luck, and it looks like the error immediately above should always be triggered, which seems to prevent any further problems.

**Review by robin-aws — DISMISSED** [review]

**Review by robin-aws — APPROVED** [review]
Nice, I like the refactoring to make this a more explicitly modeled restriction.
