### PR TITLE
Fix: Support for Corretto tests

### LINKED ISSUE #3731: dafny build/test/run fails on Java + Windows
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method {:test} Test() {
  expect 1 == 2;
}
```

### Command to run and resulting output

```code
dafny test --target java git-issue-3724.dfy
```

### What happened?

```
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());
                                             ^
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());
                                                   ^
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());
                                                            ^
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());
                                                                      ^
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());
                                                                                  ^
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: ';' expected
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());


       ^
C:\Users\username\git-issue-3724\_System\__default.java
:57: error: ';' expected
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(51,4): " + (dafny.DafnySequence.asUnicodeString("expectation viol
ation")).verbatimString());


                         ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());
                                             ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());
                                                   ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());
                                                            ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());
                                                                      ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: illegal escape character
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());
                                                                                  ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: ';' expected
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());


                     ^
C:\Users\username\git-issue-3724\_System\__default.java
:83: error: ';' expected
      throw new dafny.DafnyHaltException("C:\Users\username\git-issue-3724.dfy(1,0): " + (dafny.DafnySequence.asUnicodeString("Test failures occ
urred: see above.\n")).verbatimString());


                                       ^
14 errors
Error while compiling Java files. Process exited with exit code 1


```

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #3731, which will enable me to reproduce https://github.com/dafny-lang/dafny/issues/3724 locally.
I did not add tests for now because this bug appears on Windows + Corretto machines, and I just switched to Corretto. I'm not expecting to change the CI pipeline until we decide so.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Compilers/Java/Compiler-java.cs [hunk 1]
```diff
@@ -3417,7 +3417,8 @@ protected class ClassWriter : IClassWriter {
       var wStmts = wr.Fork();
       wr.Write("throw new dafny.DafnyHaltException(");
       if (tok != null) {
-        wr.Write("\"" + Dafny.ErrorReporter.TokenToString(tok) + ": \" + ");
+        wr.Write("\"" + Dafny.ErrorReporter.TokenToString(tok).Replace(
+          @"\", @"\\") + ": \" + ");
```
Comment (robin-aws) [inline Source/DafnyCore/Compilers/Java/Compiler-java.cs:3421]:
```suggestion
        wr.Write("\"" + TranslateEscapes(Dafny.ErrorReporter.TokenToString(tok)) + ": \" + ");
```

The root cause is printing out a string without any escaping (nothing to do with Corretto AFAICT).

It looks like all compilers have the same issue in `EmitHalt`, so worth applying the same fix consistently if possible.

Comment (MikaelMayer) [reply Source/DafnyCore/Compilers/Java/Compiler-java.cs:3421]: I did not use "TranslateEscapes" because it's not an escaping function. It's actually taking the source of a Dafny string and translating escapes to Java Escapes. Here, the only thing in PATHs that could be problematics is the backward slash.

Comment (robin-aws) [reply Source/DafnyCore/Compilers/Java/Compiler-java.cs:3421]: Actually my mistake, you want `EmitStringLiteral(..., true, wr)`
