### PR TITLE
Negative literals

### LINKED ISSUE #889: There are no negated literals
Up until now, Dafny has not had any negated literals. Instead, an expression like `-3` is parsed as a unary expression that applies operator `-` to the (non-negative) literal `3`. This is awkward in at least two situations, see below.

This Issue suggests that the grammar should change to parse a single `-` token in front of a numeric literal as part of the numeric literal.

## Repros

One awkward situation is when trying to write a negative literal for a type that doesn't have the same corresponding positive literal. Here are two examples:

``` dafny
newtype int8 = x | -128 <= x < 128
newtype smallneg = r | -1.0 <= r <= 0.0

method M() returns (b: int8, r: smallneg) {
  if {
    case true =>
      b := -128;  // this currently gives an error: the argument to unary `-`, the literal `128`, is not a value of type `int8`
    case true =>
      b := -127 - 1;  // fine
    case true =>
      b := (-128) as int8;  // fine
    case true =>
      b := -128 as int8;  // `-` binds stronger than `as`, so this is the same as the previous line
    case true =>
      b := -(128 as int8);  // this is, and should continue to be, an error
 }

  if {
    case true =>
      r := -1.0;  // error: 1.0 violates newtype type constraint
    case true =>
      r := -1.0 as smallneg;  // fine
  }
}
```

The other situation is when trying to use a negative literal in a `case` pattern:

``` dafny
method MatchCaseParsing(x: int, pair: (int, int))
  requires x == 2 || x == -1
  requires p.0 == 10 && (p.1 == 10 || p.1 == -10)
{
  match x {
    case 2 =>
    case -1 =>  // this gives a parse error
    // Note, `case (-1) =>` is not a workaround, because parenthetic expressions are not allowed in patterns
  }
  match pair {
    case (10, 10) =>
    case (10, -10) =>  // this gives a parse error
  }
}
```

## Implementation note

Bitvector arithmetic is modular, that is, is wraps around. However, literals still have to be proper values of the type. So, _after_ implementing this Issue, we would expect:

``` dafny
method Bitvectors() returns (v: bv8) {
  if
  case true =>
    v := -3;  // error: too small to be a bv8
  case true =>
    v := 300;  // error: too large to be a bv8
  case true =>
    v := -(3);  // fine, since this is still a unary-minus expression applied to 3, and - wraps on bitvectors
  case true =>
    v := 200 + 100;  // fine, since 200 and 100 are both bv8 values, and + wraps on bitvectors
}
```

### PR DESCRIPTION
**Pull request by RustanLeino**
When the token `-` is followed by a digit sequence,
* treat this as a negative literal, if the type is integer or real
* treat this as a unary-minus expression, if the type is a bitvector
* give an error saying unary-minus is not supported, if the type is an `ORDINAL`

Example benefit: This lets a program write `-128` for the smallest value in the type

    newtype int8 = x | -128 <= x < 128

Previously, when `-128` was always treated as a unary-minus expression, that would have given an error saying that `128` is not a value in the type `int8`.

Another example benefit: This lets `-1` be used to denote the all-1 bitpattern in `bv32`. If `-1` were always a negative literal, then this would give an error (since bitvectors have no negative values) and the workaround would be to instead write (the rather ugly and unnatural) `-(1)`.

Note, negative literals are parsed as two separate tokens. However, any whitespace between the `-` and the digit sequence is inconsequential.

With this PR, negative literals are also allowed in `case` patterns. But note that, since `-` followed by a digit sequence is a negative literal only for integers and reals, trying to write an expression like `-1` in a `case` pattern where gives an error for bitvectors and for `ORDINAL`.

This PR also fixes a null crash in the handling of the `null` literal in `case` patterns.

Fixes #889

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -6111,12 +6098,18 @@ public CheckTypeInference_Visitor(Resolver resolver, ICodeContext codeContext)
...
-          var t = e.Type as BitvectorType;
-          if (t != null) {
+          if (e.Type.IsBitVectorType || e.Type.IsBigOrdinalType) {
             var n = (BigInteger)e.Value;
-            // check that the given literal fits into the bitvector width
-            if (BigInteger.Pow(2, t.Width) <= n) {
-              resolver.reporter.Error(MessageSource.Resolver, e.tok, "bitvector literal ({0}) is too large for the type {1}", e.Value, t);
+            var absN = n < 0 ? -n : n;
+            // For bitvectors, check that the magnitude fits the width
+            if (e.Type.IsBitVectorType && BigInteger.Pow(2, e.Type.AsBitVectorType.Width) <= absN) {
```
Comment (davidcok) [inline Source/Dafny/Resolver.cs:6105]: Suggest using MaxBV here

File: Source/Dafny/Cloner.cs [hunk 2]
```diff
@@ -684,7 +684,7 @@ class Cloner
     public ExtendedPattern CloneExtendedPattern(ExtendedPattern pat) {
       if(pat is LitPattern) {
         var p = (LitPattern)pat;
-        return new LitPattern(p.Tok, (LiteralExpr)CloneExpr(p.Lit));
+        return new LitPattern(p.Tok, CloneExpr(p.OrigLit));
```
Comment (davidcok) [inline Source/Dafny/Cloner.cs:687]: If CloneExpr is really producing a clone, shouldn't it copy both Lit and OrigLit?  (I wish every AST node has its own ShallowCopy and DeepCopy methods-- would make maintenance/extension more robust)

File: Test/git-issues/git-issue-889a.dfy [hunk 3]
```diff
@@ -0,0 +1,128 @@
+// RUN: %dafny "%s" > "%t"
```
Comment (davidcok) [inline Test/git-issues/git-issue-889a.dfy:1]: Check --128, with and without space, (for both bv8 and an 8-bit new type), just for good measure

**Review by davidcok — CHANGES_REQUESTED** [review]
0) There is a test failure to fix.

1) It is nice that this subsumed the problem of negated literals in the constant folding in new type definitions.

2) Perhaps we ought to enable constant folding in case patterns also.

File: Source/Dafny/Resolver.cs (hunk 1 above)
Comment (RustanLeino) [reply Source/Dafny/Resolver.cs:6105]: Done

File: Source/Dafny/Cloner.cs (hunk 2 above)
Comment (RustanLeino) [reply Source/Dafny/Cloner.cs:687]: The standard Clone routines output AST nodes with the same information as after parsing. This lets resolution recompute the remaining fields.

File: Test/git-issues/git-issue-889a.dfy (hunk 3 above)
Comment (RustanLeino) [reply Test/git-issues/git-issue-889a.dfy:1]: Done

File: Test/git-issues/git-issue-889a.dfy [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+    v := -(3);  // fine, since this is still a unary-minus expression applied to 3, and - wraps on bitvectors
+    assert v == 253;
+  case true =>
+    v := 200 + 100;  // fine, since 200 and 100 are both bv8 values, and + wraps on bitvectors
+    assert v == 44;
+}
+
+method BadBitvectors() returns (v: bv8) {
+  v := -(1);
+  assert v == 1;  // error
```
[the remark this answers is not in the document]
Comment (RustanLeino) [reply Test/git-issues/git-issue-889a.dfy:82]: Just checking that the unary minus didn't turn into the identity function

**Comment by RustanLeino** [comment]
We could enable constant folding in case patterns, but I suggest we wait with that until the need arises. Constant folding is currently used only for the purpose of figuring out nativeType settings for `newtype`s. Also, as I found when writing this PR, there's an ugly interaction between negations and case patterns, so trying to do constant folding there would increase the risk of us getting it wrong.

File: Test/git-issues/git-issue-889a.dfy [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+  case true =>
+    b := --128;  // error: the result of the unary minus, 128, is not a int8
+  case true =>
+    b := - - 128;  // error: the result of the unary minus, 128, is not a int8
+  case true =>
+    r := --1.0;  // error: the result of the unary minus, 1.0, is not a value of type smallneg
+  case true =>
+    r := - - 1.0;  // error: the result of the unary minus, 1.0, is not a value of type smallneg
+}
+
```
Comment (davidcok) [inline Test/git-issues/git-issue-889a.dfy:56]: For 'good literals' is -- allowed?  e.g. for bv8 is --5 a literal, equal to 5, or is it a unary minus expression -(-5)?

**Review by davidcok — COMMENTED** [review]
One little  question about -- - don't know whether it will need changes or not.

File: Test/git-issues/git-issue-889a.dfy (hunk 5 above)
Comment (RustanLeino) [reply Test/git-issues/git-issue-889a.dfy:56]: For an integer expression, `--5` is UnaryMinus(-5). For a bitvector, it is UnaryMinus(UnaryMinus(5)).

Comment (davidcok) [reply Test/git-issues/git-issue-889a.dfy:56]: I'm fine with this behavior. I think it is worth a little test to be sure this is the behavior. I believe the current grammar at least supports this, but I could imagine a grammar that said a literal is [0-9]+|[-]{literal} or something like that.

Comment (RustanLeino) [reply Test/git-issues/git-issue-889a.dfy:59]: I added a test to make sure that `--5` isn't in the future accidentally changed to stand for the literal `5` (instead of the unary-minus of `-5`).

I did this using a `newtype exactly5 = x | x == 5` rather than trying to use `--5` in a `case` label as we just discussed in person, because the latter gives a parse error.

**Review by davidcok — APPROVED** [review]
