### PR TITLE
Issue3482

### LINKED ISSUE #3482: Crash when using old inside match
### Dafny version

3.11.0

### Code to produce this issue

```dafny
datatype X = X(z: int)
lemma Foo(x: X) returns (y: bool) {
  match x {
    case X(z) => 
      return old(x) == x;
    case _ =>
  }
  return false;
}
```

### Command to run and resulting output

```code
Open the file in the IDE


[{
	"resource": "/Users/rwillems/Documents/Scratchpad/gutterIconBug.dfy",
	"owner": "dafny-vscode",
	"severity": 8,
	"message": "Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.\nSystem.NullReferenceException: Object reference not set to an instance of an object.\n   at Microsoft.Dafny.Translator.CanCallAssumption(Expression expr, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 4877\n   at Microsoft.Dafny.Translator.TrStmt_CheckWellformed(Expression expr, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran, Boolean subsumption, Boolean lValueContext) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 5243\n   at Microsoft.Dafny.Translator.TrAssignmentRhs(IToken tok, IdentifierExpr bGivenLhs, IVariable lhsVar, Type lhsType, AssignmentRhs rhs, Type rhsTypeConstraint, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 8753\n   at Microsoft.Dafny.Translator.ProcessRhss(List`1 lhsBuilder, List`1 bLhss, List`1 lhss, List`1 rhss, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 8360\n   at Microsoft.Dafny.Translator.TrAssignment(Statement stmt, Expression lhs, AssignmentRhs rhs, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 1084\n   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 253\n   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 213\n   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 55\n   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 7371\n   at Microsoft.Dafny.Translator.TrMatchStmt(MatchStmt stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 801\n   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 430\n   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 428\n   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 7371\n   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 302\n   at Microsoft.Dafny.Translator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 647\n   at Microsoft.Dafny.Translator.AddMethod_Top(Method m, Boolean isByMethod, Boolean includeAllMethods) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 198\n   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 71\n   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 1211\n   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 796\n   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyCore/Verifier/Translator.cs:line 867\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\n   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.<>c__DisplayClass8_0.<GetVerificationTasksAsync>b__1() in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs:line 51\n   at System.Threading.Tasks.Task`1.InnerInvoke()\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location ---\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n--- End of stack trace from previous location ---\n   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.GetVerificationTasksAsync(DocumentAfterResolution document, CancellationToken cancellationToken) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs:line 51\n   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.PrepareVerificationTasksAsync(DocumentAfterResolution loaded, CancellationToken cancellationToken) in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyLanguageServer/Workspace/Compilation.cs:line 131\n   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.TranslateAsync() in /Users/rwillems/Documents/SourceCode/dafny/Source/DafnyLanguageServer/Workspace/Compilation.cs:line 108",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```
```


### What happened?

No crash

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Fixes #3482

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/AST/Expressions/OldExpr.cs [hunk 1]
```diff
@@ -14,13 +14,17 @@ public class OldExpr : Expression, ICloneable<OldExpr>, ICanFormat {
     Contract.Invariant(E != null);
   }
 
-  public OldExpr Clone(Cloner cloner) {
-    var result = new OldExpr(cloner.Tok(tok), cloner.CloneExpr(E), At);
+  public OldExpr(Cloner cloner, OldExpr original) : base(cloner, original) {
+    E = cloner.CloneExpr(original.E);
```
Comment (MikaelMayer) [inline Source/DafnyCore/AST/Expressions/OldExpr.cs:18]: As far as I can tell, the only difference with the previous code is that you are not cloning the token. Is cloning the token the thing that make it crash?

Comment (atomb) [reply Source/DafnyCore/AST/Expressions/OldExpr.cs:18]: Previously it _wasn't_ cloning the `Type` field, which is what led to the crash.

**Review by atomb — APPROVED** [review]
Looks nice!
