### PR TITLE
Solution to issue 2265 related to erroneous substitution under bindin…

### LINKED ISSUE #2265: ArgumentNullException in Translator.CheckDefiniteAssignment
repro:
```dafny
function Succ(x: int): int
{
  x + 1
}

function FailingLemma(): nat
{
  var st : set<int> :| forall x | x in st :: Succ(x) > 0;
  assert true by {
    if x: nat :| Succ(x) > 1 {
      assert Succ(x) > 0;
    }
  }
  0
}
```

output:
```
$ dafny /version
Dafny 3.6.0.40511
$ dafny repro.dfy 
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Dafny.Translator.CheckDefiniteAssignment(IdentifierExpr expr, BoogieStmtListBuilder builder)
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt_CheckWellformed(Expression expr, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran, Boolean subsumption, Boolean lValueContext)
   at Microsoft.Dafny.Translator.TrPredicateStmt(PredicateStmt stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt2StmtList(BoogieStmtListBuilder builder, Statement block, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrIfStmt(IfStmt stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrPredicateStmt(PredicateStmt stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.CheckWellformedLetExprWithResult(LetExpr e, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran, Boolean checkRhs)
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran)
   at Microsoft.Dafny.Translator.AddWellformednessCheck(Function f)
   at Microsoft.Dafny.Translator.AddFunction_Top(Function f, Boolean includeAllMethods)
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods)
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d)
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule)
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext()
   at Microsoft.Dafny.DafnyDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args)
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0()
   at System.Threading.Thread.StartCallback()
Aborted
```

Related to #2264, this was the kind of exception I was getting that led me to #2264

### PR DESCRIPTION
**Pull request by jtristan**
…g guards

Fixes #2265 

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Substituter.cs [hunk 1]
```diff
@@ -930,7 +979,73 @@ public class Substituter {
...
+      // For quantifiers and setComprehesion we want to make sure that we don't introduce name clashes with
+      // the enclosing scopes.
+
+      var q = e as QuantifierExpr;
+      if (q != null && q.SplitQuantifier != null) {
+        if (forceSubstituteOfBoundVars) {
+          return Substitute(q.SplitQuantifierExpression);
+        } else {
+          return SubstituteComprehensionExpr((ComprehensionExpr)q.SplitQuantifierExpression, false);
+        }
```
Comment (cpitclaudel) [inline Source/DafnyCore/Substituter.cs:1006]: As written, I think this code could be simplified to the following, because if `q.SplitQuantifierExpression` is a `ComprehensionExpr`, then the call to Substitute will immediately call `SubstituteComprehensionExpr(…, true)`.

```csharp
return SubstituteComprehensionExpr((ComprehensionExpr)q.SplitQuantifierExpression, forceSubstituteOfBoundVars);
```

However, I'm not sure this code is correct, because `q.SplitQuantifierExpression` is a conjunction of quantifiers, not a quantifier itself.  I would expect this code to raise an exception if it encounters a split quantifier — not just your new code, but also the old code.

This is because `Substitute(q.SplitQuantifierExpression);` was always wrong: it takes a quantifier and returns a conjunction or disjunction of quantifiers, so when applied to the `BindingGuard` of an `If` it replaces an `ExistsExpr` with a `BinaryExpr`, which confuses later parts of the code.  Here's a repro of this:

```
function method f(x: int): int { 10 - x * x }

function method BindingGuardTest(): int {
  var x: nat := 1;
  assert true by {
    if i :| 0 <= i < 10 && (f(i) == f(i+1) || f(i) == f(i+2)) {
      // print i;
    }
  }
  2
}
```

which outputs:

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.BinaryExpr' to type 'Microsoft.Dafny.ExistsExpr'.
   at Microsoft.Dafny.Translator.TrIfStmt(IfStmt stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) 
```

For the bottom branch the fix would be to ignore the split expressions, I think.  But for the top branch if we want to preserve the splits then I think we have to apply the substitution on each of them.  @RustanLeino , thoughts?

File: Source/DafnyCore/Substituter.cs [hunk 2]
```diff
@@ -930,7 +979,73 @@ public class Substituter {
...
+
+    /// <summary>
+    /// Substitution in a comprehension expression. 
+    /// Parameter 'forceSubstituteOfBoundVars' should be set to false if and only if
+    /// the expression is a binding guard, in which case a bound variable is introduced.
+    /// Such a variable must not be substituted. 
+    /// </summary>
+    protected Expression SubstituteComprehensionExpr(ComprehensionExpr expr, bool forceSubstituteOfBoundVars) {
+
+      Expression newExpr = null;
```
Comment (cpitclaudel) [inline Source/DafnyCore/Substituter.cs:994]: Could this be a `ComprehensionExpr` instead of an `Expr`?

File: Source/DafnyCore/Substituter.cs [hunk 3]
```diff
@@ -930,7 +979,73 @@ public class Substituter {
...
+          newExpr = new ExistsExpr(expr.tok, e.BodyEndTok, newBoundVars, newRange, newTerm, newAttrs);
+        } else if (expr is LambdaExpr) {
+          var l = (LambdaExpr)expr;
+          newExpr = new LambdaExpr(e.BodyStartTok, e.BodyEndTok, newBoundVars, newRange,
+            l.Reads.ConvertAll(SubstFrameExpr), newTerm);
+        } else {
+          Contract.Assert(false); // unexpected ComprehensionExpr
+        }
+
+        ((ComprehensionExpr)newExpr).Bounds = newBounds;
```
Comment (cpitclaudel) [inline Source/DafnyCore/Substituter.cs:1037]: I think you won't need the cast here if you change the declaration of `newExpr`)

File: Source/DafnyCore/Substituter.cs [hunk 4]
```diff
@@ -930,7 +979,73 @@ public class Substituter {
...
+      }
+
+      // undo any changes to substMap (could be optimized to do this only if newBoundVars != e.BoundVars)
+      foreach (var bv in e.BoundVars) {
+        substMap.Remove(bv);
+      }
+
+      return newExpr;
```
Comment (cpitclaudel) [inline Source/DafnyCore/Substituter.cs:1045]: Could we add an assertion before this to say when `newExpr` can be null?
I think it's something like this?

```
Contract.Assert(!forceSubstituteOfBoundVars ==> newExpr != null)
```

I was confused when I first read through the code to see that this was used directly in the `if` case but that it may also return null.

File: Test/git-issues/git-issue-2265.dfy [hunk 5]
```diff
@@ -0,0 +1,18 @@
+// RUN: %dafny /compile:0 "%s" > "%t"
+// RUN: %diff "%s.expect" "%t"
+
+module DefaultModule {
+  class DefaultClass {
+    static function BrokenFunction(): nat {
+      var y := 0;
+			assert true by {
```
Comment (cpitclaudel) [inline Test/git-issues/git-issue-2265.dfy:8]: The indentation is wrong here

**Review by cpitclaudel — CHANGES_REQUESTED** [review]
Great fix!  A few suggestions:

- There are still a few whitespace-only changes in unrelated parts of the code that would be nice to undo
- I think this PR is missing a fix for the `if-case` pattern that @RustanLeino sent an example of in the original issue discussion (`if x :| P(x) => …`)
- The split-quantifiers case isn't quite right, I think — but the original code was broken too (!)
- I've left other small comments in the code

File: Source/DafnyCore/Substituter.cs (hunk 1 above)
Comment (jtristan) [reply Source/DafnyCore/Substituter.cs:1006]: I am going to apply the simplification that you suggest. As for the issue with the split quantifiers, since it is a different issue, I will open a new issue to report it.

File: Source/DafnyCore/Substituter.cs (hunk 4 above)
Comment (jtristan) [reply Source/DafnyCore/Substituter.cs:1045]: We could but here is my concern: it is not actually a required invariant, it just happens to be implemented that way to match the rest of the code.

**Comment by jtristan** [comment]
With respect to the additional issue raised by Rustan involving a case statement, I decided to create a new issue because even if the fix might be small and simple, I would first like to make sure I understand the semantics, and I will add a new corresponding test.

File: Source/DafnyCore/Substituter.cs (hunk 1 above)
Comment (jtristan) [reply Source/DafnyCore/Substituter.cs]: I created a new issue #2748 to continue this discussion.

File: Source/DafnyCore/Substituter.cs [hunk 6]
```diff
@@ -262,58 +275,26 @@ public class Substituter {
...
           cases.Add(newCaseExpr);
         }
+
         if (anythingChanged) {
           var newME = new MatchExpr(expr.tok, src, cases, e.UsesOptionalBraces);
           newME.MissingCases.AddRange(e.MissingCases);
           newExpr = newME;
         }
 
       } else if (expr is ComprehensionExpr) {
```
[the remark this answers is not in the document]
Comment (jtristan) [reply Source/DafnyCore/Substituter.cs:291]: I will remain consistent with the rest of the code.

File: Source/DafnyCore/Substituter.cs (hunk 2 above)
Comment (jtristan) [reply Source/DafnyCore/Substituter.cs:972]: Not sure. ```SplitQuantifierExpression``` returns an Expression, and not a ComprehensionExpression.

File: Source/DafnyCore/Substituter.cs [hunk 7]
```diff
@@ -930,7 +979,73 @@ public class Substituter {
...
       return attrs;
     }
+
+    /// <summary>
+    /// Substitution in a comprehension expression. 
+    /// Parameter 'forceSubstituteOfBoundVars' should be set to false if and only if
+    /// the expression is a binding guard, in which case a bound variable is introduced.
+    /// Such a variable must not be substituted. 
+    /// </summary>
+    protected Expression SubstituteComprehensionExpr(ComprehensionExpr expr, bool forceSubstituteOfBoundVars) {
```
[the remark this answers is not in the document]
Comment (jtristan) [reply Source/DafnyCore/Substituter.cs:970]: Not sure. SplitQuantifierExpression returns an Expression, and not a ComprehensionExpression.

**Review by cpitclaudel — CHANGES_REQUESTED** [review]
Thanks!  Can you revert the whitespace-only changes?  Then we can merge! :)

**Review by cpitclaudel — APPROVED** [review]

**Review by cpitclaudel — APPROVED** [review]
