### PR TITLE
fix: References to built-in types in C#

### LINKED ISSUE #4284: `/compileSuffix:1` breaks references to built-in types in C#
### Dafny version

master

### Code to produce this issue

```dafny
method Main(){
  print (true, false), "\n";
}
```

### Command to run and resulting output

```code
dafny /compile:4 /compileTarget:cs /compileSuffix:1 <file>.dfy
```

### What happened?

Bad names.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by fabiomadge**
Fixes #4284.

### CODE REVIEW

**Review by keyboardDrummer — DISMISSED** [review]
Sweet, thanks !!

File: Source/DafnyCore/AST/Modules/ModuleDefinition.cs [hunk 1]
```diff
@@ -170,7 +170,7 @@ public class ModuleDefinition : RangeNode, IDeclarationOrUsage, IAttributeBearin
   public string GetCompileName(DafnyOptions options) {
     if (compileName == null) {
       var externArgs = options.DisallowExterns ? null : Attributes.FindExpressions(this.Attributes, "extern");
-      var nonExternSuffix = (options.Get(CommonOptionBag.AddCompileSuffix) ? "_Compile" : "");
+      var nonExternSuffix = (options.Get(CommonOptionBag.AddCompileSuffix) && Name != "_module" && Name != "_System" ? "_Compile" : "");
```
Comment (keyboardDrummer) [inline Source/DafnyCore/AST/Modules/ModuleDefinition.cs:173]: Could be slightly nicer to replace these string literals with a shared variable, like `SystemModuleManager.ModuleName` and `DefaultModuleDefinition.Name`

File: Source/TestDafny/MultiBackendTest.cs [hunk 2]
```diff
@@ -172,6 +172,10 @@ public class MultiBackendTest {
       return false;
     }
 
+    if (option is "--compile-suffix") {
```
Comment (keyboardDrummer) [inline Source/TestDafny/MultiBackendTest.cs:175]: Here I think `CommonOptionBag.AddCompileSuffix.Name` would be better than the string literal

File: Source/DafnyCore/AST/Modules/ModuleDefinition.cs (hunk 1 above)
Comment (fabiomadge) [reply Source/DafnyCore/AST/Modules/ModuleDefinition.cs:173]: I couldn't get either.

Comment (keyboardDrummer) [reply Source/DafnyCore/AST/Modules/ModuleDefinition.cs:173]: I'm not sure what you mean, but you'd have to create those constants since they don't exist yet.

Comment (fabiomadge) [reply Source/DafnyCore/AST/Modules/ModuleDefinition.cs:173]: I see, I was expecting them to be there.

**Review by robin-aws — APPROVED** [review]
