### PR TITLE
fix: Legacy datatype constructor compatibility in Java

### LINKED ISSUE #5553: Helpers.unsignedLongToBigInteger removed from Java runtime
This is only a problem because Java projects with Dafny-generated code in them will declare a dependency on the Java runtime of the same version, but this is interpreted as a minimum dependency and may be upgraded if some other project needs a newer version. That means in general we can't remove things from the runtimes even if they are only ever referenced by Dafny-generated code.

It's not yet clear why this doesn't show up in any customer nightly build testing: [the change that removed it](https://github.com/dafny-lang/dafny/pull/4384) should have already been released in 4.6, so the fact that we don't pre-release the runtimes isn't at fault.

### PR DESCRIPTION
**Pull request by robin-aws**
### Description
Addresses the specific problem described in #5555, without yet setting up enough regression testing for the general problem.

Adds a hidden `--legacy-data-constructors` option for the Java backend, to create `@Deprecated()` overloads of methods that create data constructors such as `create_Foo` and `Default` that don't take TypeDescriptor arguments and instead initialize them to `null`, so that Dafny code generated before #4240 is not broken.

Also fixes #5553.

### How has this been tested?
Cloned `separate-compilation/usesTimesTwo.dfy` to create a version with the Java code for the consuming code pre-compiled using Dafny 4.2 checked in.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Backends/Java/JavaBackend.cs [hunk 1]
```diff
@@ -26,6 +29,17 @@ public class JavaBackend : ExecutableBackend {
   public override bool SupportsInMemoryCompilation => false;
   public override bool TextualTargetIsExecutable => false;
 
+  public static readonly Option<bool> LegacyDataConstructors = new("--legacy-data-constructors",
+    @"Generate deprecated data constructor methods".TrimStart())  {
```
Comment (robin-aws) [inline Source/DafnyCore/Backends/Java/JavaBackend.cs:33]: Will expand the description a bit more

**Review by keyboardDrummer — APPROVED** [review]
Great work, thanks

**Review by RustanLeino — COMMENTED** [review]
Nice. Thanks!

**Review by keyboardDrummer — APPROVED** [review]
