### PR TITLE
Fix: Support for aliases in module resolution without crashing on imports

### LINKED ISSUE #2108: Crash in ModuleQualifiedId.Set
Input:

```
module M0.M1.Base {}

module M0.M2 {
  import M1.Base

  module Derived refines Base {
  }
}
```

Output:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dafny.AliasModuleDecl' to type 'Microsoft.Dafny.LiteralModuleDecl'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.AliasModuleDecl' to type 'Microsoft.Dafny.LiteralModuleDecl'.
   at Microsoft.Dafny.ModuleQualifiedId.Set(ModuleDecl m) in C:\dafny\Source\Dafny\AST\DafnyAst.cs:line 3943
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in C:\dafny\Source\Dafny\Resolver.cs:line 492
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in C:\dafny\Source\Dafny\DafnyMain.cs:line 162
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in C:\dafny\Source\Dafny\DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 249
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 67
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0() in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 47
   at System.Threading.Thread.StartCallback()
```

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #2108
Basically, we were trying to call ModuleQualifiedId.Set() on something else than a LiteralModuleDecl, and it happened it was an AliasModuleDecl. Since we were only interested by the underlying ModuleDefinition, I added a case to ensure it does not crash for AliasModuleDecl

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/AST/TopLevelDeclarations.cs [hunk 1]
```diff
@@ -595,7 +595,9 @@ public class ModuleQualifiedId {
       this.Sig = null;
     } else {
       this.Decl = m;
-      this.Def = ((LiteralModuleDecl)m).ModuleDef;
+      this.Def = m is AliasModuleDecl ?
+        m.Signature.ModuleDef :
+        ((LiteralModuleDecl)m).ModuleDef;
```
Comment (cpitclaudel) [inline Source/DafnyCore/AST/TopLevelDeclarations.cs:600]: Could we always use `m.Signature.ModuleDef`, or is there a way to make this consistent without having a special case?  Otherwise I'm not sure how to review this :/

**Review by cpitclaudel — CHANGES_REQUESTED** [review]

File: Source/DafnyCore/AST/TopLevelDeclarations.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/DafnyCore/AST/TopLevelDeclarations.cs]: > Could we always use m.Signature.ModuleDef, or is there a way to make this consistent without having a special case? Otherwise I'm not sure how to review this :/

Right ! That's a good observation. Since all modules have a signature and each signature has a module definition, what you suggest seems strictly better for maintainability.
I implemented the fix. Reviewing it should be easier now.

**Review by cpitclaudel — APPROVED** [review]
Thanks!  If the tests pass, then this is much better! :)
