### PR TITLE
Fixes #262: Corrects translation of print statements for values of function type in C#

### LINKED ISSUE #262: inconsistency in how print is compiled
```
function method tst (x : nat) : nat {
    x + 1
}

method Main() {
    var f := tst;
    print(f);
    print(tst);
}
```

The first print succeeds to compile, but the second print fails to do so

### PR DESCRIPTION
**Pull request by davidcok**

### CODE REVIEW

File: Source/Dafny/Compiler-java.cs [hunk 1]
```diff
@@ -1978,7 +1978,9 @@ private class GenericArrayElementLvalue : ILvalue {
 
     protected void EmitToString(TargetWriter wr, Expression arg) {
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-java.cs:1979]: Judging from the uses of `EmitToString` in Compiler-java.cs, I'm thinking the fix in this PR should perhaps also be applied `expect` statements. Or, please add tests for `expect` as well, to make sure there are no cast problems there.

File: Source/Dafny/Compiler-java.cs [hunk 2]
```diff
@@ -1978,7 +1978,9 @@ private class GenericArrayElementLvalue : ILvalue {
...
       if (arg.Type.IsArrowType) {
-        wr.Write(IdName(((IdentifierExpr) ((ConcreteSyntaxExpression)arg).ResolvedExpression).Var) + " == null ? null : \"Function\"");
+        var expr = ((ConcreteSyntaxExpression)arg).ResolvedExpression;
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-java.cs:1981]: There's no reason to believe `arg` is a `ConcreteSyntaxExpression`. The proper way to do this is:

    var expr = arg.Resolved;

File: Source/Dafny/Compiler-java.cs [hunk 3]
```diff
@@ -1978,7 +1978,9 @@ private class GenericArrayElementLvalue : ILvalue {
...
+        if (expr is IdentifierExpr) wr.Write(IdName(((IdentifierExpr) expr).Var) + " == null ? null : \"Function\"");
+        else wr.Write("\"Function\"");
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-java.cs:1983]: Always use curly braces around both "then" and `else` alternatives.

Also, instead of writing `expr is IdentifierExpr` and then doing the cast, C# allows you to write

    if (expr is IdentifierExpr x) {
        ...  x.Var ...

The mechanism is not perfect, because of where `x` is scoped, but it works well in this case.

File: Source/Dafny/Compiler-Csharp.cs [hunk 4]
```diff
@@ -1147,8 +1147,21 @@ protected class ClassWriter : IClassWriter {
     // ----- Statements -------------------------------------------------------------
 
     protected override void EmitPrintStmt(TargetWriter wr, Expression arg) {
-      wr.Write("Dafny.Helpers.Print(");
-      TrExpr(arg, wr, false);
+      wr.Write("Dafny.Helpers.Print");
+      if (arg.Type.AsArrowType != null) {
+        string typestr = TypeName(arg.Type, wr, null, null);
+        wr.Write("<" + typestr+ " >");
```
[the remark this answers is not in the document]
Comment (davidcok) [reply Source/Dafny/Compiler-Csharp.cs:1153]: OK

File: Source/Dafny/Compiler-Csharp.cs [hunk 5]
```diff
@@ -1147,8 +1147,21 @@ protected class ClassWriter : IClassWriter {
     // ----- Statements -------------------------------------------------------------
 
     protected override void EmitPrintStmt(TargetWriter wr, Expression arg) {
-      wr.Write("Dafny.Helpers.Print(");
-      TrExpr(arg, wr, false);
+      wr.Write("Dafny.Helpers.Print");
+      if (arg.Type.AsArrowType != null) {
```
[the remark this answers is not in the document]
Comment (davidcok) [reply Source/Dafny/Compiler-Csharp.cs:1151]: Because the full test suite failed on some user defined integer types when I did that. The oddball case appeared to be these arrow types.

File: Source/Dafny/Compiler-Csharp.cs [hunk 6]
```diff
@@ -1147,8 +1147,21 @@ protected class ClassWriter : IClassWriter {
...
+        wr.Write("<" + typestr+ " >");
+      }
+
+      wr.Write("(");
+      // var t = arg.Type as ArrowType;
+      // var ttt = arg.Type as UserDefinedType;
+      // if (arg is NameSegment && arg.Resolved is MemberSelectExpr) {
+      //   wr.Write("\"Function\"");
+      // } else {
+        TrExpr(arg, wr, false);
```
[the remark this answers is not in the document]
Comment (davidcok) [reply Source/Dafny/Compiler-Csharp.cs:1162]: and deleted the commented code

File: Test/git-issues/git-issue-262.dfy [hunk 7]
```diff
@@ -0,0 +1,15 @@
+// RUN: %dafny /compile:4 /compileTarget:cs "%s" > "%t"
+// RUN: %dafny /compile:4 /compileTarget:js "%s" >> "%t"
+// RUN: %dafny /compile:4 /compileTarget:go "%s" >> "%t"
+// RUN: %dafny /compile:4 /compileTarget:java "%s" >> "%t"
+// RUN: %diff "%s.expect" "%t"
+
+function method tst (x : nat) : nat {
```
[the remark this answers is not in the document]
Comment (davidcok) [reply Test/git-issues/git-issue-262.dfy:7]: Comes from cutting and pasting example code from other people's issues. Fixed.

File: Source/Dafny/Compiler-java.cs (hunk 2 above)
Comment (davidcok) [reply Source/Dafny/Compiler-java.cs:1981]: Fixed. Still learning this type hierarchy.

File: Source/Dafny/Compiler-java.cs (hunk 3 above)
Comment (davidcok) [reply Source/Dafny/Compiler-java.cs:1983]: handy if hacky

File: Source/Dafny/Compiler-java.cs (hunk 1 above)
Comment (davidcok) [reply Source/Dafny/Compiler-java.cs:1979]: Expect takes a boolean -- so are you thinking of general casts in expressions? I'll make a separate Issue for expect (and assert and assume?) if so.
