### PR TITLE
Fix: Ghost diagnostics correctly updated when becoming empty

### LINKED ISSUE #4693: Ghost diagnostics not correctly updated
### Dafny version

4.3.0

### Code to produce this issue

```dafny
class A {
}


method Test(a: object) {
  if a is A {
  }
}
```

### Command to run and resulting output

```code
Paste the code above in VS Code.
The lines `if a is A {}` are highlighted in ghost correctly.
Now, inside the braces, write
`print "hello";`
Now delete lines 3-5, and press enter 6 times to reproduce the animated screenshot below.
```

### What happened?

9c1b49e0-0a1d-4f3b-8c93-24c8cb11fbc7

What's going on 
- There is no more ghost code in the code, and the language server does not send a notification to the client. Hence, the client does not know that there is no more ghost code and continues to highlight the region of previous ghost code as ghost.
- You can verify this hypothesis by writing another method that contains ghost code, immediately the ghost code is updated.

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #4693
I added a test that was previously failing.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyLanguageServer/Workspace/NotificationPublisher.cs [hunk 1]
```diff
@@ -259,6 +259,17 @@ public class NotificationPublisher : INotificationPublisher {
           }).ToArray(),
         });
       }
+
+      // If we don't have ghost state anymore, publish empty ghost diagnostics
```
Comment (keyboardDrummer) [inline Source/DafnyLanguageServer/Workspace/NotificationPublisher.cs:263]: Could you merge the two loops?

```c#
var uris == previousParams.Keys.Concat(params.Keys);
      foreach (var uri in uris) {
var previous = previousParams.GetValueOrDefault(uri) ?? Enumerable<Range>.Empty();
var current = currentParams.GetValueOrDefault(uri) ?? Enumerable<Range>.Empty();
          if (previous.SequenceEqual(current)) {
            continue;
          }
        languageServer.TextDocument.SendNotification(new GhostDiagnosticsParams {
          Uri = uri,
          Version = state.Version,
          Diagnostics = current.Select(r => new Diagnostic {
            Range = r
          }).ToArray(),
        });
      }

```

**Review by keyboardDrummer — APPROVED** [review]

**Comment by keyboardDrummer** [comment]
Nice! Thanks
