### PR TITLE
fix: Make TraitParent a relation, not a function

### LINKED ISSUE #580: Extending multiple traits leads to contradiction
To reproduce:

```
trait A {}
trait B {}
class C extends A, B {
  method Foo() {
    assert false;
  }
}
```

Removing either `A` or `B` in the `extends` clause allows the verifier to correctly flag the false assertion. The issue seems to be that the translation to Boogie asserts that the trait parent of a class is unique, and hence the fact that `A != B` leads to a contradiction.

### PR DESCRIPTION
**Pull request by RustanLeino**
Like the previous TraitParent, the new relation IsTraitParent isn't actually used for anything, so it's more of a placeholder for some future use.

Fixes #580

### CODE REVIEW

File: Source/Dafny/Translator.cs [hunk 1]
```diff
@@ -1067,55 +1064,29 @@ internal class PredefinedDecls {
     }
 
     /// <summary>
-    /// adding TraitParent axioms
-    /// if a class A extends trait J and B does not extend anything, then this method adds the followings to the sink:
-    ///   axiom TraitParent(class.A) == class.J;
-    ///   axiom TraitParent(class.B) == NoTraitAtAll;
+    /// For every revealed type (class or trait) C that extends a trait J, add:
```
Comment (robin-aws) [inline Source/Dafny/Translator.cs:1067]: I know the AST supports traits extending traits, but AFAICT the parser doesn't. I think it's fine to be forwards-compatible here, but probably worth mentioning it in the comment to avoid confusion.
