### PR TITLE
Fix: Triggers warnings correclty converted into errors with --warn-as-errors

### LINKED ISSUE #3358: "No trigger covering all quantified variables found" is still a warning with `/warningsAsErrors`
### Dafny version

master (f6bd1b8e13250ec31d6db0400ce8a32a9560fcad)

### Code to produce this issue

```dafny
datatype MyResult = Ok | Err(error: set<string>)
function method warningTriggerTest(sr: seq<MyResult>): set<string> {
  set i, err | 0 <= i < |sr| && err in (if sr[i].Err? then sr[i].error else {}) :: err
}
```

### Command to run and resulting output

```code
% ./dafny /compile:0 /warningsAsErrors warning-trigger.dfy
.../warning-trigger.dfy(3,2): Warning: /!\ No trigger covering all quantified variables found.

Dafny program verifier finished with 1 verified, 0 errors
```

### What happened?

I'd expect `/warningsAsErrors` to convert the warning to an error, or else the documentation should explain why it doesn't.

### What type of operating system are you experiencing the problem on?

Linux

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #3358
I also verified that there was no other places where we were missing to convert warnings as errors by looking at all usages of "ErrorLevel.Warning".
Tests added

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Triggers/QuantifiersCollection.cs [hunk 1]
```diff
@@ -338,7 +339,7 @@ internal class QuantifierGroup {
           msg.Append(WARN).AppendLine("Suppressing loops would leave this expression without triggers.");
           FirstLetterCapitalOnNestedToken();
         } else if (suppressWarnings) {
-          errorLevel = ErrorLevel.Warning;
+          errorLevel = options.WarningsAsErrors ? ErrorLevel.Error : ErrorLevel.Warning;
```
Comment (keyboardDrummer) [inline Source/DafnyCore/Triggers/QuantifiersCollection.cs:342]: Isn't this the wrong location to check `options.WarningsAsErrors` ? Why wouldn't the reporter do that check? (as it already mostly does, but only when you call `reporter.Warning`, not when you call `reporter.Message`

Comment (MikaelMayer) [reply Source/DafnyCore/Triggers/QuantifiersCollection.cs]: Agreed. Implemented.

File: Source/DafnyCore/Triggers/QuantifiersCollection.cs [hunk 2]
```diff
@@ -347,7 +347,11 @@ internal class QuantifierGroup {
 
       if (msg.Length > 0 && !Attributes.Contains(q.quantifier.Attributes, "auto_generated")) {
         var msgStr = msg.ToString().TrimEnd("\r\n ".ToCharArray());
-        reporter.Message(MessageSource.Rewriter, errorLevel, null, reportingToken, msgStr);
```
Comment (keyboardDrummer) [inline Source/DafnyCore/Triggers/QuantifiersCollection.cs:350]: Shouldn't we fix `reporter.Message` so it can't be used incorrectly?

**Review by keyboardDrummer — APPROVED** [review]

**Review by keyboardDrummer — APPROVED** [review]

**Review by keyboardDrummer — DISMISSED** [review]
