### PR TITLE
Opaque modifies clause

### LINKED ISSUE #6217: Opaque blocks not handling modifies clauses correctly
### Dafny version

4.10.1

### Code to produce this issue

```dafny
class Test
{
  var x : int
  var y : int

  method foo()
    modifies this
    ensures x == 1
    ensures y == 1
  {
    x := 1;
    opaque
      modifies this`y
      ensures y == 1
      // ensures x == 1
    {
      y := 1;
    }
  }
}
```

### Command to run and resulting output

```code
dafny verify test.dfy 
test.dfy(11,2): Error: a postcondition could not be proved on this return path
   |
11 |   {
   |   ^

test.dfy(9,14): Related location: this is the postcondition that could not be proved
  |
9 |     ensures x == 1
  |               ^^


Dafny program verifier finished with 0 verified, 1 error
```

### What happened?

Assertions which hold before an opaque block, and whose truth-value cannot change due to the frame condition, cannot be proven after the opaque block (unless explicitly stated as part of the ensures clause of the opaque block).

This behaviour is unexpected since it is contrary to the behaviour of the same program with the opaque block replaced by either a method call or a loop, with similar specifications.

### What type of operating system are you experiencing the problem on?

Linux

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Fixes #6217

### What was changed?
- Let modifies clauses of opaque blocks use the heap before the block as 'old', instead of the one at the start of the method.

### How has this been tested?
- Added a test case to opaqueBlock.dfy

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Verifier/Statements/OpaqueBlockVerifier.cs [hunk 1]
```diff
@@ -53,11 +54,20 @@ public static void EmitBoogie(BoogieGenerator generator, OpaqueBlock block, Boog
             methodCodeContext.Modifies.Expressions
           ), null);
       }
+
```
Comment (ssomayyajula) [inline Source/DafnyCore/Verifier/Statements/OpaqueBlockVerifier.cs:57]: So the same heap variable as before an opaque block was used afterward? And since whatever on the heap belonging to the modifies clause was wiped, it was an incompleteness and not an unsoundness?

Comment (keyboardDrummer) [reply Source/DafnyCore/Verifier/Statements/OpaqueBlockVerifier.cs:57]: I'm not sure I understand the question. I would guess this fix fixes an unsoundness, but I'm not sure. Previously it was using the wrong heap in the assumptions generated from the opaque block's modifies clause.

Comment (ssomayyajula) [reply Source/DafnyCore/Verifier/Statements/OpaqueBlockVerifier.cs:57]: Got it, that's all I needed to know. Approved!

**Review by ssomayyajula — APPROVED** [review]
