### PR TITLE
#327, #659: Fixing module name lookup in refines parent

### LINKED ISSUE #327: importing qualified module in a refining module doesn't recognize module imported in parent
This code:
```
module A {
}

module B {
  import A
}

module C {
  import B
}

module D refines C {
  import A = B.A
}
```
gives the error message:
```
$ dafny test1.dfy 
Dafny 2.3.0.10506
test1.dfy(13,13): Error: module B does not exist (position 0 in path B.A)
1 resolution/type errors detected in test1.dfy
```

One might infer from this error message that the right fix is to re-import B from D. That
doesn't work either:
```
module A {
}

module B {
  import A
}

module C {
  import B
}

module D refines C {
  import B
  import A = B.A
}
```
gives this error message:
```
$ dafny test2.dfy 
Dafny 2.3.0.10506
test2.dfy(13,9): Error: a module (B) can only refine a module facade
```

My guess is that the second example is expected, and the first is not.

### PR DESCRIPTION
**Pull request by davidcok**
Fixes #327, #659

Fixes the logic for resolving a qualified name for a module.
Does not requires 'import A' before 'import A.B'
Implements export sets for qualified names: import Z = A.B.C`{X,Y}

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -2130,7 +2130,18 @@ public class ModuleBindings
       }
 
       // Although the module is known, we demand it be imported before we're willing to access it.
-      var thisImport = parent.TopLevelDecls.FirstOrDefault(t => t.Name == Path[0].val && t != alias);
+      // Imports are resolved before their containing module, so we cannot rely on
+      // the parent module to have any names that might come in through refines.
+      // However the parent refines will lready have been fully refined.
+      ModuleDefinition par = parent;
+      TopLevelDecl thisImport = null;
+      thisImport = par.TopLevelDecls.FirstOrDefault(t => t.Name == Path[0].val && t != alias);
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:2138]:
```suggestion
      TopLevelDecl thisImport = par.TopLevelDecls.FirstOrDefault(t => t.Name == Path[0].val && t != alias);
```

**Review by RustanLeino — APPROVED** [review]
