### PR TITLE
Try to treat general map comprehension as the common case

### LINKED ISSUE #336: Map created with comprehension shorthand vs full comprehension
For the following:
```cs
    var a := map[2 := (3, 5), 3 := (5, 8)];
    assert (map k | k in a :: k := a[k].0)
        == (map k | k in a :: a[k].0); // <- this is line 8
```
Note that the second map comprehension implicitly uses `k` as the key
(`k := a[k].0` vs `a[k].0`)

I get:
```
examples/map-comprehension.dfy(8,8): Error: assertion violation
```

@samuelgruetter on Gitter suggests proving it with:
```cs
predicate submap<K, V>(m1: map<K, V>, m2: map<K, V>) {
    forall k :: k in m1 ==> k in m2 && m1[k] == m2[k]
}

lemma map_ext<K, V>(m1: map<K, V>, m2: map<K, V>)
    requires submap(m1, m2)
    requires submap(m2, m1)
    ensures m1 == m2
{}

method test() {
    var a := map[2 := (3, 5), 3 := (5, 8)];
    map_ext(map k | k in a :: k := a[k].0, map k | k in a :: a[k].0);
    assert (map k | k in a :: k := a[k].0)
        == (map k | k in a :: a[k].0);
}
```

But we believe this should be provable without the `map_ext` hint.

### PR DESCRIPTION
**Pull request by RustanLeino**
If a general map comprehension has the form `map x | R(x) :: x := T(x)`, then
translate it (in the verifier) in the same way as the common `map x | R(x) :: T(x)`.

Fixes #336

### CODE REVIEW

File: Source/Dafny/DafnyAst.cs [hunk 1]
```diff
@@ -10224,6 +10224,31 @@ public MapComprehension(IToken tok, bool finite, List<BoundVar> bvars, Expressio
       TermLeft = termLeft;
     }
 
+    /// <summary>
```
Comment (seanmcl) [inline Source/Dafny/DafnyAst.cs]: Curious, what tool processes these xml tags?

Comment (seanmcl) [reply Source/Dafny/DafnyAst.cs]: Could we have a comment why being a general map comprehension is significant?  (Maybe just a copy of the detail of the PR, if that's the only significance.)

File: Test/git-issues/git-issue-336.dfy [hunk 2]
```diff
@@ -0,0 +1,27 @@
+// RUN: %dafny "%s" > "%t"
+// RUN: %diff "%s.expect" "%t"
+
+lemma TestMap(a: map<int, (int,int)>) {
```
Comment (seanmcl) [inline Test/git-issues/git-issue-336.dfy]: Nice.

File: Source/Dafny/DafnyAst.cs (hunk 1 above)
Comment (RustanLeino) [reply Source/Dafny/DafnyAst.cs]: These xml tags are used by the IDE (at least in Visual Studio, and I'm guessing also in Rider, but I haven't thought about it) to display hover text as information about the method.

The general map comprehensions were needed in some example where it was impossible to create the desired map with the simpler (and far more common) map comprehension. I think this is the example:

    map x | x in S :: f(x) := g(x)
