### PR TITLE
Fix: Dafny Rust runtime no longer checks if RC increased by one when concurrent

### LINKED ISSUE #6247: Dafny runtime fails when objects read concurrently
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
#[test]
      fn test_object_share_async() {
        let obj = ClassWrapper::constructor_object(53);
        let objClone = obj.clone();

        let handle: thread::JoinHandle<i32> = thread::spawn(move || {
            // Thread code here
            let mut result: *const ClassWrapper<i32> = objClone.as_ref();
            for _i in 0..10000 {
                let obj2 = Object::from_ref(objClone.as_ref());
                result = obj2.as_ref() as *const ClassWrapper<i32>;
            }
            result as i32
        });
        let mut result: *const ClassWrapper<i32> = obj.as_ref();
        for _i in 0..10000 {
            let obj2 = Object::from_ref(obj.as_ref());
            result = obj2.as_ref() as *const ClassWrapper<i32>;
        }

        // Wait for thread to finish
        assert_eq!(handle.join().unwrap(), result as i32);
        assert_eq!(result as i32, obj.as_ref() as *const ClassWrapper<i32> as i32);
    }
```

### Command to run and resulting output

```code
> cargo test --features sync test_object_share_async


thread 'tests::tests::test_object_share_async' panicked at src\lib.rs:3311:9:
assertion `left == right` failed
  left: 3
 right: 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### What happened?

Running this test in the runtime triggers the panic that reference counting is not increasing by + 1 but sometimes by +2 or by 0 because of concurrent copies.
With time, we showed that this assert is never hit so the code is safe to compile as-is without check. This means that, at least in the concurrent version, we can remove the assertion which cannot be checked properly anyway.

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #6247

### What was changed?
- Removed a check that the reference count was increased by 1 when the dafny runtime is used concurrently. This check was performed only to verify the compiler soundness, in that it would actually increase the resource count and not ignore the sentence in the run-time.

### How has this been tested?
- A test performed only in concurrent mode makes a lot of copies of an object. That test fails if the line that checks reference count is activated, and no segfault happens if the line that checks reference count is omitted.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs [hunk 1]
```diff
@@ -3304,10 +3304,11 @@ impl<T: ?Sized> Object<T> {
         // SAFETY: Not guaranteed unfortunately. But looking at the sources of from_raw as of today 10/24/2024
         // it will will correctly rebuilt the Rc
         let rebuilt = ::std::hint::black_box(unsafe { Rc::from_raw(pt) });
-        let previous_strong_count = ::std::hint::black_box(Rc::strong_count(&rebuilt));
+        let _previous_strong_count = ::std::hint::black_box(Rc::strong_count(&rebuilt));
         ::std::hint::black_box(increment_strong_count(pt));
-        let new_strong_count = ::std::hint::black_box(Rc::strong_count(&rebuilt));
-        assert_eq!(new_strong_count, previous_strong_count + 1); // Will panic if not
+        let _new_strong_count = ::std::hint::black_box(Rc::strong_count(&rebuilt));
+        //#[cfg(not(feature = "sync"))]
```
Comment (robin-aws) [inline Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs:3310]: Why commented out?
