### PR TITLE
#356: Implemented all combinations of 'as' conversions among { int, char, bv, real, ordinal}

### LINKED ISSUE #356: bv-to-char conversion results in malformed Boogie
A conversion from a bitvector type (like `bv32`) to `char` produces malformed Boogie, as illustrated by the following repro:

```
method Test(b: bv32, n: nat)
  requires b < 0x1_0000
  requires n < 0x1_0000
{
  var ch: char;
  ch := n as char;  // translates into char#FromInt(n), which is good
  ch := b as char;  // translates into nat_from_bv32(b), which crashes; should be char#FromInt(nat_from_bv32(b))
  assert true;
}
```

### PR DESCRIPTION
**Pull request by davidcok**
Fixes #356. Implemented all combinations of 'as' conversions among { int, char, bv, real, ordinal} in verification and all four compilers, with corresponding verification and run-time tests.

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -4079,6 +4079,9 @@ public class XConstraint
           case "NumericOrBitvector":
             satisfied = t.IsNumericBased() || t.IsBitVectorType;
             break;
+          case "NumericOrBitvectorOrChar":
+            satisfied = t.IsNumericBased() || t.IsBitVectorType || t.IsCharType;
+            break;
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:4084]: Is the new name `"NumericOrBitvectorOrChar"` ever used?

Is the old `"NumericOrBitvector"` name still used?

File: Test/git-issues/git-issue-356-errors.dfy [hunk 2]
```diff
@@ -0,0 +1,226 @@
+// RUN: %dafny /compile:0 "%s" > "%t"
+// RUN: %diff "%s.expect" "%t"
+
+
+// Check every possible conversion range error among int,char,bv,real,ORDINAL
+
+// int to char
+method Test1(n: int)
+{
+  var ch := n as char;
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356-errors.dfy:10]: When looking at just the `.dfy` test file, it's not clear where errors are produced or expected. I suggest following the convention of putting a comment that begins with the word "error" (typically `// error: ...`) in the `.dfy` file. This makes it easier to read. It also makes it easier to maintain when something changes.

File: Test/git-issues/git-issue-356-errors.dfy [hunk 3]
```diff
@@ -0,0 +1,226 @@
...
+method Test1OK(n: int)
+  requires 0 <= n < 65536
+{
+  var ch := n as char;
+}
+
+
+// int to ORDINAL
+method Test2(n: int) {
+  var o: ORDINAL := n as ORDINAL; // must be non-negative // NO ERROR
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356-errors.dfy:34]: I'm thinking this must be a stale comment. It says "NO ERROR", but the .expect file below shows that it does produce an error (as it should).

File: Test/git-issues/git-issue-356-errors.dfy [hunk 4]
```diff
@@ -0,0 +1,226 @@
...
+}
+
+method Test5c(r:real)
+  requires 0.0 <= r <= 65535.0
+{
+  var ch := r as char;
+}
+
+method Test5OK(r: real)
+  requires 0.0 < r <= 65535.0
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356-errors.dfy:97]: It would also be okay to include `0.0`

File: Test/git-issues/git-issue-356-errors.dfy [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+// real to char
+method Test5(r:real)
+  requires 0.0 <= r
+  requires r == r.Floor as real
+{
+  var ch := r as char;
+}
+
+method Test5b(r:real)
+  requires r <= 65535.0
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356-errors.dfy:84]: One could also write `r < 65536.0`

File: Test/git-issues/git-issue-356-errors.dfy [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+  var ch := b as char;
+}
+method TestCOKc(b: bv8)
+{
+  var ch := b as char;
+}
+
+
+// check everything to/from subset int or newtype
+// check everything to/from subset real or newtype
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356-errors.dfy:226]: ?

File: Test/git-issues/git-issue-356-errors.dfy [hunk 7]
```diff
@@ -0,0 +1,226 @@
...
+  var n: int := r as int;
+}
+
+method Test4OK(r: real)
+  requires r.Floor as real == r
+{
+  var n: int := r as int;
+}
+
+// real to char
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356-errors.dfy:75]: If you'd like, you can write these groups of tests more concisely. For example, here are the Test5... tests (plus one that I added to make sure the `case`s are exhaustive).

```
method Test5(r: real) returns (ch: char) {
  if
  case true =>
    ch := r as real;  // error
  case 0.0 <= r == r.Floor as real =>
    ch := r as real;  // error
  case r < 65536.0 && r == r.Floor as real =>
    ch := r as real;  // error
  case 0.0 <= r < 65536.0 =>
    ch := r as real;  // error
  case 0.0 <= r < 65536.0 && r == r.Floor as real =>
    ch := r as real;
}
```

File: Test/git-issues/git-issue-356.dfy [hunk 8]
```diff
@@ -0,0 +1,155 @@
+// RUN: %dafny /compile:0 "%s" > "%t"
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356.dfy:1]: Aha, nice! We should do this in more compiler tests.

File: Test/git-issues/git-issue-356.dfy [hunk 9]
```diff
@@ -0,0 +1,155 @@
...
+  
+    var oo: ORDINAL;
+    oo := c as ORDINAL;
+    oo := n as ORDINAL;
+    oo := r as ORDINAL;
+    oo := b as ORDINAL;
+    oo := o as ORDINAL;
+    
+    assert true;
+
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356.dfy:64]: omit?

File: Test/git-issues/git-issue-356.dfy [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+    oo := b as ORDINAL;
+    oo := o as ORDINAL;
+    
+    assert true;
+  
+  }
+
+  method Test2(b: bv, n: int, c: char, r: real, o: ORDINAL) {
+  
+      assert c == c as char;
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356.dfy:69]: Use indentation level of 2 spaces

File: Test/git-issues/git-issue-356.dfy.expect [hunk 11]
```diff
@@ -0,0 +1,14 @@
+
+Dafny program verifier finished with 5 verified, 0 errors
+
+Dafny program verifier finished with 0 verified, 0 errors
+END
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-356.dfy.expect:5]: Add some `print` statements to (some of) the tests, so we can see that the conversions do something.

File: Source/Dafny/Translator.cs [hunk 12]
```diff
@@ -8064,76 +8064,154 @@ private class WFOptions
...
+    //         var toBound = Basetypes.BigNum.FromBigInt(BigInteger.One << toWidth);  // 1 << toWidth
+    //         if (e.asBigNum <= toBound) {
+    //           return BplBvLiteralExpr(r.tok, e.asBigNum, toType.AsBitVectorType);
+    //         }
+    //       }
+    //     }
+    //     return FunctionCall(tok, "nat_to_bv" + toWidth, BplBvType(toWidth), r);
+    //   }
+    // }
+
```
Comment (RustanLeino) [inline Source/Dafny/Translator.cs:8202]: Delete this code

File: Source/Dafny/Translator.cs [hunk 13]
```diff
@@ -8206,17 +8294,62 @@ private class WFOptions
...
+              string.Format("{0}a negative integer cannot be converted to an {1}", errorMsgPrefix, toType)));
+          }
+
+          if (expr.Type.IsNumericBased(Type.NumericPersuation.Real)) {
+            PutSourceIntoLocal();
+            var oi = FunctionCall(tok, BuiltinFunction.RealToInt, null, o);
+            Bpl.Expr boundsCheck = Bpl.Expr.Le(Bpl.Expr.Literal(0), oi);
+            builder.Add(Assert(tok, boundsCheck,
+              string.Format("{0}a negative real cannot be converted to an {1}", errorMsgPrefix, toType)));
+          }
```
Comment (RustanLeino) [inline Source/Dafny/Translator.cs:8345]: Unindent

File: Source/Dafny/Translator.cs [hunk 14]
```diff
@@ -8206,17 +8294,62 @@ private class WFOptions
...
+          
+      } else if (toType.IsNumericBased(Type.NumericPersuation.Int)) {
+        // already checked that BigOrdinal or real inputs are integral
+        // FIXME - are there subset range checks to make?}
+      } else if (toType.IsNumericBased(Type.NumericPersuation.Real)) {
+        // already checked that BigOrdinal is integral
+        // FIXME - are there subset range checks to make?
```
Comment (RustanLeino) [inline Source/Dafny/Translator.cs:8352]: What is the status of these?

File: Test/git-issues/git-issue-356.dfy (hunk 8 above)
Comment (robin-aws) [reply Test/git-issues/git-issue-356.dfy:1]: +1 - this could save a lot of execution time in the tests. In my WIP refactoring to address #632 I've made the default behaviour to execute in every target language, and I can make the equivalent change to do verification separately like this.

**Comment by davidcok** [comment]
In this case I used /compile:0 to separate verification from runtime execution.
The problem, was this verification takes ~20 sec and it was a pain to repeat that verification for each of the target languages. Hence the more important part, in this case was using /noVerify /compile:4 ion the target language compilation/execution tests.

- David

File: Source/Dafny/Resolver.cs (hunk 1 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:4084]: Removed the case NumericOrBitvectorOrChar; NumericOrBitvector is still used.

File: Test/git-issues/git-issue-356-errors.dfy (hunk 2 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356-errors.dfy:10]: Marked the lines producing errors with "// ERROR". Methods that did not produce errors already have "OK" in their name.

File: Test/git-issues/git-issue-356-errors.dfy (hunk 4 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356-errors.dfy:97]: Done

File: Test/git-issues/git-issue-356-errors.dfy (hunk 5 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356-errors.dfy:84]: Done

File: Test/git-issues/git-issue-356-errors.dfy (hunk 7 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356-errors.dfy:75]: Next time. Also I prefer one error per method, just in case the order is non-deterministic or one hides the other.

File: Test/git-issues/git-issue-356.dfy (hunk 10 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356.dfy:69]: Done

File: Test/git-issues/git-issue-356.dfy.expect (hunk 11 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356.dfy.expect:5]: Done

File: Source/Dafny/Translator.cs (hunk 12 above)
Comment (davidcok) [reply Source/Dafny/Translator.cs:8202]: Done

File: Source/Dafny/Translator.cs (hunk 14 above)
Comment (davidcok) [reply Source/Dafny/Translator.cs:8352]: Added tests for subset type. Removed comments.

File: Source/Dafny/Translator.cs (hunk 13 above)
Comment (davidcok) [reply Source/Dafny/Translator.cs:8345]: Done

File: Test/git-issues/git-issue-356.dfy (hunk 9 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356.dfy:64]: Removed

**Comment by davidcok** [comment]
Added test for conversions of subset types. Identified and fixed bug in conversions of real-based subset types.

File: Test/git-issues/git-issue-356-errors.dfy (hunk 6 above)
Comment (davidcok) [reply Test/git-issues/git-issue-356-errors.dfy]: Removed
