### PR TITLE
#258: Fixes the printing of strings through Dafny print statements

### LINKED ISSUE #258: print in JS sometimes prints array of char instead of string
```
method Main() {
    var a := new char[2];
    a[0] := 'h';
    a[1] := 'i';
    print a[..];
}
```

When I compile this to C# and run it, it outputs `hi`, as expected.
However, when I compile it to JS and run it with `node`, it outputs `[h, i]`.
The behavior should be the same, no matter which language I export to.

(considered low priority, just posting here for reference)

### PR DESCRIPTION
**Pull request by davidcok**
Fixes #258. One remaining infelicity: when Dafny sequences are passed through a generic interface as in method pr<T>(s: seq<T>), then JS and GO cannot tell the element type of an empty string, so empty sequences passed through such an interface will print as [] instead of just nothing, as C# and Java will do.

### CODE REVIEW

File: Source/Dafny/Compiler-go.cs [hunk 1]
```diff
@@ -1831,9 +1831,27 @@ private class SpecialNativeType : UserDefinedType {
     }
 
     protected override void EmitPrintStmt(TargetWriter wr, Expression arg) {
-      wr.Write("_dafny.Print(");
-      TrExpr(arg, wr, false);
-      wr.WriteLine(")");
+      bool isString = arg.Type.AsCollectionType != null &&
+                      arg.Type.AsCollectionType.AsSeqType != null &&
+                      arg.Type.AsCollectionType.AsSeqType.Arg.IsCharType;
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-go.cs:1836]: `arg.Type.AsCollectionType.AsSeqType` gives the same result as just `arg.Type.AsSeqType`.

Same comment applies several places below.

File: Source/Dafny/Compiler-go.cs [hunk 2]
```diff
@@ -1831,9 +1831,27 @@ private class SpecialNativeType : UserDefinedType {
...
+      if (isString) {
+        // needed for empty sequences known to be strings
+        if (arg.Resolved is MemberSelectExpr &&
+            (arg.Resolved as MemberSelectExpr).Member.IsExtern(out _, out _)) {
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-go.cs:1840]: As a general rule, I prefer `((MemberSelectExpr)arg.Resolved)` over `arg.Resolved as MemberSelectExpr` when you expect the cast to succeed. It's a way in the source to indicate your understanding that the cast will succeed.

In this case, you can simplify the guard further as:

    arg.Resolved is MemberSelectExpr mse && mse.Member.IsExtern(out _, out _)

File: Source/Dafny/Compiler-go.cs [hunk 3]
```diff
@@ -1831,9 +1831,27 @@ private class SpecialNativeType : UserDefinedType {
...
+          wr.Write("_dafny.Print((");
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-go.cs:1841]: There's a superfluous pair of parentheses on L1841 and L1843.
Also, this case is the same as L1851-1853, so maybe the nested `if` can be rewritten with 2 cases instead of 3.

File: Source/Dafny/Compiler-js.cs [hunk 4]
```diff
@@ -1042,9 +1042,51 @@ protected class ClassWriter : IClassWriter {
...
-      TrExpr(arg, wr, false);
-      wr.WriteLine("));");
+      bool isString = arg.Type.AsCollectionType != null &&
+                      arg.Type.AsCollectionType.AsSeqType != null &&
+                      arg.Type.AsCollectionType.AsSeqType.Arg.IsCharType;
+      bool isStringLiteral = arg is StringLiteralExpr;
+      bool isGeneric = arg.Type.AsCollectionType != null &&
+                       arg.Type.AsCollectionType.AsSeqType != null &&
+                       arg.Type.AsCollectionType.AsSeqType.Arg.IsTypeParameter;
+      if (isString && isStringLiteral) {
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-js.cs:1052]: `isStringLiteral` implies `isString`, right?

File: Source/Dafny/Compiler-js.cs [hunk 5]
```diff
@@ -1042,9 +1042,51 @@ protected class ClassWriter : IClassWriter {
...
+        // process.stdout.write(_dafny.toString(x));
+        wr.Write("process.stdout.write(_dafny.toString(");
+        TrExpr(arg, wr, false);
+        wr.WriteLine("));");
+      } else if (isString && !isStringLiteral) {
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-js.cs:1057]: If the guard at L1052 is changed to just `isStringLiteral`, this the guard here can be just `isString`

File: Source/Dafny/Compiler-js.cs [hunk 6]
```diff
@@ -1042,9 +1042,51 @@ protected class ClassWriter : IClassWriter {
...
+        // try { process.stdout.write(_dafny.toString((x).join(""))); } catch (_error) { process.stdout.write(_dafny.toString(x)); }
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-js.cs:1058]: The `try`-`catch` encloses the `write`, `toString`, and `join`, but I think it's intended just for the `join`. I suggest adding a function to the JavaScript runtime that takes `x` as a parameter and returns `x.join("")` if possible and `x` otherwise. Then, the line emitted here would be just

    process.stdout.write(_dafny.toString(NEWFUNCTION(x)))

This also leaves me wondering, if `x` is a string, why would `x.join("")` fail in the first place?

For that matter, why just have a new routine `_dafny.seqAsString` that does the equivalent of `_dafny.toString(x.join(""))`, and possibly without needing to do the `.join("")` in the first place?

File: Source/Dafny/Compiler-js.cs [hunk 7]
```diff
@@ -1042,9 +1042,51 @@ protected class ClassWriter : IClassWriter {
...
+        wr.Write("try { process.stdout.write(_dafny.toString((");
+        TrExpr(arg, wr, false);
+        wr.WriteLine(").join(\"\")));");
+        wr.Write(" } catch (_error) { process.stdout.write(_dafny.toString(");
+        TrExpr(arg, wr, false);
+        wr.WriteLine(")); }");
+      } else if (!isString && !isGeneric) {
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-js.cs:1065]: With L1052 and L 1057 simplified, this guard can be just `!isGeneric`

File: Source/Dafny/Compiler-js.cs [hunk 8]
```diff
@@ -1042,9 +1042,51 @@ protected class ClassWriter : IClassWriter {
...
+        // process.stdout.write(_dafny.toString(x));
+        wr.Write("process.stdout.write(_dafny.toString(");
+        TrExpr(arg, wr, false);
+        wr.WriteLine("));");
+      } else { // isGeneric
+        // try { process.stdout.write(_dafny.toString(((x) instanceof Array && typeof((x)[0]) == \"string\") ? (x).join("") : (x))); } catch (_error) { process.stdout.write(_dafny.toString(x)); }
```
Comment (RustanLeino) [inline Source/Dafny/Compiler-js.cs:1071]: Simplifying my suggestion for L1058 further and combining it with this line, why not just do all of this inside `_dafny.toString`?

File: Test/comp/Collections.dfy [hunk 9]
```diff
@@ -116,7 +116,7 @@ module BoundedIntegerParameters {
   {
     var data := "Bounded";
 
-    print data[..u0], " ";  // it is unfortunate how these get printed in Java
+    print data[..u0], " ";
```
Comment (RustanLeino) [inline Test/comp/Collections.dfy:119]: Good catch!

File: Test/git-issues/git-issue-258.dfy [hunk 10]
```diff
@@ -0,0 +1,51 @@
...
+
+method pr<T>(s: seq<T>) {
+  print s, "\n";
+}
+
+method Main() {
+  var a := new char[2];
+  a[0] := 'h';
+  a[1] := 'i';
+  print a[..], "\n";   // hi
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-258.dfy:16]: Good comments throughout this file

File: Source/Dafny/Compiler-go.cs (hunk 1 above)
Comment (davidcok) [reply Source/Dafny/Compiler-go.cs:1836]: Done

File: Source/Dafny/Compiler-go.cs (hunk 2 above)
Comment (davidcok) [reply Source/Dafny/Compiler-go.cs:1840]: OK

File: Source/Dafny/Compiler-js.cs (hunk 5 above)
Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1057]: True, but less clear, IMHO

File: Source/Dafny/Compiler-go.cs (hunk 3 above)
Comment (davidcok) [reply Source/Dafny/Compiler-go.cs:1841]: Done - though the complexity of the if condition does not lend itself to understanding.

File: Source/Dafny/Compiler-js.cs (hunk 4 above)
Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1052]: One hopes so, but it is not obvious locally. Simplified the condition none-the-less.

File: Source/Dafny/Compiler-js.cs (hunk 6 above)
Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1058]: join() can fail because, in at least the case of the argument being something like "a"+"b",
the Dafny type of the argument is a seq<char>, but the translated JS evaluates to a literal string, instead of to a sequence.  So the try-catch is a catch-all, rather than trying to predict the exact behavior of arbitrary arguments.

Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1058]: I suppose one could argue that Seq.Concat in DafnyRuntime.js should not return a+b, but rather a Sequence equivalent, but that would have left me to find all other such situations.

Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1058]: Created the suggested helper function

File: Source/Dafny/Compiler-js.cs (hunk 7 above)
Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1065]: Reordered the cases so that the guards are simplified without losing clarity

File: Source/Dafny/Compiler-js.cs (hunk 8 above)
Comment (davidcok) [reply Source/Dafny/Compiler-js.cs:1071]: Because we need information from dafny types to distinguish various cases. For example, from dafny we know when we have an empty seq<char>, but within JS we cannot distinguish that from other empty sequences.  It is all a bit messy. Plus only within dafny do we know that the sequence has homogeneous elements -- not at all guaranteed in JS.
