### PR TITLE
Fix: #4315, allowing static reveal lemmas to reference non-static original procedures

### LINKED ISSUE #4315: Refining a module with a class containing opaque functions causes resolution error
### Dafny version

4.2.0

### Code to produce this issue

```dafny
module M1 {
  class C {
    opaque function f() : bool { true }
  }
}

module M2 refines M1 {
}
```

### Command to run and resulting output

```code
$ ./Binaries/Dafny verify ~/test/scratch.dfy
    |
173 | <nonexistent line>
    |                     ^

/Users/ekanshdg/test/scratch.dfy[M2](173,20): Error: 'this' is not allowed in a 'static' context
1 resolution/type errors detected in scratch.dfy
```

### What happened?

Due to the change making reveal lemmas static, there is a resolution error when the static reveal lemma tries to set the fuel for its non-static originating function. This only gets triggered when a module is resolved again, like when it is being refined, because the reveal lemma is added after the resolution is complete.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by EkanshdeepGupta**
This PR fixes #4315
I added the corresponding test.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs [hunk 1]
```diff
@@ -316,7 +316,49 @@ public partial class ModuleResolver {
...
             Contract.Assert(arg != null);
-            ResolveExpression(arg, resolutionContext);
+            if (!(Attributes.Contains(attributeHost.Attributes, "opaque_reveal") && attr.Name == "fuel" && arg is NameSegment)) {
+              ResolveExpression(arg, resolutionContext);
+            } else {
+              // Manually resolving NameSegments that are present in fuel attributes of reveal lemmas.
+              // This is because reveal lemmas are static and we want to allow a refence to non-static original procedures
+              // in static context in this setting.
+              //
+              // Most of the following code is copied from AnnotateRevealFunction() in OpaqueMemberRewriter.cs.
```
Comment (MikaelMayer) [inline Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs:326]: Can you please put this branch in a separate function, so that you can put it as the function's comment?

File: Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs [hunk 2]
```diff
@@ -326,6 +330,49 @@ public partial class ModuleResolver {
       }
     }
 
+    // <summary>
+    // Manually resolving NameSegments that are present in fuel attributes of reveal lemmas.
+    // This is because reveal lemmas are static and we want to allow a refence to non-static original procedures
```
Comment (MikaelMayer) [inline Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs:335]:
```suggestion
    // This is because reveal lemmas are static and we want to allow a reference to non-static original procedures
```

File: Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs [hunk 3]
```diff
@@ -326,6 +330,49 @@ public partial class ModuleResolver {
...
+    // in static context in this setting.
+    //
+    // Most of the following code is copied from AnnotateRevealFunction() in OpaqueMemberRewriter.cs.
```
Comment (MikaelMayer) [inline Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs:338]: Would you be able to refactor the common part out if the code is similar, so that we avoid code duplication? I haven't looked at the other side of the code.

File: docs/dev/news/4315.fix [hunk 4]
```diff
@@ -0,0 +1 @@
+Fixed #4315, allowing static reveal lemmas to reference non-static original procedures
```
Comment (MikaelMayer) [inline docs/dev/news/4315.fix:1]:
```suggestion
Refining an abstract module with a class with an opaque function no longer crashes
```
Here it should be user-oriented.

**Review by MikaelMayer — CHANGES_REQUESTED** [review]
A few requests, otherwise the fix looks good!

File: Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs (hunk 3 above)
Comment (EkanshdeepGupta) [reply Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs:338]: I looked but cannot think of a clean way to refactor the common code. Also it is not so big to warrant refactoring I think.

**Review by MikaelMayer — APPROVED** [review]
