### PR TITLE
Fix formatting regression

### LINKED ISSUE #3563: Between 3.11.0 and now indentation regressed
### Dafny version

3.11.0+dev

### Code to produce this issue

```dafny
const c :=
           1111111111111111111111111111111111111111
```

### Command to run and resulting output

```code
dafny format --print
```

### What happened?

This used to format as
```dafny
const c :=
  1111111111111111111111111111111111111111
```
but now is
```dafny
const c :=
1111111111111111111111111111111111111111
```
which seems like a regression to me.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes a formatting regression by actually implementing a missing formatting support for DatatypeValue.

Fixes #3563
<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/AST/MemberDecls.cs [hunk 1]
```diff
@@ -128,7 +128,7 @@ public Field(RangeToken rangeToken, Name name, bool hasStaticKeyword, bool isGho
 
   public bool SetIndent(int indentBefore, TokenNewIndentCollector formatter) {
     formatter.SetOpeningIndentedRegion(StartToken, indentBefore);
-    formatter.SetClosingIndentedRegion(EndToken, indentBefore);
+    formatter.SetIndentations(EndToken, below: indentBefore);
```
Comment (MikaelMayer) [inline Source/DafnyCore/AST/MemberDecls.cs:131]: Before, it would set the indent of the last token to (above:Indent + 2, inline:Indent, below:Indent), which works for sets and sequences, but not for constants.
Now I only set the indentation below that last token, which is the only thing really needed.

File: Source/DafnyCore/AST/Expressions/Expressions.cs [hunk 2]
```diff
@@ -986,6 +986,10 @@ public DatatypeValue(IToken tok, string datatypeName, string memberName, List<Ex
   }
 
   public IToken NameToken => tok;
+  public bool SetIndent(int indentBefore, TokenNewIndentCollector formatter) {
+    formatter.SetMethodLikeIndent(StartToken, OwnedTokens, indentBefore);
```
Comment (MikaelMayer) [inline Source/DafnyCore/AST/Expressions/Expressions.cs:990]: This method is the "default" formatting heuristic, which can take into account type parameters, named arguments, etc.

**Review by keyboardDrummer — APPROVED** [review]
