### PR TITLE
Use the same C++ warning flags on all platforms

### LINKED ISSUE #2041: Tests fail because C++ compiler has extra flag enabled in MacOS
Dafny commit 0e4b2bbd7f4adcb6fcc23a11e28bdbbcabbf5cee
macOS 12.3.1 (on Apple Silicon, in case that matters)
```
g++ --version
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

This looks like a close repeat of old issue #1306.

Some integration tests fail because the C++ compiler emits warnings that throw off the test result diff. The warning is emitted by `-Wunused-but-set-variable`, which in [Compilers/Compiler-cpp.cs:2429](https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/Compilers/Compiler-cpp.cs#L2429) is disabled for Windows and Linux but remains enabled for MacOS. 

Failed test output:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:01:03.20]     c++/const.dfy [FAIL]
  Failed c++/const.dfy [4 s]
  Error Message:
   System.Exception : Command returned non-zero exit code (1): DiffCommand TestFiles/LitTests/LitTest/c++/const.dfy.expect /Users/mija/repos/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/c++/Output/const.dfy.tmp
Output:
Xunit.Sdk.AssertActualExpectedException: AssertEqualWithDiff() Failure
Diff (changing expected into actual):

 Dafny program verifier finished with 1 verified, 0 errors
+TestFiles/LitTests/LitTest/c++/const.cpp:16:10: warning: variable '_0_b' set but not used [-Wunused-but-set-variable]
+    bool _0_b;
+         ^
+1 warning generated.


Expected:
Dafny program verifier finished with 1 verified, 0 errors

Actual:
Dafny program verifier finished with 1 verified, 0 errors
TestFiles/LitTests/LitTest/c++/const.cpp:16:10: warning: variable '_0_b' set but not used [-Wunused-but-set-variable]
    bool _0_b;
         ^
1 warning generated.

   at XUnitExtensions.AssertWithDiff.Equal(String expected, String actual) in /Users/mija/repos/dafny/dafny/Source/XUnitExtensions/AssertWithDiff.cs:line 28
   at XUnitExtensions.Lit.DiffCommand.Execute(ITestOutputHelper outputHelper, TextReader inputReader, TextWriter outputWriter, TextWriter errorWriter) in /Users/mija/repos/dafny/dafny/Source/XUnitExtensions/Lit/DiffCommand.cs:line 35
Error:

  Stack Trace:
     at XUnitExtensions.Lit.LitTestCase.Execute(ITestOutputHelper outputHelper) in /Users/mija/repos/dafny/dafny/Source/XUnitExtensions/Lit/LitTestCase.cs:line 94
   at XUnitExtensions.Lit.LitTestCase.Run(String filePath, LitTestConfiguration config, ITestOutputHelper outputHelper) in /Users/mija/repos/dafny/dafny/Source/XUnitExtensions/Lit/LitTestCase.cs:line 55
   at IntegrationTests.LitTests.LitTest(String path) in /Users/mija/repos/dafny/dafny/Source/IntegrationTests/LitTests.cs:line 157
  Standard Output Messages:
 Executing command: dotnet /Users/mija/repos/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/Dafny.dll /countVerificationErrors:0 /vcsCores:2 /useBaseNameForFileName /compileVerbose:0 /errorTrace:0 /timeLimit:300 /compile:3 /spillTargetCode:2 /compileTarget:cpp TestFiles/LitTests/LitTest/c++/const.dfy > /Users/mija/repos/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/c++/Output/const.dfy.tmp
 Executing command: DiffCommand TestFiles/LitTests/LitTest/c++/const.dfy.expect /Users/mija/repos/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/c++/Output/const.dfy.tmp
 Previous command results:
 Output:

 Dafny program verifier finished with 1 verified, 0 errors
 TestFiles/LitTests/LitTest/c++/const.cpp:16:10: warning: variable '_0_b' set but not used [-Wunused-but-set-variable]
     bool _0_b;
          ^
 1 warning generated.

 Error:


```

### PR DESCRIPTION
**Pull request by atomb**
Fixes #2041.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/Dafny/Compilers/Compiler-cpp.cs [hunk 1]
```diff
@@ -2424,12 +2424,7 @@ protected class ClassWriter : IClassWriter {
...
-      var warnings = "-Wall -Wextra -Wpedantic -Wno-unused-variable -Wno-deprecated-copy -Wno-unused-label";
-      if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux) || RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
-        warnings += " -Wno-unused-but-set-variable";
-      } else {
-        warnings += " -Wno-unknown-warning-option";
-      }
+      var warnings = "-Wall -Wextra -Wpedantic -Wno-unused-variable -Wno-deprecated-copy -Wno-unused-label -Wno-unused-but-set-variable -Wno-unknown-warning-option";
       var args = warnings + $" -g -std=c++17 -I {codebase} -o {ComputeExeName(targetFilename)} {targetFilename}";
       compilationResult = null;
       var psi = new ProcessStartInfo("g++", args) {
```
Comment (cpitclaudel) [inline Source/Dafny/Compilers/Compiler-cpp.cs:2430]: Can we take this opportunity to convert `args` to a list, instead of a string?

**Review by cpitclaudel — CHANGES_REQUESTED** [review]

**Comment by fabiomadge** [comment]
I seem to remember that there was a reason for this complex contraption at the time, but it’s great if we can get rid of it.

File: Source/Dafny/Compilers/Compiler-cpp.cs (hunk 1 above)
Comment (atomb) [reply Source/Dafny/Compilers/Compiler-cpp.cs:2430]: Yeah, I think that's a good idea.

File: Source/Dafny/Compilers/Compiler-cpp.cs [hunk 2]
```diff
@@ -2424,15 +2424,22 @@ protected class ClassWriter : IClassWriter {
...
+                       "-Wno-unused-variable",
+                       "-Wno-deprecated-copy",
+                       "-Wno-unused-label",
+                       "-Wno-unused-but-set-variable",
+                       "-Wno-unknown-warning-option",
+                        "-g",
+                        "-std=c++17",
+                        "-I", $"{codebase}",
+                        "-o", $"{ComputeExeName(targetFilename)}",
+                        $"{targetFilename}" };
```
Comment (fabiomadge) [inline Source/Dafny/Compilers/Compiler-cpp.cs:2440]:
```suggestion
                        targetFilename };
```

File: Source/Dafny/Compilers/Compiler-cpp.cs [hunk 3]
```diff
@@ -2424,15 +2424,22 @@ protected class ClassWriter : IClassWriter {
...
+                       "-Wextra",
+                       "-Wpedantic",
+                       "-Wno-unused-variable",
+                       "-Wno-deprecated-copy",
+                       "-Wno-unused-label",
+                       "-Wno-unused-but-set-variable",
+                       "-Wno-unknown-warning-option",
+                        "-g",
+                        "-std=c++17",
+                        "-I", $"{codebase}",
```
Comment (fabiomadge) [inline Source/Dafny/Compilers/Compiler-cpp.cs:2438]:
```suggestion
                        "-I", codebase,
```

File: Source/Dafny/Compilers/Compiler-cpp.cs [hunk 4]
```diff
@@ -2424,15 +2424,22 @@ protected class ClassWriter : IClassWriter {
...
+                       "-Wpedantic",
+                       "-Wno-unused-variable",
+                       "-Wno-deprecated-copy",
+                       "-Wno-unused-label",
+                       "-Wno-unused-but-set-variable",
+                       "-Wno-unknown-warning-option",
+                        "-g",
+                        "-std=c++17",
+                        "-I", codebase,
+                        "-o", $"{ComputeExeName(targetFilename)}",
```
Comment (fabiomadge) [inline Source/Dafny/Compilers/Compiler-cpp.cs:2439]:
```suggestion
                        "-o", ComputeExeName(targetFilename),
```
Sorry!

Comment (atomb) [reply Source/Dafny/Compilers/Compiler-cpp.cs]: I really should have caught that one myself. ;)

File: Source/Dafny/Compilers/Compiler-cpp.cs [hunk 5]
```diff
@@ -2424,15 +2424,22 @@ protected class ClassWriter : IClassWriter {
...
+                       "-Wno-unused-but-set-variable",
+                       "-Wno-unknown-warning-option",
+                        "-g",
+                        "-std=c++17",
+                        "-I", codebase,
+                        "-o", ComputeExeName(targetFilename),
+                        targetFilename };
       compilationResult = null;
-      var psi = new ProcessStartInfo("g++", args) {
+      var psi = new ProcessStartInfo("g++", string.Join(" ", args)) {
```
Comment (cpitclaudel) [inline Source/Dafny/Compilers/Compiler-cpp.cs:2442]: You need to use [ArgumentList](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=net-6.0#system-diagnostics-processstartinfo-argumentlist), otherwise you have the same problem as before with strings (broken escaping / injection)

**Review by cpitclaudel — CHANGES_REQUESTED** [review]

File: Source/Dafny/Compilers/Compiler-cpp.cs (hunk 5 above)
Comment (atomb) [reply Source/Dafny/Compilers/Compiler-cpp.cs:2442]: Ah! That's much nicer.

**Review by cpitclaudel — APPROVED** [review]
