### PR TITLE
Fix: out of range exception in language server

### LINKED ISSUE #2702: textDocument/codeAction can cause an exception
In the following program, clicking on `false` creates an exception in the LSP server

```dafny

module Conc refines StillAsby {
  import A = B
}

abstract module StillAsby {
  import A : Absy
}

module B refines Absy {

}

abstract module Absy {
  method Foo() 
    ensures false {
    var x := 1;
  }
}
```

```
[Trace - 12:20:07 PM] Received response 'textDocument/codeAction - (150)' in 15ms. Request failed: Internal Error - System.Collections.Generic.KeyNotFoundException: The given key '15' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionInput.Extract(Range range)
   at Microsoft.Dafny.LanguageServer.Language.VerificationDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Diagnostic diagnostic, Range selection)
   at Microsoft.Dafny.LanguageServer.Plugins.DiagnosticDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Range selection)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.<>c__DisplayClass5_0.<GetFixesWithIds>b__0(DafnyCodeActionProvider fixer)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() (-32603).
[Error - 12:20:07 PM] Request textDocument/codeAction failed.
  Message: Internal Error - System.Collections.Generic.KeyNotFoundException: The given key '15' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionInput.Extract(Range range)
   at Microsoft.Dafny.LanguageServer.Language.VerificationDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Diagnostic diagnostic, Range selection)
   at Microsoft.Dafny.LanguageServer.Plugins.DiagnosticDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Range selection)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.<>c__DisplayClass5_0.<GetFixesWithIds>b__0(DafnyCodeActionProvider fixer)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #2702 

I did not add a test for two reasons
1) I cannot reproduce this bug on my machine as stated in the thread.
2) I will be adding a test in my PR for the formatter that makes use of this code, so we'll have it covered anyway down the road.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs [hunk 1]
```diff
@@ -193,8 +193,13 @@ public class DafnyCodeActionInput : IDafnyCodeActionInput {
   }
 
   public string Extract(Range range) {
+    if (!CodeLineToPos.ContainsKey(range.Start.Line)) {
```
Comment (keyboardDrummer) [inline Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs:196]: Not related to this PR, but why did we add `CodeLineToPos` to `CodeActionHandler` instead of to `DocumentTextBuffer` ? It seems like quite a piece of functionality that many pieces of the IDE are interested in.

File: Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs [hunk 2]
```diff
@@ -193,8 +193,13 @@ public class DafnyCodeActionInput : IDafnyCodeActionInput {
...
+      return ""; // Out of range
+    }
     var startTokenPos = CodeLineToPos[range.Start.Line] + range.Start.Character;
-    var endTokenPos = CodeLineToPos[range.End.Line] + range.End.Character;
+    var endTokenPos =
+      !CodeLineToPos.ContainsKey(range.Start.Line) ? Code.Length - startTokenPos :
```
Comment (keyboardDrummer) [inline Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs:201]: How can `CodeLineToPos.ContainsKey(range.Start.Line) ` ever be false here if you already return on line 197 when it's false?

Comment (MikaelMayer) [inline Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs:201]:
```suggestion
      !CodeLineToPos.ContainsKey(range.End.Line) ? CodeLineToPos[range.End.Line] + range.End.Character :
```

File: Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs [hunk 3]
```diff
@@ -193,8 +193,13 @@ public class DafnyCodeActionInput : IDafnyCodeActionInput {
...
+        CodeLineToPos[range.End.Line] + range.End.Character;
```
Comment (MikaelMayer) [inline Source/DafnyLanguageServer/Handlers/DafnyCodeActionHandler.cs:202]:
```suggestion
        Code.Length - startTokenPos;
```

**Review by keyboardDrummer — APPROVED** [review]
