### PR TITLE
#151, #328: Fixes to ambiguity of imported types

### LINKED ISSUE #151: Type definitions from current module should unambiguously override those from opened imports
Consider the following program:

```
module A {
    export provides T, Foo

    type T = int
    function method Foo(x: T): T
}

module B {
    import opened A

    type T = A.T

    function method Bar(x: T): T
    {
        A.Foo(x)
    }
}
```

Dafny complains that the references to `T` in the signature of `Bar` are ambiguous. It would be nice if instead they were unambiguously resolved to the local definition of `T`.

### PR DESCRIPTION
**Pull request by davidcok**
Allows use of imported types that are imported through multiple paths if they are the "same" type; also gives locally defined types preference over imports.

Fixes #151, #328.

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -1585,7 +1585,41 @@ public class ModuleBindings
...
+                      kk = (kkk as UserDefinedType).AsRevealableType as TopLevelDecl;
+                      kkk = null;
+                    }
+                  }
+                  if (ddd == null || kkk == null) {
+                    ok = dd == kk;
+                  } else {
+                    ok = ddd.Equals(kkk, true);
+                  }
+                }
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:1618]: I don't feel certain about this logic. It may be right, but I'm not convinced, so I'll at least ask some question here. One of the things that worries me is that it bypasses the mechanism for expanding types through module boundaries, where some things may be visible through imports and other things not.

I think the aim of this code is to repeatedly follow type synonyms to their non-synonym base definitions. That can be done with one call to `.NormalizeExpand(true)`, provided one starts with a `Type`, not a `TopLevelDecl`. So, then, can the code above instead be accomplished by:

```
var dType = UserDefinedType.FromTopLevelDecl(d, d.tok).NormalizeExpand(true);
var vType = UserDefinedType.FromTopLevelDecl(kv.Value, kv.Value.tok).NormalizeExpand(true);
var ok = dType.Equals(vType);
```

Or, for that matter, why not just

```
var dType = UserDefinedType.FromTopLevelDecl(d, d.tok);
var vType = UserDefinedType.FromTopLevelDecl(kv.Value, kv.Value.tok);
var ok = dType.Equals(vType, true);
```

File: Source/Dafny/DafnyAst.cs [hunk 2]
```diff
@@ -2779,23 +2779,23 @@ public UserDefinedType(TypeParameter tp)
...
       if (i is UserDefinedType) {
         var ii = (UserDefinedType)i;
-        var t = that.NormalizeExpand() as UserDefinedType;
+        var t = that.NormalizeExpand(keepConstraints) as UserDefinedType;
         if (t == null || ii.ResolvedParam != t.ResolvedParam || ii.ResolvedClass != t.ResolvedClass || ii.TypeArgs.Count != t.TypeArgs.Count) {
           return false;
         } else {
           for (int j = 0; j < ii.TypeArgs.Count; j++) {
-            if (!ii.TypeArgs[j].Equals(t.TypeArgs[j])) {
+            if (!ii.TypeArgs[j].Equals(t.TypeArgs[j],keepConstraints)) {
```
Comment (RustanLeino) [inline Source/Dafny/DafnyAst.cs:2791]:
```suggestion
            if (!ii.TypeArgs[j].Equals(t.TypeArgs[j], keepConstraints)) {
```

File: Source/Dafny/DafnyAst.cs [hunk 3]
```diff
@@ -2779,23 +2779,23 @@ public UserDefinedType(TypeParameter tp)
...
               return false;
             }
           }
           return true;
         }
       } else {
-        return i.Equals(that);
+        return i.Equals(that,keepConstraints);
```
Comment (RustanLeino) [inline Source/Dafny/DafnyAst.cs:2798]:
```suggestion
        return i.Equals(that, keepConstraints);
```

File: Source/Dafny/DafnyAst.cs [hunk 4]
```diff
@@ -2223,7 +2223,7 @@ public class BigOrdinalType : BasicType
     public override string TypeName(ModuleDefinition context, bool parseAble) {
       return "ORDINAL";
     }
-    public override bool Equals(Type that) {
+    public override bool Equals(Type that, bool keepConstraints = false) {
       return that.IsBigOrdinalType;
```
Comment (RustanLeino) [inline Source/Dafny/DafnyAst.cs:2227]: To handle a type like `type MyOrdinal = x: ORDINAL | x != 8`, I think this needs to be:

    return that.NomalizeExpand(keepConstraints) is BigOrdinalType;

File: Source/Dafny/DafnyAst.cs [hunk 5]
```diff
@@ -2190,8 +2190,8 @@ public class IntType : BasicType
     public override string TypeName(ModuleDefinition context, bool parseAble) {
       return "int";
     }
-    public override bool Equals(Type that) {
-      return that.IsIntegerType;
+    public override bool Equals(Type that, bool keepConstraints = false) {
+      return keepConstraints ? this.GetType() == that.GetType() : that.IsIntegerType;
```
Comment (RustanLeino) [inline Source/Dafny/DafnyAst.cs:2194]: To handle a type like `type MyInt = x: int | x != 8`, I think this needs to be:

    return that.NomalizeExpand(keepConstraints) is IntType;

File: Source/Dafny/DafnyAst.cs [hunk 6]
```diff
@@ -2206,8 +2206,8 @@ public class RealType : BasicType {
     public override string TypeName(ModuleDefinition context, bool parseAble) {
       return "real";
     }
-    public override bool Equals(Type that) {
-      return that.IsRealType;
+    public override bool Equals(Type that, bool keepConstraints = false) {
+      return keepConstraints ? this.GetType() == that.GetType() : that.IsRealType;
```
Comment (RustanLeino) [inline Source/Dafny/DafnyAst.cs:2210]: See L2194 and L2227.

**Review by RustanLeino — CHANGES_REQUESTED** [review]

File: Test/git-issues/git-issue-151.dfy [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+  type T = A.T
+
+  function method Baz(x: T): T { 0 } // OK C.T is local
+  function method Bar(x: U): U { 0 } // Error A.U, B.U conflict
+  function method Bam(x: V): V { 0 } // OK A.V, B.V are the same type
+  function method Baa(x: W): W { 0 } // Error A.W, B.W are different
+  function method Bag(x: X): X { 0 } // Error A.X, B.X are different
+  function method Bay(x: Y): Y { 0 } // OK A.Y, D.Y are the same type
+  function method Bat(x: Z): Z { 0 } // Error: A.Z, B.Z are different newtypes
+  function method Ban(x: K): K { 0 } // OK: A.K, D.K are refer to same decl
```
[the remark this answers is not in the document]
Comment (davidcok) [reply Test/git-issues/git-issue-151.dfy:43]: OK

File: Source/Dafny/DafnyAst.cs (hunk 2 above)
Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2791]: OK

File: Source/Dafny/DafnyAst.cs (hunk 3 above)
Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2798]: OK

Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2798]: OK

File: Source/Dafny/DafnyAst.cs (hunk 4 above)
Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2227]: OK

File: Source/Dafny/DafnyAst.cs (hunk 5 above)
Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2194]: OK

File: Source/Dafny/DafnyAst.cs (hunk 6 above)
Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2210]: OK

File: Test/git-issues/git-issue-151.dfy (hunk 7 above)
[the remark this answers is not in the document]
Comment (davidcok) [reply Test/git-issues/git-issue-151.dfy:43]: OK

File: Source/Dafny/DafnyAst.cs (hunk 2 above)
Comment (davidcok) [reply Source/Dafny/DafnyAst.cs:2791]: OK

File: Source/Dafny/Resolver.cs (hunk 1 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:1618]: Used the last suggestion, with a bit of adjustment to accommodate the current use of .ResolvedParams for OpaqueTypeDecls.
