### PR TITLE
Fix C# codegen for tail-recursive member functions

### LINKED ISSUE #2173: Invalid C# codegen for tail-recursive member functions that recurse on `this`
Input:

```dafny
datatype T = Leaf(x: int) | T(t: T) {
  function method {:tailrecursion} TR() : int {
    if Leaf? then 0
    else t.TR()
  }
}
```

Output:

```
Dafny /spillTargetCode:3 /noVerify /compile:4 test.dfy 

Dafny program verifier did not attempt verification
Wrote textual form of target program to test.cs
Errors compiling program into test
(1873,17): error CS0266: Cannot implicitly convert type '_module._IT' to '_module.T'. An explicit conversion exists (are you missing a cast?)
```

### PR DESCRIPTION
**Pull request by cpitclaudel**
Closes #2173.

### CODE REVIEW

File: Source/Dafny/Compilers/Compiler-Csharp.cs [hunk 1]
```diff
@@ -1331,7 +1331,9 @@ protected class ClassWriter : IClassWriter {
     protected override ConcreteSyntaxTree EmitTailCallStructure(MemberDecl member, ConcreteSyntaxTree wr) {
       Contract.Assume((member is Method m0 && m0.IsTailRecursive) || (member is Function f0 && f0.IsTailRecursive)); // precondition
       if (!member.IsStatic && !NeedsCustomReceiver(member)) {
-        wr.WriteLine("var _this = this;");
+        var receiverType =  member.EnclosingClass is DatatypeDecl dt ?
+          "_I" + dt.CompileName + TypeParameters(SelectNonGhost(dt, dt.TypeArgs)) : "var";
```
Comment (MikaelMayer) [inline Source/Dafny/Compilers/Compiler-Csharp.cs:1335]: Oh I see, since the fields stores an interface, you need to provide the interface for the base type. Nice and easy fix.

**Review by MikaelMayer — APPROVED** [review]
Bien trouvé !

**Review by fabiomadge — APPROVED** [review]

**Review by fabiomadge — APPROVED** [review]
