### PR TITLE
fix: Substitute for receiver in automatically generated induction hypothesis

### LINKED ISSUE #2001: Automatic induction does not substitute receiver parameter
Dafny currently verifies the following program, yet it crashes at run time. The problem is that the automatic induction does not substitute for `this` in the postcondition.

``` dafny
class Node {
  ghost var Repr: set<object>
  var left: Node?
  var uu: nat

  predicate Valid()
    reads this, Repr
    ensures Valid() ==> this in Repr
  {
    this in Repr &&
    (left != null ==>
      left in Repr && left.Repr <= Repr &&
      this !in left.Repr &&
      left.Valid()) &&
    ((left == null && uu == 0) || (left != null && uu != 0))
  }

  constructor (left: Node?)
    requires left == null || left.Valid()
    ensures Valid()
    ensures uu == 0 <==> left == null
  {
    if left == null {
      this.left, uu, Repr := null, 0, {this};
    } else {
      this.left, uu, Repr := left, 6, {this} + left.Repr;
    }
  }

  lemma AboutUU()
    requires Valid()
    ensures uu == 0
    decreases Repr
  { // BOGUS! This lemma should not verify.
  }
}

method Main() {
  var n0 := new Node(null);
  var n1 := new Node(n0);
  assert n1.uu != 0;
  n1.AboutUU();
  assert false;
  var divByZero := 5 / 0;
}
```

Here's the output:

```
% dafny /compile:3 test.dfy

Dafny program verifier finished with 5 verified, 0 errors
Running...

Error: Execution resulted in exception: Exception has been thrown by the target of an invocation.
System.DivideByZeroException: Attempted to divide by zero.
   at System.Numerics.BigInteger.op_Division(BigInteger dividend, BigInteger divisor)
   at System.Numerics.BigInteger.Divide(BigInteger dividend, BigInteger divisor)
   at Dafny.Helpers.EuclideanDivision(BigInteger a, BigInteger b)
   at _module.__default._Main()
   at Dafny.Helpers.WithHaltHandling(Action action)
   at __CallToMain.Main(String[] args)
```

### PR DESCRIPTION
**Pull request by RustanLeino**
A lemma like

``` dafny
class C {
  lemma MyLemma(x: X)
    requires Pre(x)
    ensures Post(x)
    decreases D(x)
  {
  }
}
```

should give rise to an induction hypothesis (which is provided by the verifier as an assumption on entry to the lemma's body) of the form

``` dafny
forall this': C, x': X | this'.Pre(x') && this'.D(x') < this.D(x) :: this'.Post(x')
```

Previously, this was generated incorrectly. In particular, the formula `this'.Post(x')` was previously generated as `this.P(x')`. This PR corrects the generated formula.

Fixes #2001

The example given in issue #2001 is included in `Test/dafny1/Induction.dfy`.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/Dafny/Verifier/Translator.ClassMembers.cs [hunk 1]
```diff
@@ -594,7 +594,7 @@ public partial class Translator {
           // Generate a CallStmt for the recursive call
           Expression recursiveCallReceiver;
           List<Expression> recursiveCallArgs;
-          RecursiveCallParameters(m.tok, m, m.TypeArgs, m.Ins, substMap, out recursiveCallReceiver, out recursiveCallArgs);
+          RecursiveCallParameters(m.tok, m, m.TypeArgs, m.Ins, receiverSubst, substMap, out recursiveCallReceiver, out recursiveCallArgs);
```
Comment (fabiomadge) [inline Source/Dafny/Verifier/Translator.ClassMembers.cs:597]: Is the comment in L555 still up-to-date?

**Review by fabiomadge — CHANGES_REQUESTED** [review]

File: Source/Dafny/Verifier/Translator.ClassMembers.cs [hunk 2]
```diff
@@ -547,12 +547,12 @@ public partial class Translator {
...
         var inductionVars = ApplyInduction(m.Ins, m.Attributes);
         if (inductionVars.Count != 0) {
-          // Let the parameters be this,x,y of the method M and suppose ApplyInduction returns y.
+          // Let the parameters be this,x,y of the method M and suppose ApplyInduction returns this,y.
           // Also, let Pre be the precondition and VF be the decreases clause.
           // Then, insert into the method body what amounts to:
           //     assume case-analysis-on-parameter[[ y' ]];
-          //     forall (y' | Pre(this, x, y') && VF(this, x, y') << VF(this, x, y)) {
-          //       this.M(x, y');
+          //     forall this',y' | Pre(this', x, y') && (VF(this', x, y') << VF(this', x, y)) {
```
Comment (fabiomadge) [inline Source/Dafny/Verifier/Translator.ClassMembers.cs:554]:
```suggestion
          //     forall this',y' | Pre(this', x, y') && (VF(this', x, y') << VF(this', x, y) {
```

Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.ClassMembers.cs:554]: That parenthesis matches the one before the first `VF`. (Since `<<` is two characters wide and isn't a Dafny operator, I felt compelled to surround the `... << ...` expression with parentheses.)

Comment (fabiomadge) [reply Source/Dafny/Verifier/Translator.ClassMembers.cs:554]: Yes, missed that.

**Review by fabiomadge — APPROVED** [review]
