### PR TITLE
Fix: Support for opaque function handles

### LINKED ISSUE #4202: Opaque functions passed as arguments causes type checking errors
### Dafny version

4.1.0

### Code to produce this issue

```dafny
opaque function F(x: int): char
{ 'D' }

method InitArray<D>(f: int -> D) returns (a: D)
{
  return f(44);
}

method Main() {
  reveal F();
  var c := InitArray(F);
}
```

### Command to run and resulting output

```code
$ dafny verify ../../Test/test.dfy
/Users/ekanshdg/Test/test.dfy(44,16): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
/Users/ekanshdg/Test/test.dfy(44,16): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
/Users/ekanshdg/Test/test.dfy(44,16): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
/Users/ekanshdg/Test/test.dfy(44,16): Error: wrong number of arguments to function: _module.__default.F (2 instead of 3)
/Users/ekanshdg/Test/test.dfy(44,16): Error: wrong number of arguments to function: _module.__default.F (2 instead of 3)
/Users/ekanshdg/Test/test.dfy(44,16): Error: wrong number of arguments to function: _module.__default.F (2 instead of 3)
/Users/ekanshdg/Test/test.dfy(54,21): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
7 type checking errors detected in /var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl

*** Encountered internal translation error - re-running Boogie to get better debug information

/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4580,4): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4581,2): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4582,8): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4589,13): Error: wrong number of arguments to function: _module.__default.F (2 instead of 3)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4602,4): Error: wrong number of arguments to function: _module.__default.F (2 instead of 3)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4603,2): Error: wrong number of arguments to function: _module.__default.F (2 instead of 3)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/test__module.bpl(4641,12): Error: wrong number of arguments to function: _module.__default.F#Handle (2 instead of 1)
```

### What happened?

Because opaque functions generate an extra argument, that is causing type-checking to fail when an opaque function is passed as an argument.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #4202
I added the corresponding test.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Verifier/Translator.cs [hunk 1]
```diff
@@ -5845,7 +5853,7 @@ void CheckCasePatternShape<VT>(CasePattern<VT> pat, Bpl.Expr rhs, IToken rhsTok,
         }
 
         {
-          // Requires(Ty.., F#Handle( Ty1, ..., TyN, Layer, self), Heap, arg1, ..., argN)
+          // Requires(Ty.., F#Handle( Ty1, ..., TyN, Layer, reveal, self), Heap, arg1, ..., argN)
```
Comment (atomb) [inline Source/DafnyCore/Verifier/Translator.cs:5856]: Based on my initial experiments, this should make it easier to allow all functions to have a reveal parameter. The fact that `requires` didn't have this parameter was an awkward asymmetry.

File: Test/git-issues/git-issue-4202.dfy [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+{ 'D' }
+
+method InitArray<D>(f: int -> D) returns (a: D)
+{
+  return f(44);
+}
+
+method Main() {
+  reveal F();
+  var c := InitArray(F);
```
Comment (atomb) [inline Test/git-issues/git-issue-4202.dfy:14]:
```suggestion
  var c := InitArray(F);
  assert c == 'D';
```
This would help ensure not only that it doesn't crash but also that `F` is properly revealed.

**Review by atomb — CHANGES_REQUESTED** [review]
This is great! I made one tiny suggested edit for the test.

**Review by atomb — DISMISSED** [review]
