### PR TITLE
Fix name clash in generated CS files when module and types have same name

### LINKED ISSUE #6014: Java backend not handling well module and datatype homonyms
### Dafny version

4.9.1

### Code to produce this issue

```dafny
module State {

  datatype State = Whatever

}

module Foo {

   import opened State

   const bar: State

   method Main() {
     print "Hello!\n";
  }
}
```

### Command to run and resulting output

```code
dafny build -t:java file.dfy
```

### What happened?

```
Dafny program verifier finished with 0 verified, 0 errors
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
file-java/Foo/__default.java:18: error: cannot find symbol
  public static State.State bar()
                     ^
  symbol:   class State
  location: class State
file-java/State/State.java:37: error: cannot find symbol
  private static final State theDefault = State.State.create();
                                               ^
  symbol:   variable State
  
  ...
```
  
This is similar to the error reported for CS backend in  #5746 
  

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by olivier-aws**
### What was changed?
This change updates the CS code generated from Dafny to fix name clashes between namespace and class when a module defines a datatype with the same name. On the example for https://github.com/dafny-lang/dafny/issues/6014, we have:

```
module A {

  datatype A = Foo. // Notice the name of the datatype is the name of the module

}

module B {

   import opened A

   const bar: A

   method Main() {
     print "Hello!\n";
  }
}

```

which generated the code (simlified for readability)

```
namespace A {

  public interface _IA {
    bool is_Foo { get; }
    _IA DowncastClone();
  }
  public class A : _IA {
    public A() {
    }
    // [...]

    public static _IA create() {
      return new A();
    }

    private static readonly A._IA theDefault = create();

   // [...]

    }
  }
} // end of namespace A

namespace B {

  public partial class __default {
    public static void _Main(Dafny.ISequence<Dafny.ISequence<Dafny.Rune>> __noArgsParameter)
    {
      Dafny.Helpers.Print((Dafny.Sequence<Dafny.Rune>.UnicodeFromString("Hello!\n")).ToVerbatimString(false));
    }
    public static A._IA bar { get {
      return A.A.Default();
    } }
  }
} // end of namespace B

```

The expression `A._IA theDefault` does not compile in C#, as the first A. is resolved to be the name of the class and not the name of the namespace. One solution could be to ensure we have `_IA` here instead of `A._IA` as for the `create` method, but the code to generate this type name is used at other places where the `A._IA` is required (e.g in ` bar` method in `namespace B`).

This change changes the name of the namespace `A` to `_NA` when there is a name clash with a datatype declared in `A`.

### How has this been tested?
Updated test gith-issues-6014.dfy

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs [hunk 1]
```diff
@@ -265,15 +265,42 @@ protected override ConcreteSyntaxTree CreateStaticMain(IClassWriter cw, string a
...
+          foreach (var d in module.TopLevelDecls) {
+            if (d is DatatypeDecl) {
+              if (d.Name == module.Name) {
+                hasNameClash = true;
+                break;
+              }
+            }
+          }
+        }
+        protectedModuleName = hasNameClash ? "_N" + protectedModuleName : protectedModuleName;
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs:300]: What about placing "_N" as a static constant of its own?

**Review by MikaelMayer — CHANGES_REQUESTED** [review]
This is great thank. One more less C# compiler bug in sight !

More test cases: it looks like the module name contains all the dots, whereas the inner declarations don't. Hence, the test file covering only top-level modules and declarations with the same name might not accurately represent all test cases.
Could you please add a test case like this one?
```dafny
module Enclosing {
  module A {
    datatype A = Foo
  }
}

module Enclosing.A {
  datatype A = Foo
}
```
I think these cases won't pass and yet they are likely, as [mentioned in this article](https://learn.microsoft.com/en-us/archive/blogs/ericlippert/do-not-name-a-class-the-same-as-its-namespace-part-one)

Also, for compatibility, we often wish that adding unrelated Dafny code does not change the API of existing generated code, i.e. that changes are possibly local. However, with this solution, a diff like that in Dafny
```diff
 module A {
   function ComputeThis(): int { ... }
+  datatype A = Foo
 }
```
would result in a non-local diff like that in the generated code.
```diff
-namespace A {
+namespace _NA {
   class _default {
     static int ComputeThis() { ... }
+  interface _IFoo { ... }
+  class Foo: _IFoo { ... }
 }
```
which would break any library calling into `A._default.ComputeThis()`. Well, one might argue that it's good to break calling code so that they are aware that the Dafny code is doing something not very C# compatible, but if that was important, I think we would prefer to reject the Dafny program at resolution time.

Would you mind flipping the fix over and renaming the datatype if it conflicts with the module name? I know this is extra hard work but I hope I have convinced you that it might be preferable. You could reuse the same "_N" prefix.

File: Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs [hunk 2]
```diff
@@ -443,7 +452,7 @@ protected override IClassWriter DeclareDatatype(DatatypeDecl dt, ConcreteSyntaxT
           // Overload the not-comparison operator
           wstruct.WriteLine("friend bool operator!=(const {0} &left, const {0} &right) {{ return !(left == right); }} ", structName);
 
-          // Define a custom hasher
+          // Define a custom hasherGetCompileName
```
Comment (olivier-aws) [inline Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs:455]: Remove extra GetCompileName

File: Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.cs [hunk 3]
```diff
@@ -1684,8 +1684,8 @@ private void EmitModule(Program program, ConcreteSyntaxTree programNode, ModuleD
           var (classIsExtern, include) = GetIsExternAndIncluded(defaultClassDecl);
 
           if (include) {
+            // HERE: was using IdName(defaultClassDecl) as name, now using clName(defaultClassDecl)
```
Comment (olivier-aws) [inline Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.cs:1687]: Remove comment

File: Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.cs [hunk 4]
```diff
@@ -1700,7 +1700,8 @@ private void EmitModule(Program program, ConcreteSyntaxTree programNode, ModuleD
           var (classIsExtern, include) = GetIsExternAndIncluded(cl);
 
           if (include) {
-            var cw = CreateClass(IdProtect(d.EnclosingModuleDefinition.GetCompileName(Options)), IdName(cl),
+            // HERE: was using IdName(cl) as name, now using clName(cl)
```
Comment (olivier-aws) [inline Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.cs:1703]: Remove comment

File: Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs [hunk 5]
```diff
@@ -265,15 +265,41 @@ protected override ConcreteSyntaxTree CreateStaticMain(IClassWriter cw, string a
       return wr.NewBlock($"public static void _StaticMain(Dafny.ISequence<Dafny.ISequence<{CharTypeName}>> {argsParameterName})");
     }
 
+    /// <summary>
+    /// Compute the name of the class to use to translate a data-type
+    /// </summary>
+    private string dataTypeName(DatatypeDecl dt) {
+      var protectedName = IdName(dt);
+      if (dt.EnclosingModuleDefinition is not null) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs:273]:
```suggestion
      if (dt.EnclosingModuleDefinition is { Name: var moduleName } && moduleName == protectedName) {
```
And then you can directly return. That simplifies the code a bit while increasing the readability.

File: Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs [hunk 6]
```diff
@@ -265,15 +265,41 @@ protected override ConcreteSyntaxTree CreateStaticMain(IClassWriter cw, string a
...
+        if (moduleName == protectedName) {
+          return $"_{protectedName}";
+        }
+      }
+      return protectedName;
+    }
+
+    private string className(TopLevelDecl dt) {
+      var protectedName = IdName(dt);
+      if (dt.EnclosingModuleDefinition is not null) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs:284]: Since the if-return it's the same code as the above function, perhaps you can consider refactoring it so that we can reuse it in both places.

File: Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs [hunk 7]
```diff
@@ -226,9 +226,18 @@ private string InstantiateTemplate(List<Type> typeArgs) {
 
     protected override string GetHelperModuleName() => "_dafny";
 
-    protected override IClassWriter CreateClass(string moduleName, string name, bool isExtern, string/*?*/ fullPrintName, List<TypeParameter>/*?*/ typeParameters, TopLevelDecl cls, List<Type>/*?*/ superClasses, IOrigin tok, ConcreteSyntaxTree wr) {
+    private string clName(TopLevelDecl cl) {
+      var className = IdName(cl);
+      if (cl is ClassDecl || cl is DefaultClassDecl) {
+        return className;
+      }
+      return "class_" + className;
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs:234]:
```suggestion
      return "_class_" + className;
```
That way we are sure we don't clash with something named "class_..." already in the dafny code.

**Review by MikaelMayer — COMMENTED** [review]
A few comments, otherwise I find this solution very adequate. Thanks for addressing all my previous comment.

File: Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs (hunk 5 above)
Comment (olivier-aws) [reply Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs:273]: Thanks I was not aware of this syntax from C#

File: Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs (hunk 6 above)
Comment (olivier-aws) [reply Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs:284]: Indeed, I first used two different encodings for class and datatypes, hence two different functions. I decided to revert to the same encoding but forgot to merge the functions. Will do.

File: Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs (hunk 7 above)
Comment (olivier-aws) [reply Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs:234]: The "class_" + className encoding was the one already done by the CppCodeGenerator. I'm not sure I want to take the risk to modify it in this change, maybe a subsequent one?

Comment (MikaelMayer) [reply Source/DafnyCore/Backends/Cplusplus/CppCodeGenerator.cs:234]: Ok, let's postpone it for a subsequent one, perhaps either proactively or if someone hits this issue. It's not a soundness issue anyway, just annoying if it happened, but it's unlikely in practice.

**Review by MikaelMayer — APPROVED** [review]
