### PR TITLE
Fixes #315

### LINKED ISSUE #315: boogie type error from map comprehension
I was attempting to use the general map comprehension syntax and got a boogie error.

```
function foo(s: seq<seq<int>>) : map<seq<int>, seq<int>>
{
  map i:int | 0 <= i < |s| :: s[i] := s[i]
}
```

```
$ dafny mapcompbug.dfy 
Dafny 2.3.0.10506
(0,-1): Error: invalid argument types (int and Seq Box) to binary operator ==
mapcompbug.dfy(3,2): Error: invalid type for argument 0 in application of map$project$0#0#i#0: int (expected: Seq Box)
(0,-1): Error: invalid argument types (int and Seq Box) to binary operator ==
mapcompbug.dfy(3,2): Error: invalid type for argument 0 in application of map$project$1#0#i#0: int (expected: Seq Box)
(0,-1): Error: invalid argument types (int and Seq Box) to binary operator ==
mapcompbug.dfy(3,2): Error: invalid type for argument 0 in application of map$project$2#0#i#0: int (expected: Seq Box)
6 type checking errors detected in /var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl

*** Encountered internal translation error - re-running Boogie to get better debug information

/var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl(2683,40): Error: invalid argument types (int and Seq Box) to binary operator ==
/var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl(2684,80): Error: invalid type for argument 0 in application of map$project$0#0#i#0: int (expected: Seq Box)
/var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl(2708,40): Error: invalid argument types (int and Seq Box) to binary operator ==
/var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl(2710,66): Error: invalid type for argument 0 in application of map$project$1#0#i#0: int (expected: Seq Box)
/var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl(2776,40): Error: invalid argument types (int and Seq Box) to binary operator ==
/var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl(2777,80): Error: invalid type for argument 0 in application of map$project$2#0#i#0: int (expected: Seq Box)
6 type checking errors detected in /var/folders/pk/wmrmymkx7yv5fxn8gb26fx480000gp/T/mapcompbug__module.bpl
```

Here's the boogie code:
```
// definition axiom for _module.__default.foo(revealed)
axiom 0 <= $FunctionContextHeight
   ==> (forall s#0: Seq Box :: 
    { _module.__default.foo(s#0) } 
    _module.__default.foo#canCall(s#0)
         || (0 != $FunctionContextHeight && $Is(s#0, TSeq(TSeq(TInt))))
       ==> (forall a#0#0#0: int :: 
          { map$project$0#0#i#0($Unbox(Seq#Index(s#0, a#0#0#0)): Seq Box) } 
          LitInt(0) <= a#0#0#0 && a#0#0#0 < Seq#Length(s#0)
             ==> LitInt(0) <= map$project$0#0#i#0($Unbox(Seq#Index(s#0, a#0#0#0)): Seq Box) 
               && map$project$0#0#i#0($Unbox(Seq#Index(s#0, a#0#0#0)): Seq Box) < Seq#Length(s#0)
               && $Unbox(Seq#Index(s#0, a#0#0#0)): Seq Box
                 == $Unbox(Seq#Index(s#0, map$project$0#0#i#0($Unbox(Seq#Index(s#0, a#0#0#0)): Seq Box))): Seq Box) 
         && _module.__default.foo(s#0)
           == Map#Glue((lambda $w#0: Box :: 
              (exists a#1#0#0: int :: 
                LitInt(0) <= a#1#0#0
                   && a#1#0#0 < Seq#Length(s#0)
                   && $Unbox($w#0): int == $Unbox(Seq#Index(s#0, a#1#0#0)): Seq Box)), 
            (lambda $w#0: Box :: Seq#Index(s#0, map$project$0#0#i#0($Unbox($w#0): int))), 
            TMap(TSeq(TInt), TSeq(TInt))));
```

Looks like the third line from the bottom has the error.

### PR DESCRIPTION
**Pull request by mschlaipfer**

### CODE REVIEW

File: Source/Dafny/Translator.cs [hunk 1]
```diff
@@ -15280,19 +15279,22 @@ public Expression GetSubstitutedBody(LetExpr e)
...
             var subst = new Dictionary<IVariable,Expression>();
-            subst.Add(e.BoundVars[0], new BoogieWrapper(unboxw, e.BoundVars[0].Type));
+            subst.Add(bv, new BoogieWrapper(unboxw, bv.Type));
 
             var ebody = BplAnd(typeAntecedent ?? Bpl.Expr.True, TrExpr(Translator.Substitute(e.Range, null, subst)));
             keys = new Bpl.LambdaExpr(e.tok, new List<TypeVariable>(), new List<Variable> { wVar }, kv, ebody);
             ebody = TrExpr(Translator.Substitute(e.Term, null, subst));
             values = new Bpl.LambdaExpr(e.tok, new List<TypeVariable>(), new List<Variable> { wVar }, kv, BoxIfNecessary(expr.tok, ebody, e.Term.Type));
           } else {
+            var t = e.TermLeft;
```
Comment (mschlaipfer) [inline Source/Dafny/Translator.cs]: Using `e.TermLeft` instead of `e.BoundVars[0]` in this case is the crucial change.
