### PR TITLE
Fix: No more spurious restart needed in the IDE

### LINKED ISSUE #4833: Dafny IDE needs restarting every 3-4 minutes
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
Just wait. After a few minutes, nothing works.
```

### Command to run and resulting output

_No response_

### What happened?

Here is more debugging information:
- It seems that the language server receives only one notification about the current file open, even if there are other files open. So the number of open files for the language server is 1
- After 3-4 minutes, VSCode sends to the language server a notification of closed files for the files that the language server did not even thought were open.
- Since the language server keeps track of a number of files open, it decrements that number, gets to 0 and dispose the compilation, which prevents anything else from happening.

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #4833 

### Description
I replaced the openFileCount by openFiles so that closing a document, even if unexpected like VSCode does randomly, won't trigger the Compilation object to be disposed, which crashes the IDE every 3-4 minutes on projects with multiple files open.

### How has this been tested?
I have been enjoying the IDE for 20 minutes straight without restarting it. It's a fantastic experience. I'm going to turn on "verification on change" again.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyLanguageServer/Workspace/ProjectManager.cs [hunk 1]
```diff
@@ -345,7 +346,7 @@ public class ProjectManager : IDisposable {
   }
 
   public void OpenDocument(Uri uri, bool triggerCompilation) {
-    Interlocked.Increment(ref openFileCount);
+    openFiles.TryAdd(uri, 1);
```
Comment (atomb) [inline Source/DafnyLanguageServer/Workspace/ProjectManager.cs:349]: What role does the `1` serve here? Could this be a set instead of a map?

Comment (MikaelMayer) [reply Source/DafnyLanguageServer/Workspace/ProjectManager.cs:349]: The only concurrent set I found in C# is a ConcurrentBag but it curiously does not have a method for removing a specific element.

**Review by atomb — APPROVED** [review]

**Comment by keyboardDrummer** [comment]
Amazing, thanks :)

@MikaelMayer I'm a little concerned that we didn't get to understand how you got the stack trace:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EventLoopScheduler'.
   at System.Reactive.Concurrency.EventLoopScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs:line 173
   at System.Reactive.ObserveOnObserverNew`1.Schedule() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 486
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 139
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 139
   at Microsoft.Dafny.LanguageServer.Language.ObservableErrorReporter.AddDiagnosticForFile(DafnyDiagnostic dafnyDiagnostic, MessageSource messageSource, Uri uri) in C:\Users\mimayere\Documents\dafny\Source\DafnyLanguageServer\Language\ObservableErrorReporter.cs:line 139
```

But then again I wouldn't think the exception from this stack trace causes an issue, because it relates to already closed project managers, so we can leave it for now

**Comment by MikaelMayer** [comment]
> Amazing, thanks :)
> 
> @MikaelMayer I'm a little concerned that we didn't get to understand how you got the stack trace:
> 
> ```
> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'EventLoopScheduler'.
>    at System.Reactive.Concurrency.EventLoopScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs:line 173
>    at System.Reactive.ObserveOnObserverNew`1.Schedule() in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 486
>    at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 139
>    at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 139
>    at Microsoft.Dafny.LanguageServer.Language.ObservableErrorReporter.AddDiagnosticForFile(DafnyDiagnostic dafnyDiagnostic, MessageSource messageSource, Uri uri) in C:\Users\mimayere\Documents\dafny\Source\DafnyLanguageServer\Language\ObservableErrorReporter.cs:line 139
> ```
> 
> But then again I wouldn't think the exception from this stack trace causes an issue, because it relates to already closed project managers, so we can leave it for now

I got this exception while putting breakpoints on disposed method, which apparently was caught here:
* DafnyTextDocumentHandler.cs line 102, `telemetryPublisher.PublishUnhandledException(e);`
This project was closed but should not as I still had files open.
