### PR TITLE
#261: Fixed a compiler bug in printing the type of a temporary

### LINKED ISSUE #261: bug in destructing tuple in assignment
The below code verifies but does not compile correctly:

```
datatype Option<T> = None | Some(T)

method Main() {
    var x : Option<(nat, nat)> := Some((2,3));
    var Some((a,b)) := x;
}
```

### PR DESCRIPTION
**Pull request by davidcok**
Fixes #261.

### CODE REVIEW

File: Source/Dafny/Compiler.cs [hunk 1]
```diff
@@ -1976,7 +1976,9 @@ protected class NullClassWriter : IClassWriter {
           } else {
             var sw = new TargetWriter(wr.IndentLevel, true);
             EmitDestructor(tmp_name, formal, k, ctor, ((DatatypeValue)pat.Expr).InferredTypeArgs, arg.Expr.Type, sw);
-            TrCasePatternOpt(arg, null, sw.ToString(), formal.Type, pat.Expr.tok, wr, inLetExprBody);
+            Type targetType = formal.Type;
+            if (targetType.IsTypeParameter) targetType = ((DatatypeValue) pat.Expr).InferredTypeArgs[0];
```
Comment (acioc) [inline Source/Dafny/Compiler.cs:1980]: I wasn't aware of `DatatypeValue`. 👍
