### PR TITLE
Fix: Handling of opaque methods in traits overriding check

### LINKED ISSUE #4205: Extending a trait with an opaque function causes error, but only on the commandline and not on VSCode.
### Dafny version

4.1.0

### Code to produce this issue

```dafny
trait T {
  opaque function bar(): int
}

class F extends T {
  opaque function bar(): int {
    1
  }
}
```

### Command to run and resulting output

```code
$ ./Binaries/Dafny verify  ~/test/git-issue-549.dfy
git-issue-549.dfy(2,18): Error: wrong number of arguments to function: _module.T.bar (1 instead of 2)
git-issue-549.dfy(2,18): Error: wrong number of arguments to function: _module.T.bar (1 instead of 2)
git-issue-549.dfy(6,18): Error: wrong number of arguments to function: _module.F.bar (2 instead of 3)
git-issue-549.dfy(2,18): Error: wrong number of arguments to function: _module.T.bar (1 instead of 2)
git-issue-549.dfy(6,18): Error: wrong number of arguments to function: _module.F.bar (2 instead of 3)
5 type checking errors detected in /var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl

*** Encountered internal translation error - re-running Boogie to get better debug information

/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl(2958,6): Error: wrong number of arguments to function: _module.T.bar (1 instead of 2)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl(2959,8): Error: wrong number of arguments to function: _module.T.bar (1 instead of 2)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl(2959,29): Error: wrong number of arguments to function: _module.F.bar (2 instead of 3)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl(2962,11): Error: wrong number of arguments to function: _module.T.bar (1 instead of 2)
/var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl(2962,34): Error: wrong number of arguments to function: _module.F.bar (2 instead of 3)
5 type checking errors detected in /var/folders/v7/dtr5626966sf_f5665tczxpw0000gr/T/git-issue-549__module.bpl
```

### What happened?

In the Boogie translation, the `override axiom for _module.T.bar in class _module.F` seems to have the `reveal` argument missing.

Lines 2955 to 2962 of boogie_print.bpl:
```
// override axiom for _module.T.bar in class _module.F
axiom 0 <= $FunctionContextHeight
   ==> (forall this: ref :: 
    { _module.T.bar(this), $Is(this, Tclass._module.F()) } 
      { _module.T.bar(this), _module.F.bar($LZ, this) } 
    _module.F.bar#canCall(this)
         || (0 < $FunctionContextHeight && this != null && $Is(this, Tclass._module.F()))
       ==> _module.T.bar(this) == _module.F.bar($LZ, this));
```

Whereas, lines 2810-2811:
```
// function declaration for _module.T.bar
function _module.T.bar($reveal: bool, this: ref) : int;```


Interestingly, this example still verifies on the VSCode extension, but not on the command-line.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #4205
I added the corresponding test.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Verifier/Translator.ClassMembers.cs [hunk 1]
```diff
@@ -1069,6 +1070,18 @@ public partial class Translator {
...
+      if (f.IsOpaque) {
+        Contract.Assert(overridingFunction.IsOpaque);
+        var revealVar = new Boogie.BoundVariable(f.tok, new Boogie.TypedIdent(f.tok, "reveal", Boogie.Type.Bool));
+        forallFormals.Add(revealVar);
+        reveal = new Boogie.IdentifierExpr(f.tok, revealVar);
+        argsJF.Add(reveal);
+      } else if (overridingFunction.IsOpaque) {
+        // We can't use a bound variable $fuel, because then one of the triggers won't be mentioning this $fuel.
+        // Instead, we do the next best thing: use the literal false.
+        reveal = new Boogie.IdentifierExpr(f.tok, "false", Boogie.Type.Bool);
```
Comment (atomb) [inline Source/DafnyCore/Verifier/Translator.ClassMembers.cs:1082]: Can you create a literal expression instead of an identifier expression here? I think this accidentally works but is confusing, since `false` is an actual value rather than a name for a value, at least in the semantics I understand.

File: docs/dev/news/4205.fix [hunk 2]
```diff
@@ -0,0 +1 @@
+Handling of opaque methods in traits overriding check
```
Comment (atomb) [inline docs/dev/news/4205.fix:1]: It would be nice to have a longer, more explanatory message here.

Comment (atomb) [reply docs/dev/news/4205.fix:1]: Maybe "Traits with opaque functions can now be extended without errors" or something like that.

**Review by atomb — CHANGES_REQUESTED** [review]
I suggested a couple of tiny adjustments.

**Review by atomb — APPROVED** [review]
Looks good!
