### PR TITLE
In-memory implementation of %diff, enable integration tests on windows

### LINKED ISSUE #1313: CI does not run tests on Windows
The Dafny continuation integration does not run the Dafny test suite on windows, see [the code](hub/workflows/msbuild.yml#L35).

### LINKED ISSUE #1538: xUnit lit test runner doesn't work on Windows
Hidden regression from #680, since the CI is not running the integration tests on windows (#1313). I defined `%diff` as just `diff`, which works on Linux and OSX but not Windows.

I already had an alternative implemented using `DiffPlex`, but I didn't use it in #680 only because it needed a bit of tweaking to interact correctly with XFAIL tests.

### PR DESCRIPTION
**Pull request by robin-aws**
Fixes #1313
Fixes #1538

### CODE REVIEW

**Review by MikaelMayer — DISMISSED** [review]
This works well on Windows, thanks for putting this up!

File: Source/XUnitExtensions/Lit/MainMethodLitCommand.cs [hunk 1]
```diff
@@ -34,6 +34,10 @@ public class MainMethodLitCommand : ILitCommand {
 
       var exitCode = (int)assembly.EntryPoint!.Invoke(null, new object[] { arguments })!;
 
+      inputReader?.Close();
```
Comment (keyboardDrummer) [inline Source/XUnitExtensions/Lit/MainMethodLitCommand.cs:37]: Shouldn't we do this at the call site of `Execute`, where the disposables are created?

File: Source/DafnyDriver/DafnyDriver.cs [hunk 2]
```diff
@@ -592,20 +592,25 @@ private record TargetPaths(string Directory, string Filename) {
 
       WriteFile(paths.Filename, targetProgramText, callToMain);
 
+      var relativeTarget = paths.RelativeFilename;
+      if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
+        // To satisfy the tests that assume a '/' instead of a '\'
+        relativeTarget = relativeTarget.Replace('\\', '/');
```
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyDriver/DafnyDriver.cs:600]: Windows supports both "\\" and "/", but all the `*.expect` files assume that the output is using `/`, hence we normalize using the UNIX directory separator. This is also why we only normalize it at printing time, because it does not bring anything to change it before, and I believe that it's better that this change is made on the last step, for test output consistency only.

File: Source/DafnyTestGeneration/Main.cs [hunk 3]
```diff
@@ -110,9 +110,9 @@ public static class Main {
         yield break;
       }
       var dafnyInfo = new DafnyInfo(program);
-      var rawName = sourceFile.Split("/").Last().Split(".").First();
+      var rawName = sourceFile.Split(new[] { '/', '\\' }).Last().Split(".").First();
```
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyTestGeneration/Main.cs:113]: I would definitely agree on this readability refactoring on that but it would need to be tested, since they don't have exactly the same semantics.
`GetFileNameWithoutExtension` returns the filename minus the last period and everything that follows.
This code returns the filename minus the first period and everything that follows.
So for example, in the case of a file `file.dfy.expect`, this code would return `file`, but `Path.GetFileNameWithoutExtension` would return `file.dfy`.
I'm not sure it's a problem though, but I would have to run the full CI on that to ensure it's working so let's keep it for the very last test, for when there will be no CI test failing (currently there are a lot).

File: Source/DafnyTestGeneration/Main.cs [hunk 4]
```diff
@@ -110,9 +110,9 @@ public static class Main {
...
 
-      yield return $"include \"{sourceFile}\"";
+      yield return $"include \"{sourceFile.Replace("\\", "\\\\")}\"";
```
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyTestGeneration/Main.cs:115]: It outputs an include statement that will include the Dafny generated files, but since in Windows the paths are backslashes, we cannot output raw backslashes in Dafny code, they need to be escaped.

File: Source/XUnitExtensions/Lit/LitTestCase.cs [hunk 5]
```diff
@@ -58,27 +62,41 @@ public class LitTestCase {
...
           if (exitCode != 0) {
-            throw new SkipException($"Command returned non-zero exit code ({exitCode}): {command}\nOutput:\n{output}\nError:\n{error}");
+            throw new SkipException(
+              $"Command returned non-zero exit code ({exitCode}): {command}\nOutput:\n{output}\nError:\n{error}");
           }
         }
 
         if (exitCode != 0) {
-          throw new Exception($"Command returned non-zero exit code ({exitCode}): {command}\nOutput:\n{output}\nError:\n{error}");
+          // TODO: sloppy, don't commit without cleaning up
```
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:88]: Just marked the PR as draft, but thanks for spotting.

File: Source/XUnitExtensions/Lit/MainMethodLitCommand.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/MainMethodLitCommand.cs:37]: I'll wait for @robin-aws  to answer this one because he wrote this part.

File: Source/Dafny/Compilers/Compiler-go.cs [hunk 6]
```diff
@@ -3519,6 +3520,14 @@ private class SpecialNativeType : UserDefinedType {
       // Dafny compiles to the old Go package system, whereas Go has moved on to a module
       // system. Until Dafny's Go compiler catches up, the GO111MODULE variable has to be set.
       psi.EnvironmentVariables["GO111MODULE"] = "auto";
+      if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
+        // On Windows, Path.GetTempPath() returns "c:\Windows" which, being not writable, crashes Go.
+        // Hence we set up a local temporary directory depending on the user.
+        psi.EnvironmentVariables["GOTMPDIR"] =
+          Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\Temp";
```
Comment (fabiomadge) [inline Source/Dafny/Compilers/Compiler-go.cs:3527]: Should we clean that up?

File: Source/Directory.Build.props [hunk 7]
```diff
@@ -2,7 +2,7 @@
 
   <!-- Target framework -->
   <PropertyGroup>
-    <TargetFramework>net6.0</TargetFramework>
+    <TargetFramework>net5.0</TargetFramework>
```
Comment (fabiomadge) [inline Source/Directory.Build.props:5]: Why can't we have `net6.0`?

File: Test/comp/Variance.dfy [hunk 8]
```diff
@@ -35,7 +35,8 @@ datatype Non<T> = Non(T){
     method mD(x: T) returns (r: T) { r := x; }
 }
 
-datatype Con<-T> = Con(T -> int) {
+// Con.java would create an error in Windows file systems because "Con" is a reserved file name.
```
Comment (fabiomadge) [inline Test/comp/Variance.dfy:38]:
```suggestion
```
Thanks for the explanation, but I don't think we need to keep it around. This has the nice side-effect of preserving the line numbers in the `.expect`.

File: Source/DafnyDriver/DafnyDriver.cs [hunk 9]
```diff
@@ -592,20 +594,25 @@ private record TargetPaths(string Directory, string Filename) {
...
-        outputWriter.WriteLine("Wrote textual form of target program to {0}", paths.RelativeFilename);
+        outputWriter.WriteLine("Wrote textual form of target program to {0}", relativeTarget);
       }
 
       foreach (var entry in otherFiles) {
         var filename = entry.Key;
         WriteFile(Path.Join(paths.SourceDirectory, filename), entry.Value);
         if (DafnyOptions.O.CompileVerbose) {
-          outputWriter.WriteLine("Additional target code written to {0}", Path.Join(paths.RelativeDirectory, filename));
+          outputWriter.WriteLine("Additional target code written to {0}", Path.Join(paths.RelativeDirectory, filename).Replace("\\", "/"));
```
Comment (fabiomadge) [inline Source/DafnyDriver/DafnyDriver.cs:615]: Should we make is platform depended?

File: Source/DafnyDriver/DafnyDriver.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (fabiomadge) [reply Source/DafnyDriver/DafnyDriver.cs:600]: You could add something like `NormalizedRelativeFilename`.

File: Source/XUnitExtensions/Lit/LitTestCase.cs [hunk 10]
```diff
@@ -58,27 +63,40 @@ public class LitTestCase {
...
+      List<(string, string)> results = new();
 
       foreach (var command in commands) {
         int exitCode;
         string output;
         string error;
         try {
-          outputHelper.WriteLine($"Executing command: {command}");
+          var commandStr = $"{command}";
+          outputHelper.WriteLine($"Executing command: {commandStr}");
```
Comment (fabiomadge) [inline Source/XUnitExtensions/Lit/LitTestCase.cs:75]: Does that fix something?

File: Source/XUnitExtensions/AssertWithDiff.cs [hunk 11]
```diff
@@ -0,0 +1,37 @@
...
+        return;
+      }
+
+      var message = new StringBuilder();
+      message.AppendLine("AssertEqualWithDiff() Failure");
+      message.AppendLine("Diff (changing expected into actual):");
+      foreach (var line in diff.Lines) {
+        switch (line.Type) {
+          case ChangeType.Inserted:
+            message.Append('+');
```
Comment (fabiomadge) [inline Source/XUnitExtensions/AssertWithDiff.cs:21]: Do we want `{}` here?

File: Source/DafnyTestGeneration/Main.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/DafnyTestGeneration/Main.cs:113]: So, now then?

File: Source/DafnyTestGeneration/Main.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/DafnyTestGeneration/Main.cs:115]: I remember someone suggesting to use verbatim strings for code like this :D

Consider moving the replace into a method `EscapeDafnyStringLiteral`

File: Source/XUnitExtensions/Lit/DiffCommand.cs [hunk 12]
```diff
@@ -0,0 +1,42 @@
+using System;
+using System.IO;
+using Xunit;
+using Xunit.Abstractions;
+using Xunit.Sdk;
+
+namespace XUnitExtensions.Lit {
+  public class DiffCommand : ILitCommand {
```
Comment (keyboardDrummer) [inline Source/XUnitExtensions/Lit/DiffCommand.cs:8]: Could you add a small comment explaining what this class does? Maybe a link to `https://man7.org/linux/man-pages/man1/diff.1.html`

File: Source/XUnitExtensions/Lit/MainMethodLitCommand.cs (hunk 1 above)
Comment (keyboardDrummer) [reply Source/XUnitExtensions/Lit/MainMethodLitCommand.cs:37]: You're closing at the `Execute` call site now so these lines can be removed

File: Source/DafnyDriver/DafnyDriver.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyDriver/DafnyDriver.cs:600]: Thanks @keyboardDrummer . I'm sorry for your feeling. As a regular Windows user myself, I'm used to see and use both slashes and backslashes, and I guess that most Windows developers are used to that, so as one of these users you worry about, I can reassure you, it won't negatively impact user experience. Note that this is also used to display informative relative paths in specific logging messages, so it is not an absolute path nor a path used in some API. I myself write paths using slashes most of the time when possible, because when I put backslashes in strings (bash, php, python, JavaScript...), they need to be doubled. This makes scripting quite hard.

The only way to add a global constant to check if we are testing or not would be to change an environment variable, since most tests are actually running whole Dafny processes. But I strongly advise against changing the behavior of an application depending on whether it is tested or not, it makes things even harder to debug (e.g. expectations that are different from a platform to another one).

That said, I think that a good way to implement a change compatible with your thinking would be, in our customized test-aware %diff command, to search and replace the following regex:

    (?<=(?:Wrote textual form of (partial )?target program to |Additional target code written to ).*)\\
    /

Let me know if you still want me to implement the change despite of the above.

File: Source/DafnyTestGeneration/Main.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyTestGeneration/Main.cs:113]: I'm ready to answer this now. Looking at the code more carefully, this `rawName` should not contain any dot since it is used as a module name in a dafny tile. However, the function `Path.GetFileNameWithoutExtension` does not guarantee that the final name won't have a dot. But the construct above does guarantee the absence of dot in the final name.
Note that I also found some Dafny files that look like `filename.dfy.tmp.dprint.dfy` and that would thus crash the test, so even though this would not be a problem now, it's better to not introduce potential bugs.
Thus, let's keep it the way it is (at least for the dot part).

File: Source/DafnyTestGeneration/Main.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyTestGeneration/Main.cs:115]: The waterer watered :-P
Considered and done.

File: Source/Dafny/Compilers/Compiler-go.cs (hunk 6 above)
Comment (MikaelMayer) [reply Source/Dafny/Compilers/Compiler-go.cs:3527]: What do you mean? These four lines of code literally fix all the GO tests on Windows.
I took action on this by refactoring `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)` into a single variable, but I'm not sure if it's what you meant.

File: Source/Directory.Build.props (hunk 7 above)
Comment (MikaelMayer) [reply Source/Directory.Build.props:5]: Ooops good catch. I have had problems with a merge commit that I had to resolve manually, and it looks like this was one of the errors that I missed.

File: Test/comp/Variance.dfy (hunk 8 above)
Comment (MikaelMayer) [reply Test/comp/Variance.dfy:38]: Done. Indeed, if someone ever renamed it to `Con`, Dafny would generate a suitable error now on Windows, so this is not needed anymore.

File: Source/XUnitExtensions/Lit/LitTestCase.cs (hunk 10 above)
Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:75]: No fix here, only explicit the string cast conversion which used to happen implicitly before, and enable to debug it more easily - that's how I spotted virtually all the problems with the backslashes in commands.

File: Source/Dafny/Compilers/Compiler-go.cs (hunk 6 above)
Comment (fabiomadge) [reply Source/Dafny/Compilers/Compiler-go.cs:3527]: I was wondering whether this temporary data is still there after finishing the compilation.

File: Source/XUnitExtensions/Lit/LitTestCase.cs (hunk 10 above)
Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:75]: Unless you want otherwise, I'm leaving it because it will ease maintainability in the future as we will add more various tests.

File: Source/XUnitExtensions/AssertWithDiff.cs (hunk 11 above)
Comment (MikaelMayer) [reply Source/XUnitExtensions/AssertWithDiff.cs:21]: The goal of this text is to be appended, so I understand why @robin-aws  did not concatenate it.
However, I simplified the code a bit with a switch expression:

```
        var prefix = line.Type switch
        {
          ChangeType.Inserted => '+',
          ChangeType.Deleted => '-',
          _ => ' '
        };
        message.Append(prefix);
```

File: Source/XUnitExtensions/Lit/LitTestCase.cs (hunk 10 above)
Comment (fabiomadge) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:75]: Just out of curiosity, how did it help you?

File: .github/workflows/msbuild.yml [hunk 13]
```diff
@@ -125,8 +125,21 @@ jobs:
       run: |
         unzip dafny/Package/CI.zip -d unzippedRelease
     - name: Run integration tests
+      if: runner.os == 'Windows'
+      env:
```
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply .github/workflows/msbuild.yml:129]: I'm not familiar enough with the build system, and I did not write these lines.
What is your suggestion exactly? Where is the build level?

File: Source/Dafny/Compilers/Compiler-go.cs (hunk 6 above)
Comment (MikaelMayer) [reply Source/Dafny/Compilers/Compiler-go.cs:3527]: Oh, I see, it's a general question about the temporary directory, not specific about Windows. Here we only provide a valid path for temporary files, but Unix and MacOX use their own paths. Here for Windows I use a standard temp directory that is weirdly not used by `Path.GetTemporaryPath`.
I don't think we should clean up the temporary directory ourselves. It might be used at any time by other processes.

File: Source/DafnyDriver/DafnyDriver.cs [hunk 14]
```diff
@@ -616,6 +623,21 @@ private record TargetPaths(string Directory, string Filename) {
         Directory.CreateDirectory(dir);
       }
 
+      // We cannot get the full path correctly on Windows if the file name uses some reserved words
```
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyDriver/DafnyDriver.cs:626]: Done.

File: Source/XUnitExtensions/Lit/DiffCommand.cs (hunk 12 above)
Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/DiffCommand.cs:8]: Added the following comment:

```
  /// <summary>
  /// This class implements the equivalent of the Unix 'diff' command that lit tests rely on,
  /// because 'diff' does not exist on Windows.
  /// </summary>
  ```

File: Source/DafnyTestGeneration/Main.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyTestGeneration/Main.cs:113]: I still refactored the code the following way:

`Path.GetFileName(sourceFile).Split(".").First()`

File: Source/XUnitExtensions/Lit/LitTestCase.cs (hunk 10 above)
Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:75]: I put a breakpoint on line `outputHelper.WriteLine($"Executing command: {commandStr}");` and figure out what the command is immediately by looking at the variable value, and thus I can enter the command execution if I want to inspect it.

Comment (fabiomadge) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:75]: I see, but can't you just have the breakpoint on the next line? Anyway, it's fine if think that it's worth it.

Comment (MikaelMayer) [reply Source/XUnitExtensions/Lit/LitTestCase.cs:75]: That's true. Historically, I did not find where the output was being written to so but now I do, so let me remove this line.

File: Source/DafnyTestGeneration/Main.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/DafnyTestGeneration/Main.cs]: I'm confused. Don't we want it to assign `filename.dfy.tmp.dprint` in case the sourceFile is `filename.dfy.tmp.dprint.dfy` ?

File: Source/DafnyDriver/DafnyDriver.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/DafnyDriver/DafnyDriver.cs]: Alright. If slashes in either direction are the norm in Windows, then we don't need to only output backslashes :-)

File: Source/XUnitExtensions/Lit/LitTestCase.cs (hunk 10 above)
Comment (keyboardDrummer) [reply Source/XUnitExtensions/Lit/LitTestCase.cs]: I think we could extract variables almost everywhere in the code to improve the debug experience, so we shouldn't commit those extracted variables to source after we're done debugging. I see you've reverted this change so I'll mark as resolved.

**Review by keyboardDrummer — APPROVED** [review]

File: Source/DafnyTestGeneration/Main.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (MikaelMayer) [reply Source/DafnyTestGeneration/Main.cs]: I frankly don't know what exactly we want here, because I was just fixing the filename extraction so that it works on Windows. The documentation about this method is here and dates from earlier in March:
https://github.com/Dargones/dafny/tree/PatchesToCounterExamples/Source/DafnyTestGeneration#readme
As you can read, the name generation is under-specified because it assumes a file name with exactly one dot.

If you have a clear vision (I don't) and are sure of the intended behavior, then I'll do the change because it's cheap. I just checked that Dafny accepts dots in module names, so lights are green on that. Otherwise; I'd suggest we leave it for when it will be needed.

[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/DafnyTestGeneration/Main.cs]: Let's leave it since it seems out of scope for this PR :-)

**Review by fabiomadge — APPROVED** [review]
