### PR TITLE
fix: DafnyOptions.O.Compiler is null, preventing instantiation of ModuleExportDecl

### LINKED ISSUE #1932: Bug: Using Dafny.dll to build an AST fails if no compiler specified.
Since #1894 , `ModuleExportDecl.FullCompileName` used in the constructor of `ModuleExportDecl` can throw a null pointer exception because `TopLevelDecl.FullCompileName` now [depends on](https://github.com/dafny-lang/dafny/commit/d9aa57676e1ceca6bf151e0fe30d7b0b83e63cc5#diff-fa257574acd41f12645bbc3b82e23fc93ac386d13a9fb58c0f5f54944a8359e3R4313) `DafnyOptions.O.Compiler`, which does not have a default value.

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #1932

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/Dafny/AST/DafnyAst.cs [hunk 1]
```diff
@@ -4312,9 +4312,12 @@ public TopLevelDecl(IToken tok, string name, ModuleDefinition enclosingModule, L
...
           }
         }
-
-        return DafnyOptions.O.Compiler.GetCompileName(EnclosingModuleDefinition.IsDefaultModule,
+        if (DafnyOptions.O.Compiler != null) {
+          return DafnyOptions.O.Compiler.GetCompileName(EnclosingModuleDefinition.IsDefaultModule,
           EnclosingModuleDefinition.CompileName, CompileName);
+        } else {
+          return Declaration.IdProtect(EnclosingModuleDefinition.CompileName) + "." + Declaration.IdProtect(CompileName);
+        }
```
Comment (cpitclaudel) [inline Source/Dafny/AST/DafnyAst.cs:4320]: Why do we not instantiate the compiler?

File: RELEASE_NOTES.md [hunk 2]
```diff
@@ -1,7 +1,8 @@
 # Upcoming
 
-- fix: Miscompilation due to incorrect parenthesization in C# output for casts. (#1908)
+- fix: Miscompilation due to incorrect parenthesization in C# output for casts. (https://github.com/dafny-lang/dafny/pull/1908)
```
Comment (cpitclaudel) [inline RELEASE_NOTES.md:3]: Why do you add the full link?

**Review by cpitclaudel — CHANGES_REQUESTED** [review]
I don't think this is the right fix: we should make sure that the compiler is properly instantiated.

File: Source/Dafny/AST/DafnyAst.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/Dafny/AST/DafnyAst.cs:4320]: I don't think the AST is the right place to instantiate a compiler anyway, it should be instantiated in the options if really instantiated manually. I we don't want the compiler to be null, I think we should always instantiate a default C# compiler. Would you prefer that?

File: RELEASE_NOTES.md (hunk 2 above)
Comment (MikaelMayer) [reply RELEASE_NOTES.md:3]: So that it's browsable when reading the README.md from a text editor, and in Github markdown it still displays nicely "#1908"

File: Source/Dafny/DafnyOptions.cs [hunk 3]
```diff
@@ -27,6 +27,7 @@ public DafnyOptions()
       Prune = true;
       NormalizeNames = true;
       EmitDebugInformation = false;
+      Compiler = new CsharpCompiler();
```
Comment (cpitclaudel) [inline Source/Dafny/DafnyOptions.cs:30]: Won't that break the .compileTarget flag?

**Comment by cpitclaudel** [comment]
Could you have a look?  I don't think defaulting to the C# compiler is the right fix.  https://github.com/dafny-lang/dafny/pull/1945

**Review by cpitclaudel — APPROVED** [review]

**Comment by cpitclaudel** [comment]
Can you fix the conflicts in RELEASE_NOTES?
