### PR TITLE
Fix: Added missing check to prevent crash during resolution

### LINKED ISSUE #2111: Assertion failure in ResolveDotSuffix
Input:

```dafny
datatype DT = C(s: string) {
  predicate F() {
    C.XYZ()
  }
}
```

Output:

```
StrTree_AssertionFailure.dfy(3,4): Error: wrong number of arguments (datatype constructor 'C' expects 1, got 0)
Process terminated. Assertion failed.
   at Microsoft.Dafny.Expression.get_Resolved() in C:\dafny\Source\Dafny\AST\DafnyAst.cs:line 9068
   at Microsoft.Dafny.Resolver.ResolveDotSuffix(ExprDotName expr, Boolean isLastNameSegment, List`1 args, ResolveOpts opts, Boolean allowMethodCall) in C:\dafny\Source\Dafny\Resolver.cs:line 16328
   at Microsoft.Dafny.Resolver.ResolveApplySuffix(ApplySuffix e, ResolveOpts opts, Boolean allowMethodCall) in C:\dafny\Source\Dafny\Resolver.cs:line 16695
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 14745
   at Microsoft.Dafny.Resolver.ResolveFunction(Function f) in C:\dafny\Source\Dafny\Resolver.cs:line 10196
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in C:\dafny\Source\Dafny\Resolver.cs:line 9593
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 2815
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 1032
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in C:\dafny\Source\Dafny\Resolver.cs:line 507
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in C:\dafny\Source\Dafny\DafnyMain.cs:line 162
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in C:\dafny\Source\Dafny\DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 249
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 67
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0() in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 47
   at System.Threading.Thread.StartCallback()
```

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #2111
Basically, after the error on the expr.Lhs was reported, we tried to access the `.Resolved` property, which threw an exception because of failed contracts.
So I added the test to verify that `.WasResolved()` before, so that we don't continue if the LHS is not resolved.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Resolver.cs [hunk 1]
```diff
@@ -16595,6 +16595,9 @@ public ResolutionContext(ICodeContext codeContext, bool isTwoState)
       MemberDecl member = null;
 
       var name = resolutionContext.InReveal ? "reveal_" + expr.SuffixName : expr.SuffixName;
+      if (!expr.Lhs.WasResolved()) {
+        return null;
+      }
       var lhs = expr.Lhs.Resolved;
       if (lhs != null && lhs.Type is Resolver_IdentifierExpr.ResolverType_Module) {
```
Comment (cpitclaudel) [inline Source/DafnyCore/Resolver.cs:16602]: I don't understand this part; it looks like we're already checking for `null`; if that's not enough, shouldn't we remove this null check now that you have the early exit?

**Review by cpitclaudel — CHANGES_REQUESTED** [review]

File: Source/DafnyCore/Resolver.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/DafnyCore/Resolver.cs:16602]: `WasResolved()` on expressions is only equivalent to the type not being `null`.
However, `.Resolved` will still return `null` even if `.WasResolved()` is true, if the underlying expression is e.g. not a `ConcreteSyntaxExpression` (so it has nothing to "resolve"). it's just that `.WasResolved()` is part of the _requires_ of `.Resolved`.

Comment (cpitclaudel) [reply Source/DafnyCore/Resolver.cs:16602]: Got it, thanks!  And why do we do the check here instead of just after resolving the LHS a few lines above?

**Review by cpitclaudel — APPROVED** [review]
Approved, feel free to decide whether to take the feedback about the location of the fix

File: Source/DafnyCore/Resolver.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/DafnyCore/Resolver.cs:16602]: I think it's better to do the check just before when we need it for sure - e.g. if this code is copy-pasted at some point, this check won't be missed - but I acknowledge it could be subject to debate.
