### PR TITLE
fix: Remove unsound where clauses

### LINKED ISSUE #1619: Too much assumed about temporary or unassigned variables
The following program verifies and compiles, but crashes at run time:

``` dafny
predicate method {:opaque} P<W>(w: W) {
  true
}

method M<W>(s: seq<W>) returns (ghost r: W)
{
  var b := exists w: W :: P(w);
  ghost var w: W :| b ==> P(w); // BOGUS: this should be flagged as an error, because the type W may be empty
  if s != [] {
    var cand: W := GimmieOne(s);
  }
  return w;
}

method GimmieOne<W>(s: seq<W>) returns (c: W)
  requires s != []
{
  return s[0];
}

type Empty = x: int | false witness *

method Main() {
  var w := M<Empty>([]); // it's impossible for w to have a value, so the verifier (correctly) assumes false here
  var x := 3 / 0;
}
```

```
$ dafny /compile:3 test.dfy

Dafny program verifier finished with 3 verified, 0 errors
Running...

Error: Execution resulted in exception: Exception has been thrown by the target of an invocation.
System.DivideByZeroException: Attempted to divide by zero.
   at System.Numerics.BigInteger.op_Division(BigInteger dividend, BigInteger divisor)
   at System.Numerics.BigInteger.Divide(BigInteger dividend, BigInteger divisor)
   at Dafny.Helpers.EuclideanDivision(BigInteger a, BigInteger b)
   at _module.__default._Main()
   at Dafny.Helpers.WithHaltHandling(Action action)
   at __CallToMain.Main(String[] args)
```

## Diagnosis

The problem has to do with `where`-clause assumptions that are generated for variables. Here's some context.

The verifier translates a local variable `x` of a type `X` into a similar local variable in Boogie. If `BX` is the Boogie type that includes all Dafny-`X` values, then the Boogie declaration looks something like this:

    var x: BX;

The Boogie type `BX` may be bigger than the Dafny type `X`, so the verifier adds the more precise information using assumptions. Boogie's `where` clauses give a convenient place to hang such an assumption. So, in the typical case, the Boogie declaration of `x` looks something like:

    var x: BX where $Is(x, X);

This is fine as long as long as `X` denotes a nonempty type.

If `X` denotes a possibly empty type, then Dafny puts into effect a definite-assignment rule. This rule, which is enforced by the verifier, checks that any use of the variable `x` is preceded by an assignment to `x`. For the sake of soundness, the verifier must arrange that `$Is(x, X)` does not get assumed until after `x` has been assigned. This is done by emitting a second Boogie variable, named `defass$x`. This variable is set to `true` when `x` is assigned. So, in the case that `X` denotes a possibly empty type, the declarations generated are:

    var defass$x: bool;
    var x: BX where defass$x ==> $Is(x, X);

So far, all good. The Dafny verifier incorporates this design. But there are two places where an incorrect `where` clause is generated.

One place is for temporary variables. In particular, for a Dafny call `x := MyMethod();`, the verifier generates

    rhs$0 := MyMethod();
    x := rhs$0;
    defass$x := true;  // (this line is included only if X is a possibly empty type)

and for a simultaneous assignment `x, y := E, F;`, the verifier generates

    rhs$0 := E;
    rhs$1 := F;
    x := rhs$0;
    y := rhs$0;
    defass$x := true;  // (this line is included only if X is a possibly empty type)
    defass$y := true;  // (this line is included only if the type of y is a possibly empty type)

The problem is that the temporary variable `rhs$0` (and similar for `rhs$1`) is currently declared with a `where` clause:

    var rhs$0: BX where $Is(rhs$0, X)`;

A temporary variable does not need a `where` clause. (And even if it did have one, it would need to replicate the definite-assignment mechanism. But it doesn't need a `where` clause at all.) So, this is one problem that should be fixed.

The other place where an incorrect `where` clause is generated is when the Dafny program declares and immediately assigns a variable, like `var x := E;`. In this case, every Dafny use of the variable `x` will be after `x` has been assigned, so there seems to be no reason to bring in the `defass$x` mechanism. Wrong! While the Dafny part of the argument I made is correct, the Boogie `where` clause will be available even before the Dafny initialization `x := E;` has happened. The verifier gets this wrong. It should apply this optimization only for nonempty types.

PS. If the Dafny statement `var cand: W := GimmieOne(s);` in the program above is broken up into a declaration `var cand: W;` and an assignment `cand := GimmieOne(s);`, then one runs into a bug in the compiler. That bug has already been reported in https://github.com/dafny-lang/dafny/issues/1553.

### PR DESCRIPTION
**Pull request by RustanLeino**
Fixes #1619 

The fix is as described in Issue #1619, except that `where` clauses of simultaneous-assignment `$rhs` temporaries _do_ get `where` clauses when assigned `*` _provided_ the type is known to be nonempty.

### CODE REVIEW

File: Source/Dafny/Verifier/Translator.cs [hunk 1]
```diff
@@ -11738,7 +11738,12 @@ public ForceCheckToken(IToken tok)
         Type localType = rhsTypeConstraint;  // this is a type that is appropriate for capturing the value of the RHS
         var ty = TrType(localType);
         var nm = CurrentIdGenerator.FreshId("$rhs#");
-        Bpl.Expr wh = GetWhereClause(tok, new Bpl.IdentifierExpr(tok, nm, ty), localType, etran, NOALLOC);
+        Bpl.Expr wh;
+        if (rhs is HavocRhs && localType.IsNonempty) {
```
[the remark this answers is not in the document]
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.cs:11742]: I argued in the issue #1619 that such temporary variables never need a `where` clause. I was thinking that such a temporary (call it `$rhs`) always gets used in the following way in the Boogie code:

```
$rhs := ...;
...
lhs := $rhs;
```

In this case, there is no reason for `$rhs` to have a `where` clause. However, I had then forgotten that for a Dafny assignment `lhs := *;` (that is, assigning an arbitrary value of the left-hand side), the generated Boogie is

```
havoc $rhs;
...
lhs := $rhs;
```

To assume the type information, one can then either follow the `havoc` with an `assume` statement or add the type information in the `where` clause of `$rhs`. But there's one more snag: if the type is possibly empty, then the `lhs := *;` assignment does not count in Dafny's definite-assignment rules. That's why it's still necessary to check `localType.IsNonempty`.

File: Source/Dafny/Verifier/Translator.TrStatement.cs [hunk 2]
```diff
@@ -844,6 +844,10 @@ public partial class Translator {
               needDefiniteAssignmentTracking = true;
             }
           }
+          if (!local.Type.IsNonempty) {
+            // This prevents generating an unsatisfiable where clause for possibly empty types
```
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/Dafny/Verifier/Translator.TrStatement.cs:848]: Thanks.

I'm still a little confused about empty types. If the type doesn't have values, and `GimmieOne` return a value of this type, then I'd expect an error in `GimmieOne`.

Should
```
method GimmieOne<W>(s: seq<W>) returns (c: W)
  requires s != []
{
  return s[0];
}
```
even pass the resolver? Why doesn't it require `W(00)` ?

File: Source/Dafny/Verifier/Translator.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/Dafny/Verifier/Translator.cs:11742]: > But there's one more snag: if the type is possibly empty, then the lhs := *; assignment does not count in Dafny's definite-assignment rules.

Can you link to the relevant code?

**Review by keyboardDrummer — DISMISSED** [review]

File: Source/Dafny/Verifier/Translator.TrStatement.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.TrStatement.cs:848]: You are absolutely correct that `GimmieOne`'s precondition can be satisfied only if `W` is a nonempty type, and likewise the `if s != []` branch can be taken only if `W` is a nonempty type.

The statement `w: W :| b ==> P(w);` incurs a proof obligation `exists w: W :: b ==> P(w)`. At first, you might think this proof obligation holds trivially if `b` is `false`, but one still needs to prove `exists w: W`. So, this existential quantifier is not provable for an empty type. Therefore, the verifier _should_ give an error for this assignment.

Any statement that comes _after_ the `w :| ...` statement should not have any effect on whether or not you get an error for the `w :| ...` statement. Therefore, an error should be reported for the `w :| ...` statement whether or not the `if` statement is included in the method. But the previous unsoundness was that the `if` statement _did_ cause a change.

How did the presence of the `if ... { var cand := ...; }` statement cause the verifier not to flag `w :| ...` as an error? Previously (before this PR), the Boogie generated for method `M` looked something like this (where I'm omitting many irrelevant details):

```
procedure M(W: Ty, s: Seq Box where ...) returns (defass$r: bool, r: Box where defass$r ==> $Is(r, W))
{
  var b: bool;
  var defass$w: bool;
  var w: Box where defass$w ==> $Is(w, W);
  var $rhs: Box where $Is($rhs, W);
  var cand: Box where $Is($rhs, W);

  b := exists w: Box :: $Is(w, W) && P(w);

  assert exists w: Box :: $Is(w, W) && (b ==> P(w));
  havoc w;
  assume b ==> P(w);
  defass$w := true;

  if s != [] {
    call $rhs := GimmieOne(s);
    cand := $rhs;
  }

  assert defass$w; // check that w has been defined
  r := w;
  defass$r := true;
  assert defass$r; // check that r has been defined before returning
  return;
}
```

Note that out-parameter `r` and local variable `w` have `where` clauses that are guarded by `defass$r` and `defass$w` (respectively), which are set to `true` when `r` and `w` are known to contain a value that satisfies `$Is(_, W)`. Note also that local variables `$rhs` and `cand` (which come about because of the `if` statement downstream of the `w :| ...` assignment) have `where` clauses that are _not_ guarded by a `defass$` variable. Boogie assumes all `where` clauses of in- and out-parameters and local variables on entry to the procedure body (and in all places where Boogie gets to assign an arbitrary value to these variables; see Boogie reference manual for details). So, because of the `where` clauses of `$rhs` and `cand`, Boogie can assume the existence of a value that satisfies `$Is(_, W)`. This is why Boogie can prove the `assert` above when the Dafny program included the `if ... { var cand := ...; }` statement.

To fix the unsoundness, I did two things.

First, I removed the `where` clause of `$rhs` altogether (except in some cases when `$rhs` was used in the translation of Dafny's `... := *;` assignments, as I described in other comments on this PR). But even if you remove the `where` clause of `$rhs` in my Boogie sketch above, there's still a problem with the `where` clause for `cand`. How come `cand` has a bad `where` clause?

A variable `y` whose type is a possibly empty type (and also a non-ghost variable `y` whose type is not an auto-init type) is subject to definite-assignment rules. The verifier enforces definite-assignment rules using `defass$` variables, as I sketched above. Previously, the verifier implemented an "optimization": a variable declaration with an initial value, like `var y := E;`, was deemed to be "trivially definitely-assigned", and thus the `defass$` machinery was omitted. But this is wrong, because the Boogie program gets to see the `where` clause _before_ the initializing assignment happens (as you can see in the Boogie program above).

So, the second thing I did to fix the unsoundness was to not do this "optimization" for possibly empty types.

After my PR, the Boogie translation of the same method is:

```
procedure M(W: Ty, s: Seq Box where ...) returns (defass$r: bool, r: Box where defass$r ==> $Is(r, W))
{
  var b: bool;
  var defass$w: bool;
  var w: Box where defass$w ==> $Is(w, W);
  var $rhs: Box; // no where clause
  var cand: Box; // no where clause

  // ... same as in the procedure above ...
}
```

File: Source/Dafny/Verifier/Translator.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.cs:11742]: You mean the code in Translator? Essentially, this means that `lhs := *;` does _not_ do a `defass$lhs := true;` assignment. In particular, `lhs := *;` translates to

```
havoc lhs;
```

and not to

```
defass$lhs := true;
havoc lhs;
```

(and similarly for multi-assignments, via a `$rhs` temporary).

Since this is (correctly) _not_ done, I have no code to point to in Translator.

There are tests for this in the new `git-issue-1619.dfy`, near the end. For example,

``` dafny
method G0() {
  var m: MaybeEmpty, other: int := *, *;
  assume G(m); // error: use before definition
```

File: Source/Dafny/Verifier/Translator.TrStatement.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (keyboardDrummer) [reply Source/Dafny/Verifier/Translator.TrStatement.cs:848]: I see, I didn't realise that the where clauses create assume statements. I wasn't actually sure what they did and assumed they translated to assertions.

Is it a good idea to use where clauses to begin with? If you do a call, then the return type of the callee can add an implicit ensures statement, which translates into an assume on the call site, and if you do a havoc, it makes sense to do an assume on the type afterwards, so then what are the remaining use-cases for where clauses?

File: Source/Dafny/Verifier/Translator.cs [hunk 3]
```diff
@@ -9744,7 +9744,12 @@ public ForceCheckToken(IToken tok)
...
+          wh = GetWhereClause(tok, new Bpl.IdentifierExpr(tok, nm, ty), localType, etran, NOALLOC);
+        } else {
+          wh = null;
```
Comment (keyboardDrummer) [inline Source/Dafny/Verifier/Translator.cs:9751]: Could you add a comment to the else branch to explain why the where is not needed. If I understand correctly, because the variable is short lived, we know it will not be havoc'ed by Boogie, so a where wouldn't provide additional information over the assigned value.

Btw, are we not possibly missing information for possibly empty types, by leaving out the where? I know putting in the where is unsound, but won't leaving it out be confusing for developers? Would it be an option not to allow havoc'ing a possibly empty type? If doing this havoc leaves you with a variable that is unusable unless you assign to it again, why allow it?

File: Test/dafny1/SchorrWaite.dfy [hunk 4]
```diff
@@ -227,7 +227,7 @@ class Main {
       invariant forall k :: 0 < k < |stackNodes| ==>
                   stackNodes[k].children[stackNodes[k].childrenVisited] == stackNodes[k-1]
       // the original values of m.children[m.childrenVisited] for m's on the stack:
-      invariant forall k :: 0 <= k && k+1 < |stackNodes| ==>
+      invariant forall k {:matchinglooprewrite false} :: 0 <= k && k+1 < |stackNodes| ==>
```
Comment (keyboardDrummer) [inline Test/dafny1/SchorrWaite.dfy:230]: A change was made to SchorrWaite.dfy in master so it verifies faster, so maybe this change is no longer necessary.

**Review by keyboardDrummer — APPROVED** [review]

File: Source/Dafny/Verifier/Translator.TrStatement.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.TrStatement.cs:848]: Added comment.

File: Source/Dafny/Verifier/Translator.cs (hunk 3 above)
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.cs:9751]: Comment added.

I'm looking into one case (that's not likely to ever occur) where the PR so far provides too little information for empty types.

File: Test/dafny1/SchorrWaite.dfy (hunk 4 above)
Comment (RustanLeino) [reply Test/dafny1/SchorrWaite.dfy]: I fixed up `SchorrWaite.dfy` by using the loop invariants from `SchorrWaite-stages.dfy` (in the order given throughout the refinement modules in that file).

File: Source/Dafny/Verifier/Translator.cs (hunk 3 above)
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.cs:9789]: I fixed up the remaining case. We are no longer providing too little information for possibly empty types. In particular, when temporary `rhs` variable is used for an assignment of `*`, then that `rhs` variable gets a Boogie `where` clause whose antecedent is the definite-assignment tracker of the variable being assigned. For example, if the Dafny program defines a variable `p` of a possibly empty type, then the assignment

``` dafny
x, p := E, *;
```

is translated into Boogie as:

```
var x: ...;
var defass#p: bool;
var p: P where defass#p ==> W(p); // for some type P and expression W(p)
var rhs0: ...;
var rhs1: P where defass#p ==> W(rhs1); // note, the use of defass#p here
...
rhs0 := E;
havoc rhs1;
x := rhs0;
p := rhs1;
```

Comment (keyboardDrummer) [reply Source/Dafny/Verifier/Translator.cs:9789]: What does it matter that you've added `where defass#p ==> W(rhs1)` ? That could only effect visible variables after `p := rhs1` right? But given that we also have `where defass#p ==> W(p)`, shouldn't that provide no additional information?

File: Source/Dafny/Verifier/Translator.cs [hunk 5]
```diff
@@ -9747,7 +9773,19 @@ public ForceCheckToken(IToken tok)
         Bpl.Expr wh;
         if (rhs is HavocRhs && localType.IsNonempty) {
           wh = GetWhereClause(tok, new Bpl.IdentifierExpr(tok, nm, ty), localType, etran, NOALLOC);
+        } else if (rhs is HavocRhs && lhsVar != null && GetDefiniteAssignmentTracker(lhsVar) != null) {
+          // This "where" clause expresses that the new variable has a value of the given type only if
+          // the variable has already been definitely assigned. (If it has not already been assigned,
+          // then the variable will get a new value, but Dafny's definite-assginment rules prevent that
+          // value from being used, so it's appropriate to use effectively-"true" as the "where" clause
+          // in that case.
+          wh = GetWhereClause(tok, new Bpl.IdentifierExpr(tok, nm, ty), localType, etran, NOALLOC);
```
Comment (keyboardDrummer) [inline Source/Dafny/Verifier/Translator.cs:9782]: Instead of temporarily assigning `wh` like you do here does not improve readability, I would prefer either
```
wh = BplImp(GetDefiniteAssignmentTracker(lhsVar), 
  GetWhereClause(tok, new Bpl.IdentifierExpr(tok, nm, ty), localType, etran, NOALLOC));
```

or 
```
var consequent = GetWhereClause(tok, new Bpl.IdentifierExpr(tok, nm, ty), localType, etran, NOALLOC);
wh = BplImp(GetDefiniteAssignmentTracker(lhsVar), consequent);
```

**Review by keyboardDrummer — APPROVED** [review]

File: Source/Dafny/Verifier/Translator.cs (hunk 5 above)
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.cs]: Done

**Review by keyboardDrummer — APPROVED** [review]

File: Source/Dafny/Verifier/Translator.cs (hunk 3 above)
Comment (RustanLeino) [reply Source/Dafny/Verifier/Translator.cs:9789]: If `defass#p` is already `true` at the time of the `havoc rhs1`, then this new `where` clause will have the effect of assuming `W(rhs1)`. This let the verifier prove the last `assert` statement in method `HavocMultipleVar` of `git-issue-1619.dfy`. In my original PR, that assertion did not verify -- which your comment about us possibly "not providing too little information" led me to realize.

Comment (keyboardDrummer) [reply Source/Dafny/Verifier/Translator.cs:9789]: I see, thanks :)
