### PR TITLE
Fix: Other CLI files that are not found do not trigger exceptions

### LINKED ISSUE #2719: Passing a DLL path that doesn't exist raises an exception
`dafny foobar.dfy` gives you a relatively clean `Unable to open included file` error, but `dafny foobar.dll` leads to a `FileNotFoundException` (because it tries to extract the `DafnySourceAttribute` text if it exists, without handling this case).

```dafny
method Test() {}
```

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #2719
I added the corresponding test.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyDriver/DafnyDriver.cs [hunk 1]
```diff
@@ -259,7 +259,14 @@ public enum CommandLineArgumentsResult {
 
         var supportedExtensions = options.Compiler.SupportedExtensions;
         if (supportedExtensions.Contains(extension)) {
-          otherFiles.Add(file);
+          // .h files are not part of the build, they are just emitted as includes
+          if (File.Exists(file) || extension == ".h") {
+            otherFiles.Add(file);
+          } else {
+            options.Printer.ErrorWriteLine(Console.Out,
+              "*** Error: file " + file + " not found");
```
Comment (fabiomadge) [inline Source/DafnyDriver/DafnyDriver.cs]:
```suggestion
            options.Printer.ErrorWriteLine(Console.Out, $"*** Error: file {file} not found");
```

**Review by fabiomadge — APPROVED** [review]
