### PR TITLE
Fix: Shadowing of output variables in methods in Dafny-to-Rust

### LINKED ISSUE #6261: Bad Rust code generated when local variable shares name with return variable.
### Dafny version

4.10 and also HEAD of master

### Code to produce this issue

```dafny
https://github.com/aws/aws-database-encryption-sdk-dynamodb/
```

### Command to run and resulting output

```code
clone https://github.com/aws/aws-database-encryption-sdk-dynamodb/
cd DynamoDbEncryption
make polymorph_rust transpile_rust test_rust
note that test_rust successfully compiles

Edit the file dafny/DynamoDbEncryption/src/FilterExpr.dfy
In the definition of apply_function on line 1267 (or so) change
returns (result : Result<StackValue, Error>)
to
returns (ret : Result<StackValue, Error>)

make transpile_rust test_rust
note that test_rust does not compile, even though it should, and in fact does in all the other languages.

It seems that code on 1274 that starts
var ret :- 
confuses Dafny, in that the variable has the same name as the return variable
```

### What happened?

Generated rust code does not compile.
I expected it to compile, or at a minimum Dafny should have complained at transpilation time.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #6261 

The root cause of the bug was that shadowed variables are never accessible in Dafny anymore except for one case: Output variables, through the return statement.
Indeed, a return statement with an expression assigns the result of the expression to the (unique) output variable, and then returns. Even in the presence of shadowing when another local variable overrides the output variable, the (outer) output variable is correctly assigned in the compiler.
I had not considered this case when considering enabling shadowing.

### What was changed?
- Whether a variable's name results in the shadowable name instead of the unique name is now more constrained: it requires that the variable name is different from any output variables.

### How has this been tested?
- Two tests, including one with a structure close to #6261 with the elephant operator, were failing before this PR and now are passing.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Backends/Dafny/DafnyCodeGenerator.cs [hunk 1]
```diff
@@ -56,7 +56,9 @@ public DafnyCodeGenerator(DafnyOptions options, ErrorReporter reporter, string i
     }
 
     protected override string GetCompileNameNotProtected(IVariable v) {
-      return preventShadowing ? v.GetOrCreateCompileName(currentIdGenerator) : v.CompileNameShadowable;
+      var canShadow = !preventShadowing &&
+                      !(enclosingMethod != null && enclosingMethod.Outs.Any(outVar => outVar.Name == v.Name));
+      return canShadow ? v.CompileNameShadowable : v.GetOrCreateCompileName(currentIdGenerator);
```
Comment (ssomayyajula) [inline Source/DafnyCore/Backends/Dafny/DafnyCodeGenerator.cs:61]: Is it acceptable to shadow a name declared in the body of the enclosing method, not necessarily among the out-parameters?

Comment (MikaelMayer) [reply Source/DafnyCore/Backends/Dafny/DafnyCodeGenerator.cs:61]: Good question. Yes, because there is no way in Dafny to refer to outer variables, so there won't be an ambiguity in the generated code.
