### PR TITLE
Fix: Proper warning that 'new' cannot be used in expressions, instead of a parse error

### LINKED ISSUE #3366: Parse failure on `Some(new C<nat>(0))`
### Dafny version

3.10.0

### Code to produce this issue

```dafny
class C<T> {
    constructor (x: T) {}
  }

  datatype O<T> = Some(x: T) | None

  method main() {
    // works
    var v := new C<nat>(0);
    var c := Some(v);

    // fails when inlining v
    var c2 := Some(new C<nat>(0));
  }
```

### Command to run and resulting output

```code
`dafny bug.dfy`
```

### What happened?

Getting a parse error when inlining `v`, in the line defining `c2`.

```
bug.dfy(13,19): Error: closeparen expected
1 parse errors detected in bug.dfy
```

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #3366
It does not remove the parse error as it was expected, but it does add an explanation of it.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/XUnitExtensions/Lit/ExitCommand.cs [hunk 1]
```diff
@@ -14,7 +14,7 @@ public class ExitCommand : ILitCommand {
 
   public (int, string, string) Execute(ITestOutputHelper? outputHelper, TextReader? inputReader, TextWriter? outputWriter, TextWriter? errorWriter) {
     var (exitCode, output, error) = operand.Execute(outputHelper, inputReader, outputWriter, errorWriter);
-    return (exitCode != expectedExitCode ? 1 : 0, output, error);
+    return (exitCode != expectedExitCode ? 1 : 0, output, error + $"\nMoreover the expected exit code was {expectedExitCode} but got {exitCode}");
```
Comment (MikaelMayer) [inline Source/XUnitExtensions/Lit/ExitCommand.cs:17]: This is manually tested and was useful to understand why my original tests with %exits-with 1 was failing without indication about what was wrong.

**Review by alex-chew — APPROVED** [review]
LGTM
