### PR TITLE
Prevent incorrect internal error message

### LINKED ISSUE #5295: Error: Dafny encountered an internal error while waiting for this symbol to verify.
### Dafny version

4.6.0

### Code to produce this issue

I'm hitting in a reproducible error in a github action for my project.
I'm pretty new to dafny so I expect the real cause is that I'm doing something silly, but presumably it shouldn't be giving this error despite that.
Sorry for not creating a minimal example to show what the problem is.  Feel free to ignore this issue.  I'm mostly just submitting the issue because the error message told me too :).

https://github.com/benreynwar/SiLemma/actions/runs/8546419158/job/23416730258

The error message is:

```
Utils/SetExt.dfy(27,39):
Utils/SetExt.dfy(27,39): Error: Dafny encountered an internal error while waiting for this symbol to verify. Please report it at <https://github.com/dafny-lang/dafny/issues>.
 
   |
27 |     lemma {:vcs_split_on_every_assert} ThereIsAMinimum<T(!new)>(s: set<T>, R: (T, T)->bool)
   |                                        ^^^^^^^^^^^^^^^
Dafny program verifier finished with 105 verified, 0 errors
: Dafny encountered an internal error while waiting for this symbol to verify. Please report it at <https://github.com/dafny-lang/dafny/issues>.
 
   |
27 |     lemma {:vcs_split_on_every_assert} ThereIsAMinimum<T(!new)>(s: set<T>, R: (T, T)->bool)
   |                                        ^^^^^^^^^^^^^^^
Dafny program verifier finished with 105 verified, 0 errors
```

### Command to run and resulting output

```
https://github.com/benreynwar/SiLemma/actions/runs/8546419158/job/23416730258
```

### What happened?

```
Utils/SetExt.dfy(27,39): Error: Dafny encountered an internal error while waiting for this symbol to verify. Please report it at <https://github.com/dafny-lang/dafny/issues>.
 
   |
27 |     lemma {:vcs_split_on_every_assert} ThereIsAMinimum<T(!new)>(s: set<T>, R: (T, T)->bool)
   |                                        ^^^^^^^^^^^^^^^
Dafny program verifier finished with 105 verified, 0 errors
```

### What type of operating system are you experiencing the problem on?

Linux

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Fixes https://github.com/dafny-lang/dafny/issues/5209
Fixes #5295

### Description
- When mentioning an internal error due to verification timing out, throw an exception, so no successful verification message is emitted.
- Wait longer before concluding the Boogie back-end is ignoring the verification timeout.
- Update MultiBackendTest so it allows overriding default options.

### How has this been tested?
Manually made code edits to simulate Boogie not returning, resulting in:

```
Exit code is 134 (Unhandled exception. System.Exception: Dafny encountered an internal error while waiting for C._ctor to verify.
   at DafnyDriver.Commands.CliCompilation.VerifyAllLazily(Nullable`1 randomSeed)+MoveNext() in /Users/rwillems/SourceCode/dafny/Source/DafnyDriver/CliCompilation.cs:line 253
   at DafnyDriver.Commands.CliCompilation.VerifyAllLazily(Nullable`1 randomSeed)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
```

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyDriver/CliCompilation.cs [hunk 1]
```diff
@@ -22,15 +22,18 @@ namespace DafnyDriver.Commands;
 public record CanVerifyResult(ICanVerify CanVerify, IReadOnlyList<VerificationTaskResult> Results);
 
 public class CliCompilation {
+  private readonly ILogger<CliCompilation> logger;
```
Comment (atomb) [inline Source/DafnyDriver/CliCompilation.cs:25]: This looks like it's never used. Am I missing something?

Comment (keyboardDrummer) [reply Source/DafnyDriver/CliCompilation.cs]: Unused indeed. Usage only occurred in a previous commit. Removed it.

**Review by atomb — APPROVED** [review]
Looks good!
