### PR TITLE
Fix: Duplicate declarations caused by resolver do not crash the language server anymore

### LINKED ISSUE #3155: Another "item with the same key has already been added" instance
### Dafny version

3.9.1 (and 35a047871ef6)

### Code to produce this issue

Load [this file](https://github.com/dafny-lang/compiler-bootstrap/blob/main/src/AST/Translator.Entity.dfy) in the IDE.

### Command to run and resulting output

In the "Dafny Language Server" log pane, you'll see something like:

```code
[Error - 1:21:29 PM] Request textDocument/codeAction failed.
  Message: Internal Error - System.ArgumentException: An item with the same key has already been added. Key: Microsoft.Dafny.DatatypeUpdateExpr
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.Dafny.LanguageServer.Workspace.SymbolTable..ctor(Document document, IReadOnlyList`1 usages)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.CreateFrom(Program program, Document document, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadInternal(DocumentTextBuffer textDocument, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.<>c__DisplayClass12_0.<<LoadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadAsync(DocumentTextBuffer textDocument, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.ResolveAsync()
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentManager.GetLastDocumentAsync()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

### What happened?

This is the same exception as in #1790, #2951, and #3105, but thrown from a different location, so I don't think it's the same issue.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
This PR fixes #3155
The construction of the symbol table was requiring that every recorded usage of a symbol appears only once. However, since we are traversing a resolved tree, some symbols might be used several times at the same place, for example:

```dafny
datatype Test =
    | A(field: int)
    | B(field: int)


predicate updateTest(test: Test, test': Test)
{
    test' == test.(field := 1)
}
```

where `test.(field := 1)` is resolved into

```dafny
match test {
  case A(field) => A(field := 1)
  case B(field) => B(field := 1)
}
``` 

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Review by atomb — DISMISSED** [review]
I think this looks good, based on my understanding that these duplicate declarations would need to be identical and so it's okay to just keep one of them. Am I thinking about that correctly?

File: Source/DafnyLanguageServer/Workspace/SymbolTable.cs [hunk 1]
```diff
@@ -21,7 +21,12 @@ public class SymbolTable {
 
   public SymbolTable(Document document, IReadOnlyList<(IDeclarationOrUsage usage, IDeclarationOrUsage declaration)> usages) {
     var safeUsages = usages.Where(k => k.declaration.NameToken.Filename != null).ToList();
-    Declarations = safeUsages.ToDictionary(k => k.usage, k => k.declaration);
+    Declarations = new();
+    // We don't use ToDictionary because we are currently traversing the resolved tree, which
```
Comment (keyboardDrummer) [inline Source/DafnyLanguageServer/Workspace/SymbolTable.cs:25]: I would prefer
```Declarations = safeUsages.DistinctBy(k => k.usage).ToDictionary(k => k.usage, k => k.declaration);```

**Comment by keyboardDrummer** [comment]
Thanks a lot for fixing this!

**Review by keyboardDrummer — APPROVED** [review]
