### PR TITLE
Add test and fix for issue 4004

### LINKED ISSUE #4004: Parallel assignment including match expression within match statement crash
### Dafny version

4.1.0

### Code to produce this issue

```dafny
method Main() returns ()
{
  match 8 {
    case _ => {
      var v_bool: bool, v_real: real := true, match 15.06 {
        case _ => 6.58
      };
      print v_bool, " ", v_real, "\n";
    }
  }
}
```

### Command to run and resulting output

```code
$ Dafny /compile:4 test.dfy
Process terminated. Assertion failed.
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1190
...
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
```

### What happened?

Found a weird crash issue where this program crashes, however splitting the parallel assignment into 2 individual assignments causes the program to compile and verify correctly. This may be related to #3966

<details>
  <summary>Full error message</summary>
Process terminated. Assertion failed.
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1190
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1178
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 238
   at Microsoft.Dafny.Translator.TrStmt_CheckWellformed(Expression expr, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran, Boolean subsumption, Boolean lValueContext) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 5348
   at Microsoft.Dafny.Translator.TrAssignmentRhs(IToken tok, IdentifierExpr bGivenLhs, IVariable lhsVar, Type lhsType, AssignmentRhs rhs, Type rhsTypeConstraint, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 8871
  at Microsoft.Dafny.Translator.ProcessUpdateAssignRhss(List`1 lhss, List`1 rhss, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 8529
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 238
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 486
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 7485
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 307
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 7485
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 307
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 433
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 7485
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 307
   at Microsoft.Dafny.Translator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 653
   at Microsoft.Dafny.Translator.AddMethod_Top(Method m, Boolean isByMethod, Boolean includeAllMethods) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 200
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 72
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 1236
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 806
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.cs:line 877
   at Microsoft.Dafny.DafnyDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext() in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyDriver/DafnyDriver.cs:line 596
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass16_0.<ProcessFilesAsync>b__0() in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyDriver/DafnyDriver.cs:line 424
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.CustomStackSizePoolTaskScheduler.WorkLoop()
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)

</details>

### What type of operating system are you experiencing the problem on?

Linux

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Fixes #4004

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Verifier/Translator.TrStatement.cs [hunk 1]
```diff
@@ -218,10 +218,9 @@ public partial class Translator {
           TrStmt(resolved[0], builder, locals, etran);
         } else {
           AddComment(builder, s, "update statement");
-          var lhss = new List<Expression>();
-          foreach (var lhs in s.Lhss) {
```
Comment (keyboardDrummer) [inline Source/DafnyCore/Verifier/Translator.TrStatement.cs:222]: `s.Lhss` and `s.Rhss` should no longer be accessed after resolution, since they are the unresolved children of `UpdateStmt`. Instead, `s.ResolvedStatements` should be used.

**Review by RustanLeino — APPROVED** [review]

**Comment by alex-usher** [comment]
Hi, I believe there are still some issues with nested match statements combined with parallel assignment - the following test case is crashing with a new assertion error, and it was previously crashing with the same error as #4004.
```dafny
datatype D2 = DC3

method Main() {
    var v1 := 1;
    var v2 := 2;
    match DC3 {
        case DC3 =>
            var v3 := 3;
            v1, v2 := v1 + 1, match DC3 {
                case DC3 => v2 + 1
            };
    }
}
```
```
Process terminated. Assertion failed.
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5272
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5079
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrRhs(AssignmentRhs rhs, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4110
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3039
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4631
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3371
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3350
...
```

**Comment by keyboardDrummer** [comment]
> Hi, I believe there are still some issues with nested match statements combined with parallel assignment - the following test case is crashing with a new assertion error, and it was previously crashing with the same error as #4004.

I don't have any error when I pass your latest example program to a Dafny build off of the master branch

**Comment by alex-usher** [comment]
Thanks for getting back to me! I've pulled master and I'm still experiencing the error both on Mac + Linux - I've tried with both Dotnet 6 & 7. Here's what I'm doing to reproduce it on Linux:
```
$ dotnet --version 
6.0.408
$ git clone  --recursive git@github.com:dafny-lang/dafny.git
$ cd dafny && git rev-parse HEAD
8c1d8ff20b3e5da68e743ea3f16f7961b319dda6
$ make z3-ubuntu && make
$ cd <test file dir>
$ dotnet ~/dafny/Binaries/Dafny.dll test.dfy

Dafny program verifier finished with 0 verified, 0 errors
Process terminated. Assertion failed.
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5272
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5079
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrRhs(AssignmentRhs rhs, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4110
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3039

...
```

Just wanted to make you aware of this - let me know if there's anything more I could do to help (e.g. provide debug info etc)

Thanks! Alex

**Comment by Dilan-s** [comment]
Hi @keyboardDrummer 

I agree @alex-usher on this, I am also getting the program detailed in his message to have an error.

I have also found the following program to crash:

```dafny
method Main() returns ()
{
  match (-19 / 23) {
    case 26 => {
      var v_bool_7: bool, v_bool_8: bool := (match true {
        case _ => true
      }), false;
    }
    case _ => {
    }
  }
}
```
```
Dafny /compile:4 test.dfy 

Dafny program verifier did not attempt verification
Process terminated. Assertion failed.
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5272
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5079
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrRhs(AssignmentRhs rhs, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4110
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3039
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3392
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4631
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3096
...
```
I have also checked, and both programs compiled and executed successfully before [3886](https://github.com/dafny-lang/dafny/pull/3886)

Dilan

**Comment by keyboardDrummer** [comment]
> Thanks for getting back to me! I've pulled master and I'm still experiencing the error both on Mac + Linux - I've tried with both Dotnet 6 & 7. Here's what I'm doing to reproduce it on Linux:
> 
> ```
> $ dotnet --version 
> 6.0.408
> $ git clone  --recursive git@github.com:dafny-lang/dafny.git
> $ cd dafny && git rev-parse HEAD
> 8c1d8ff20b3e5da68e743ea3f16f7961b319dda6
> $ make z3-ubuntu && make
> $ cd <test file dir>
> $ dotnet ~/dafny/Binaries/Dafny.dll test.dfy
> 
> Dafny program verifier finished with 0 verified, 0 errors
> Process terminated. Assertion failed.
>    at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5272
>    at Microsoft.Dafny.Compilers.SinglePassCompiler.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 5079
>    at Microsoft.Dafny.Compilers.SinglePassCompiler.TrRhs(AssignmentRhs rhs, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4110
>    at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in ~/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3039
> 
> ...
> ```
> 
> Just wanted to make you aware of this - let me know if there's anything more I could do to help (e.g. provide debug info etc)
> 
> Thanks! Alex

Got it now, thanks.

**Comment by alex-usher** [comment]
> Just to be sure, is the directory where you did `git clone` also your home directory (`~`), so `~/dafny/Binaries/Dafny.dll`

Yes, that's correct - sorry I left that out

**Comment by Dilan-s** [comment]
> PR for the rest of the fix: #4039

Yes I've tested this a bit and it seems to be working now.

Thank you!
