### PR TITLE
#731: Improved reasoning about member lookup in presence of type parameters

### LINKED ISSUE #731: .Length on generic arrays can cause a type error
This example

method Main() {
  var cb := new ClassB;
  print cb.y.Length, " ", cb.k.Length, " ", cb.l.Length, "\n";
}

trait Trait<Y> {
  const y: Y
  const k: Y := y
  const l: Y
}

class ClassB extends Trait<array<bv8>> { }

produces

git-issue-731.dfy(10,13): Error: type of the receiver is not fully determined at this program point
git-issue-731.dfy(10,31): Error: type of the receiver is not fully determined at this program point
git-issue-731.dfy(10,49): Error: type of the receiver is not fully determined at this program point
3 resolution/type errors detected in git-issue-731.dfy

### PR DESCRIPTION
**Pull request by davidcok**
Fixes #731.

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -12244,7 +12245,21 @@ class LazyString_OnTypeEquals
                   } else {
                     // pick the supertype "mbr.EnclosingClass" of "cl"
                     Contract.Assert(mbr.EnclosingClass is TraitDecl);  // a proper supertype of a ClassDecl must be a TraitDecl
-                    var proxyTypeArgs = mbr.EnclosingClass.TypeArgs.ConvertAll(_ => (Type)new InferredTypeProxy());
+                    var typeMapping = cl.ParentFormalTypeParametersToActuals;
+                    List<Type> proxyTypeArgs = null;
+                    foreach (Type tt in cl.ParentTraits) {
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:12250]: This will only iterate through the immediate parent traits. Don't you also want transitive parent traits? To do that, use `TraitAncestors()`.

File: Source/Dafny/Resolver.cs [hunk 2]
```diff
@@ -12244,7 +12245,21 @@ class LazyString_OnTypeEquals
...
+                      // If there is a match, the list of Type actuals is unique
+                      // (a class cannot inherit both Trait<T1> and Trait<T2> with T1 != T2).
+                      if (tt.AsTraitType == (TraitDecl) mbr.EnclosingClass) {
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:12253]:
```suggestion
                      if (tt.AsTraitType == (TraitDecl)mbr.EnclosingClass) {
```

File: Source/Dafny/Resolver.cs [hunk 3]
```diff
@@ -12244,7 +12245,21 @@ class LazyString_OnTypeEquals
...
+                         proxyTypeArgs = tt.TypeArgs.ConvertAll(t0 => SubstType(t0,typeMapping));
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:12254]:
```suggestion
                         proxyTypeArgs = tt.TypeArgs.ConvertAll(t0 => SubstType(t0, typeMapping));
```

File: Source/Dafny/Resolver.cs [hunk 4]
```diff
@@ -12244,7 +12245,21 @@ class LazyString_OnTypeEquals
...
+                      }
+                    }
+                    if (proxyTypeArgs == null) {
+                      proxyTypeArgs = mbr.EnclosingClass.TypeArgs.ConvertAll(t0 => (typeMapping.ContainsKey(t0) ? typeMapping[t0] : (Type)new InferredTypeProxy()) );
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:12258]:
```suggestion
                      proxyTypeArgs = mbr.EnclosingClass.TypeArgs.ConvertAll(t0 => typeMapping.ContainsKey(t0) ? typeMapping[t0] : (Type)new InferredTypeProxy());
```

File: Source/Dafny/Resolver.cs [hunk 5]
```diff
@@ -12244,7 +12245,21 @@ class LazyString_OnTypeEquals
...
+                    }
+                    var meetMapping = TypeSubstitutionMap(cl.TypeArgs, meet.TypeArgs);
+                    proxyTypeArgs = proxyTypeArgs.ConvertAll(t0 => SubstType(t0,meetMapping));
+                    proxyTypeArgs = proxyTypeArgs.ConvertAll(t0 => t0.AsTypeParameter == null ? t0 : (Type)new InferredTypeProxy() );
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:12262]:
```suggestion
                    proxyTypeArgs = proxyTypeArgs.ConvertAll(t0 => t0.AsTypeParameter == null ? t0 : (Type)new InferredTypeProxy());
```

File: Source/Dafny/Resolver.cs [hunk 6]
```diff
@@ -12244,7 +12245,21 @@ class LazyString_OnTypeEquals
...
+                      // (a class cannot inherit both Trait<T1> and Trait<T2> with T1 != T2).
+                      if (tt.AsTraitType == (TraitDecl) mbr.EnclosingClass) {
+                         proxyTypeArgs = tt.TypeArgs.ConvertAll(t0 => SubstType(t0,typeMapping));
+                      }
+                    }
+                    if (proxyTypeArgs == null) {
+                      proxyTypeArgs = mbr.EnclosingClass.TypeArgs.ConvertAll(t0 => (typeMapping.ContainsKey(t0) ? typeMapping[t0] : (Type)new InferredTypeProxy()) );
+                    }
+                    var meetMapping = TypeSubstitutionMap(cl.TypeArgs, meet.TypeArgs);
+                    proxyTypeArgs = proxyTypeArgs.ConvertAll(t0 => SubstType(t0,meetMapping));
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:12261]:
```suggestion
                    proxyTypeArgs = proxyTypeArgs.ConvertAll(t0 => SubstType(t0, meetMapping));
```

File: Test/dafny0/ResolutionErrors.dfy.expect [hunk 7]
```diff
@@ -43,8 +43,7 @@ ResolutionErrors.dfy(356,27): Error: arguments must have comparable types (got b
 ResolutionErrors.dfy(354,18): Error: arguments must have comparable types (got int and DTD_List)
 ResolutionErrors.dfy(355,18): Error: arguments must have comparable types (got DTD_List and int)
 ResolutionErrors.dfy(369,17): Error: ghost variables are allowed only in specification contexts
-ResolutionErrors.dfy(395,11): Error: RHS (of type int) not assignable to LHS (of type bool)
-ResolutionErrors.dfy(396,18): Error: arguments must have comparable types (got bool and int)
+ResolutionErrors.dfy(393,7): Error: incorrect type of method in-parameter 1 (expected GenericClass<int>, got GenericClass<bool>) (non-variant type parameter would require int = bool)
```
Comment (RustanLeino) [inline Test/dafny0/ResolutionErrors.dfy.expect:46]: Update the `// error` comments in ResolutionErrors.dfy to reflect these changes

File: Test/git-issues/git-issue-731.dfy [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+}
+
+class ClassB extends Trait<array<bv8>> { 
+  var m: array<bv8>
+  constructor () { m := new bv8[42]; }
+}
+
+class ClassC extends Trait<array3<bv8>> {
+  var m: array3<bv8>
+  constructor () { m := new bv8[8,9,10]; }
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-731.dfy:21]:
```suggestion
  constructor () { m := new bv8[8, 9, 10]; }
```

File: Test/git-issues/git-issue-731b.dfy [hunk 9]
```diff
@@ -0,0 +1,24 @@
+// RUN: %dafny /compile:0 "%s" > "%t"
+// RUN: %dafny /noVerify /compile:4 /compileTarget:cs "%s" >> "%t"
+// RUN: %dafny /noVerify /compile:4 /compileTarget:js "%s" >> "%t"
+// RUN: %dafny /noVerify /compile:4 /compileTarget:go "%s" >> "%t"
+// RUN: %dafny /noVerify /compile:4 /compileTarget:java "%s" >> "%t"
+// RUN: %diff "%s.expect" "%t"
+
+// Testing issue#731 when the class in question has type parameters
+
+trait Tr2<W,Y> {
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-731b.dfy:10]:
```suggestion
trait Tr2<W, Y> {
```

File: Test/git-issues/git-issue-731b.dfy [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+  const w: W;
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-731b.dfy:11]:
```suggestion
  const w: W
```

File: Test/git-issues/git-issue-731b.dfy [hunk 11]
```diff
@@ -0,0 +1,24 @@
...
+  const y: Y;
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-731b.dfy:12]:
```suggestion
  const y: Y
```

File: Test/git-issues/git-issue-731b.dfy [hunk 12]
```diff
@@ -0,0 +1,24 @@
...
+}
+
+class ClassA<Q> extends Tr2<Q,array<bv8>> {
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-731b.dfy:15]:
```suggestion
class ClassA<Q> extends Tr2<Q, array<bv8>> { 
```

File: Source/Dafny/Resolver.cs (hunk 1 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:12250]: Changed

File: Source/Dafny/Resolver.cs (hunk 2 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:12253]: Done

File: Source/Dafny/Resolver.cs (hunk 3 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:12254]: Done

File: Source/Dafny/Resolver.cs (hunk 4 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:12258]: Cleaned up

File: Test/git-issues/git-issue-731.dfy (hunk 8 above)
Comment (davidcok) [reply Test/git-issues/git-issue-731.dfy:21]: OK - it is the standard style - though not my preference

File: Test/git-issues/git-issue-731b.dfy (hunk 10 above)
Comment (davidcok) [reply Test/git-issues/git-issue-731b.dfy:11]: When I don't type semicolons reflexively (and don't put types before variables), I'll really be a Dafny programmer

File: Test/git-issues/git-issue-731b.dfy (hunk 11 above)
Comment (davidcok) [reply Test/git-issues/git-issue-731b.dfy:12]: Done

File: Test/git-issues/git-issue-731b.dfy (hunk 12 above)
Comment (davidcok) [reply Test/git-issues/git-issue-731b.dfy:15]: Done

File: Test/git-issues/git-issue-731b.dfy (hunk 9 above)
Comment (davidcok) [reply Test/git-issues/git-issue-731b.dfy:10]: Done

File: Source/Dafny/Resolver.cs (hunk 5 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs]: Already fixed
