### PR TITLE
fix: Account for the optional equality support of map/seq inside newtypes

### LINKED ISSUE #5978: General newtypes not supporting equality in a sound way
### Dafny version

latest-nightly

### Code to produce this issue

```dafny
// RUN: %exits-with 2 %baredafny verify --type-system-refresh --general-newtypes %args "%s" > "%t"
// RUN: %diff "%s.expect" "%t"

newtype M<U> = m: map<int, U> | true

method CompareAnything<A>(f: A, g: A) returns (b: bool) 
   ensures b <==> f == g
{
  var m1 := map[0 := f] as M<A>;
  var m2 := map[0 := g] as M<A>;
  assert m1 == m2 <==> f == g by {
    if f == g {
      assert m1 == m2;
    }
    if m1 == m2 {
      assert m1[0] == m2[0];
    }
  }
  return m1 == m2;
}

newtype S<T> = s: seq<T> | true

method CompareAnythingS<A>(f: A, g: A) returns (b: bool) 
   ensures b <==> f == g
{
  var m1 := [f] as S<A>;
  var m2 := [g] as S<A>;
  assert m1 == m2 <==> f == g by {
    if f == g {
      assert m1 == m2;
    }
    if m1 == m2 {
      assert m1[0] == m2[0];
    }
  }
  return m1 == m2;
}

codatatype Stream = Stream(head: int, tail: Stream)
{
  static function From(i: int): Stream {
    Stream(i, From(i + 1))
  }
}

method Main() {
  var s1 := Stream.From(0);
  var s2 := Stream.From(0);
  var b := CompareAnything(s1, s2);
  var b2 := CompareAnythingS(s1, s2);
  if !b || !b2 {
    assert false;
    print 1/0;
  }
}
```

### Command to run and resulting output

```code
dafny run --type-system-refresh --general-newtypes
```

### What happened?

It can run this incorrect program, which results in a crash.
Very similar to  #5972 

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by RustanLeino**
This PR extends fix #5973 of issue #5972 to also handle newtypes, subset types, and type synonyms wrapped around map and sequence types.

Fixes #5978 

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Resolver/ModuleResolver.cs [hunk 1]
```diff
@@ -2929,26 +2928,43 @@ private static void DetermineEqualitySupportType(Type type, ref bool thingsChang
...
-          var i = 0;
-          foreach (var otherTp in otherDt.TypeArgs) {
-            if (otherTp.NecessaryForEqualitySupportOfSurroundingInductiveDatatype) {
-              var tp = otherUdt.TypeArgs[i].AsTypeParameter;
-              if (tp != null) {
-                tp.NecessaryForEqualitySupportOfSurroundingInductiveDatatype = true;
-                thingsChanged = true;
+      } else if (type.SupportsEquality) {
+        // nothing to do
+      } else if (type.Normalize() is UserDefinedType userDefinedType) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Resolver/ModuleResolver.cs:2933]: Why do you need this normalization? I thought that AsMapType and AsSeqType would actually do that.

Comment (RustanLeino) [reply Source/DafnyCore/Resolver/ModuleResolver.cs:2933]: This `type.Normalize()` cuts through any type proxies that may be sitting around the `UserDefinedType`.

`AsMapType` and `AsSeqType` call `NormalizeExpand()`, which cuts through both proxies and type synonyms. But that's too much, because a type synonym can also have an explicit `(==)` declaration.

File: Source/DafnyCore/AST/TypeDeclarations/NewtypeDecl.cs [hunk 2]
```diff
@@ -96,13 +96,21 @@ public Type RhsWithArgument(List<Type> typeArgs) {
   public TopLevelDecl AsTopLevelDecl => this;
   public TypeDeclSynonymInfo SynonymInfo { get; set; }
 
-  public TypeParameter.EqualitySupportValue EqualitySupport {
+  private IndDatatypeDecl.ES equalitySupport = IndDatatypeDecl.ES.NotYetComputed;
```
Comment (MikaelMayer) [inline Source/DafnyCore/AST/TypeDeclarations/NewtypeDecl.cs:99]: The Rust compiler will also need to have precise equality support, as it's the only backend that needs to distinguish between type-parameter conditional equality and no equality possible.
Hence, it's not only solving a soundness issue, it's also making the compilation to Rust possible.

File: Makefile [hunk 3]
```diff
@@ -30,27 +30,16 @@ boogie: ${DIR}/boogie/Binaries/Boogie.exe
 tests:
 	(cd "${DIR}"; dotnet test Source/IntegrationTests)
 
-# make test name=<part of the path of an integration test>
+# make test name=<integration test filter>
```
Comment (MikaelMayer) [inline Makefile:33]: These changes to the makefile make it much much easier to test single files without having to rebuild, and also to update individual outputs without having to run the IDE or a complex command (or Lit, which we are not always supporting)

File: Source/DafnyCore/AST/TypeDeclarations/NewtypeDecl.cs [hunk 4]
```diff
@@ -96,13 +96,21 @@ public Type RhsWithArgument(List<Type> typeArgs) {
...
+
+  public IndDatatypeDecl.ES EqualitySupport {
     get {
-      if (this.BaseType.SupportsEquality) {
-        return TypeParameter.EqualitySupportValue.Required;
-      } else {
-        return TypeParameter.EqualitySupportValue.Unspecified;
+      if (equalitySupport == IndDatatypeDecl.ES.NotYetComputed) {
+        var thingsChanged = false;
+        if (ModuleResolver.SurelyNeverSupportEquality(BaseType)) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/AST/TypeDeclarations/NewtypeDecl.cs:105]: Because the types are topologically sorted, this will only be executed when the types this newtype depends on have been resolved.

File: Source/DafnyCore/AST/Types/UserDefinedType.cs [hunk 5]
```diff
@@ -400,6 +400,12 @@ public override bool SupportsEquality {
           i++;
         }
         return true;
+      } else if (ResolvedClass is NewtypeDecl newtypeDecl) {
+        if (newtypeDecl.IsRevealedInScope(Type.GetScope())) {
+          return newtypeDecl.RhsWithArgument(TypeArgs).SupportsEquality;
```
Comment (MikaelMayer) [inline Source/DafnyCore/AST/Types/UserDefinedType.cs:405]: Because of my change, we could also do the same treatment as for the datatypes, if you preferred. I'm fine with both approaches and to switch if you prefer.

File: Source/DafnyCore/Resolver/ModuleResolver.cs [hunk 6]
```diff
@@ -2861,11 +2861,7 @@ void MarkSCCAsNotSupportingEquality() {
             return;  // we are done
           }
           foreach (var arg in ctor.Formals) {
-            var anotherIndDt = arg.Type.AsIndDatatype;
-            if (arg.IsGhost ||
-                (anotherIndDt != null && anotherIndDt.EqualitySupport == IndDatatypeDecl.ES.Never) ||
-                arg.Type.IsCoDatatype ||
-                arg.Type.IsArrowType) {
+            if (arg.IsGhost || SurelyNeverSupportEquality(arg.Type)) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Resolver/ModuleResolver.cs:2864]: We need this type traversal to be recursive, otherwise soundness issue 5972c.dfy

File: Source/DafnyCore/Resolver/ModuleResolver.cs (hunk 1 above)
Comment (MikaelMayer) [reply Source/DafnyCore/Resolver/ModuleResolver.cs:2941]: If a type synonym does not have an explicit `(==)` annotation, it's still sound, right?
In general, I don't think you can conclude faster that a type synonym supports equality anyway. It seems that `(==)` is only a way to catch errors earlier.

**Review by MikaelMayer — DISMISSED** [review]
Approved when all tests pass

**Review by MikaelMayer — APPROVED** [review]

File: Source/DafnyCore/Resolver/ModuleResolver.cs (hunk 1 above)
Comment (RustanLeino) [reply Source/DafnyCore/Resolver/ModuleResolver.cs:2953]: An explicit `(==)` is also a way to advertise equality support to importers of the enclosing module. Without an explicit `(==)`, an `export provides` of the type would not let importers use the type as supporting equality.

**Review by MikaelMayer — APPROVED** [review]
We reviewed each other's changes and we agree with them.
