### PR TITLE
fix: Resolution of static functions-by-method

### LINKED ISSUE #2016: static function-by-method crashes Dafny
```
module M {
  datatype D = D() {
    static function f(): (res: int) {
      5
    } by method {
      return 5;
    }
  }
}
```

crashes Dafny.

```
$ dafny /compile:0 ~/tmp/bug.dfy
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
...
```

### PR DESCRIPTION
**Pull request by fabiomadge**
Fixes #2016.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -2317,10 +2317,9 @@ public class ModuleBindings {
       }
     }
 
-    void RegisterByMethod(Function f) {
+    void RegisterByMethod(Function f, TopLevelDeclWithMembers cl) {
       Contract.Requires(f != null && f.ByMethodBody != null);
 
-      var cl = (TopLevelDeclWithMembers)f.EnclosingClass;
```
Comment (cpitclaudel) [inline Source/Dafny/Resolver.cs:2323]: Is it a bug that the `enclosingclass` of `f` doesn't match cl?

Comment (fabiomadge) [reply Source/Dafny/Resolver.cs:2323]: I don't think so, as I believe that it gets filled in later. It's null at this point.

**Review by cpitclaudel — APPROVED** [review]
