### PR TITLE
Fix 5724 compile suffix main arguments

### LINKED ISSUE #5724: In Rust, Main fails to pass arguments
### Dafny version

4.7.0 -- feat-rust

### Code to produce this issue

```dafny
module foo {
  method Main(args: seq<string>) {
    print "Hello World!\n";
  }
}
```

### Command to run and resulting output

```code
dafny build -t rs foo.dfy
```

### What happened?

The code below was produced.
Not that `main` calls `foo::_default::Main();` but `foo::_default::Main();` has the signature 
`pub fn Main(args: &::dafny_runtime::Sequence<::dafny_runtime::Sequence<::dafny_runtime::DafnyChar>>) -> ()`
and so `dafny build` fails because `foo.rs` does not compile.

```
#![allow(warnings, unconditional_panic)]
#![allow(nonstandard_style)]

pub mod _module {
  
}
pub mod foo {
  pub struct _default {}

  impl _default {
    pub fn Main(args: &::dafny_runtime::Sequence<::dafny_runtime::Sequence<::dafny_runtime::DafnyChar>>) -> () {
      print!("{}", ::dafny_runtime::DafnyPrintWrapper(&::dafny_runtime::string_of("Hello World!\n")));
      return ();
    }
  }
}
fn main() {
foo::_default::Main();
}147dda119fc1:xxx ajewell$ cat foo-rust/src/foo.rs; echo
#![allow(warnings, unconditional_panic)]
#![allow(nonstandard_style)]

pub mod _module {
  
}
pub mod foo {
  pub struct _default {}

  impl _default {
    pub fn Main(args: &::dafny_runtime::Sequence<::dafny_runtime::Sequence<::dafny_runtime::DafnyChar>>) -> () {
      print!("{}", ::dafny_runtime::DafnyPrintWrapper(&::dafny_runtime::string_of("Hello World!\n")));
      return ();
    }
  }
}
fn main() {
foo::_default::Main();
}

```

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #5724 

### Description
- Support for `--compile-suffix` for emitting the main method name.
- Support for main methods with arguments.
- Support for test main methods with implicit formals

### How has this been tested?
- Modified the existing `comp/rust/tests.dfy` test in a way that was reproducing the two issues mentioned in #5724

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs [hunk 1]
```diff
@@ -216,7 +216,7 @@ pub mod dafny_runtime_conversions {
         }
     }
 
-    // --unicode-chars:false
+    // --unicode-char:false
     pub mod unicode_chars_false {
```
Comment (MikaelMayer) [inline Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs:220]: I wish I could change the module name here but it's a breaking change, so I'm not sure it's be a good idea at this point.

File: Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy [hunk 2]
```diff
@@ -3774,17 +3775,25 @@ module {:extern "DCOMP"} DafnyToRustCompiler {
...
-      var i := 0;
-      while i < |fullName| {
-        if i > 0 {
-          s := s + "::";
-        }
-        s := s + escapeName(fullName[i]);
-        i := i + 1;
+    method EmitCallToMain(companion: Expression, mainMethodName: string, hasArgs: bool) returns (s: string) {
+      s := "\nfn main() {";
+      if hasArgs {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy:3780]: Having test tree vs. formal tree: At this point, the emitted main method is emitted directly into the resulting text file, so any automated refactoring here is useless, as there is zero knowledge of everything that was imported before. We could change the entire architecture but that's too big of a change for this PR.

File: Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs [hunk 3]
```diff
@@ -1781,7 +1781,7 @@ protected override string TypeName_UDT(string fullCompileName, List<TypeParamete
       return s;
     }
 
-    protected override string TypeName_Companion(Type type, ConcreteSyntaxTree wr, IToken tok, MemberDecl/*?*/ member) {
+    internal override string TypeName_Companion(Type type, ConcreteSyntaxTree wr, IToken tok, MemberDecl/*?*/ member) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs:1784]: Changing the visibility here because I needed to access this method to emit the proper path here.
https://github.com/dafny-lang/dafny/pull/5910/files#diff-88e28efa63a86a01c970f8732d7414bb1f8c5bcb77cbba8e4ae7e7b7bad18711R69
It's very Dafny-compiler specific but I could not change the visibility to anything less than internal to make it work.
I could have created another method that calls the protected one, but at this point I think it would have created redundancy for nothing.

File: Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy [hunk 4]
```diff
@@ -3774,17 +3775,25 @@ module {:extern "DCOMP"} DafnyToRustCompiler {
...
-      s := "\nfn main() {\n";
-      var i := 0;
-      while i < |fullName| {
-        if i > 0 {
-          s := s + "::";
-        }
-        s := s + escapeName(fullName[i]);
-        i := i + 1;
+    method EmitCallToMain(companion: Expression, mainMethodName: string, hasArgs: bool) returns (s: string) {
+      s := "\nfn main() {";
```
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy:3779]: Having test tree vs. formal tree: At this point, the emitted main method is emitted directly into the resulting text file, so any automated refactoring here is useless, as there is zero knowledge of everything that was imported before. We could change the entire architecture but that's too big of a change for this PR.

File: Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy (hunk 2 above)
Comment (MikaelMayer) [inline Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy:3780]: This test of whether the method has arguments is there for historical reasons, but it seems that SinglePassCodeGenerator always add an implicit formal for arguments on main methods even if it's not declared, so I'm not sure the case `!hasArgs` is tested.

**Review by ssomayyajula — APPROVED** [review]
