### PR TITLE
#750: Fixing non-variance of array assignments

### LINKED ISSUE #321: Typ inference seems to infer array as nullable
```
method h(n: nat)
{
  var a: array<nat> := new [n](i => i);
}
```
results in

```
> $ Dafny.exe lang-test51.dfy
Dafny 2.3.0.10506
lang-test51.dfy(3,23): Error: value does not satisfy the subset constraints of 'array<nat>' (possible cause: it may be null)
Execution trace:
    (0,0): anon0
    lang-test51.dfy(3,32): anon3_Else
```

when adding the type explicitly on the RHS as in

```
method h(n: nat)
{
  var a: array<nat> := new nat[n](i => i);
}
```

it works

### LINKED ISSUE #750: User defined type parameters should be non-variant
There should be type errors (not just verification errors) from these:
```
  var a: C<nat>;
  var b: C<int>;
  a := new C<nat>;
  b := new C<int>;
  if * {
    a := b;
  } else {
    b := a;
  }

```
and 
```
  var a: array<nat>;
  var b: array<int>;
  a := b;
  b := a;
```

### PR DESCRIPTION
**Pull request by davidcok**
Fixes #750.
Fixes #321.

### CODE REVIEW

File: Source/Dafny/Resolver.cs [hunk 1]
```diff
@@ -3768,6 +3768,9 @@ public class ModuleBindings
         var lhsWithProxyArgs = Type.HeadWithProxyArgs(lhs);
         ConstrainSubtypeRelation(lhsWithProxyArgs, rhs, errMsg, false, allowDecisions);
         ConstrainAssignableTypeArgs(lhs, lhsWithProxyArgs.TypeArgs, lhs.TypeArgs, errMsg, out moreXConstraints);
+        if (Type.SameHead(lhs, rhs, true) && lhs.AsCollectionType == null) {
+          ConstrainAssignableTypeArgs(lhs, lhs.TypeArgs, rhs.TypeArgs, errMsg, out moreXConstraints);
```
Comment (RustanLeino) [inline Source/Dafny/Resolver.cs:3772]: This will overwrite the `moreXConstraints` that was set in L3770. I think L3772 should probably pass a new local boolean variable and then update `moreXConstraint` to be the disjunction of `moreXConstraints` from L3700 and the new local variable.

File: Test/dafny0/ArrayElementInit.dfy [hunk 2]
```diff
@@ -73,8 +73,8 @@ method Q0(s: Six, y: int) returns (a: array<Six>)
 {
   if
   case true =>  a := new Six[10](_ => s);
-  case true =>  a := new Six[10](x => 6+x);
-  case true =>  a := new Six[10](_ => y);
+  case true =>  // a := new Six[10](x => 6+x); // type error
+  case true =>  // a := new Six[10](_ => y);   // type error
```
Comment (RustanLeino) [inline Test/dafny0/ArrayElementInit.dfy:77]: I don't expect these to be (type or verification) errors.

File: Test/dafny0/SubsetTypes.dfy [hunk 3]
```diff
@@ -176,9 +176,9 @@ module SoftCasts {
   {
     if
     case true =>
-      g := z => if z < 0 then -z else z;
+      // g := z => if z < 0 then -z else z; // type error
```
Comment (RustanLeino) [inline Test/dafny0/SubsetTypes.dfy:179]: So then, what would be the correct way to write such an `int -> nat` absolute-value function?

File: Test/dafny0/SubsetTypes.dfy [hunk 4]
```diff
@@ -228,21 +228,21 @@ module AssignmentsFromNewAllocation {
...
     }
   }
-
+*/
   method M(N: nat, p: Person) {
     var a: array<Person?>;
     var b: array<Person>;
     if * {
-      a := b;  // error
+      // a := b;  // error
```
Comment (RustanLeino) [inline Test/dafny0/SubsetTypes.dfy:236]: Yes, good! The commented-out tests in this method should indeed be caught as type errors. Since they are (and are tested as such in `SubsetTypesERR.dfy`), I think the tests are better just deleted here (rather than being commented out--although being commented out helped do this review).

**Review by RustanLeino — CHANGES_REQUESTED** [review]

File: Test/dafny0/ArrayElementInit.dfy (hunk 2 above)
Comment (davidcok) [reply Test/dafny0/ArrayElementInit.dfy:77]: OK - but will need checking in the verifier

File: Test/dafny0/SubsetTypes.dfy (hunk 3 above)
Comment (davidcok) [reply Test/dafny0/SubsetTypes.dfy:179]: Could always put an `as nat` on the expression (after the =>). But we'll see if the verifier can be encouraged to check this.

File: Source/Dafny/Resolver.cs (hunk 1 above)
Comment (davidcok) [reply Source/Dafny/Resolver.cs:4106]: Done

Comment (davidcok) [reply Source/Dafny/Resolver.cs]: Fixed this

File: Test/dafny0/SubsetTypes.dfy (hunk 4 above)
Comment (davidcok) [reply Test/dafny0/SubsetTypes.dfy]: Sorted out the two test files

Comment (davidcok) [reply Test/dafny0/SubsetTypes.dfy]: revised these tests

File: Test/dafny0/TypeConstraints.dfy [hunk 5]
```diff
@@ -415,20 +415,46 @@ module LetPatterns {
...
+    } else if * {
+      a := b;  // ERROR
+    } else if * {
+      b := a;  // ERROR
+    } else if * {
+      var n := new nat[100];  // array<nat>
+      if * {
+        a := n;
+      } else {
+        b := n;
```
Comment (RustanLeino) [inline Test/dafny0/TypeConstraints.dfy:437]: This should also be an error

File: Test/git-issues/git-issue-321.dfy [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+}
+
+method p(n: nat) {
+  var init: nat -> nat := i => i;
+  var a: array := new [n](init); // OK
+}
+
+method q(n: nat) {
+  var init: int -> int := i => i;
+  var a: array<nat> := new [n](init); // ERROR
```
Comment (RustanLeino) [inline Test/git-issues/git-issue-321.dfy:19]: If `new [n]` is changed to `new nat[n]`, then this method would verify, right?

File: Test/dafny0/TypeConstraints.dfy [hunk 7]
```diff
@@ -415,20 +415,46 @@ module LetPatterns {
...
+
+module Arrays_and_SubsetTypesOK {
   method M()
   { // Type-wise, all of the following are allowed (but the verifier will complain):
     var a: array<nat>;
     var b: array<int>;
     if * {
       a := new nat[100];
-      b := new nat[100];
+      //b := new nat[100];
```
Comment (RustanLeino) [inline Test/dafny0/TypeConstraints.dfy:450]: Do these no longer work? If there're no longer needed, delete them.

**Review by RustanLeino — CHANGES_REQUESTED** [review]

File: Test/dafny0/TypeConstraints.dfy (hunk 5 above)
Comment (davidcok) [reply Test/dafny0/TypeConstraints.dfy:437]: It is a verification error. Moved it to a different file to check it.

File: Test/dafny0/TypeConstraints.dfy (hunk 7 above)
Comment (davidcok) [reply Test/dafny0/TypeConstraints.dfy:450]: Fixed up the tests

File: Test/git-issues/git-issue-321.dfy (hunk 6 above)
Comment (davidcok) [reply Test/git-issues/git-issue-321.dfy:19]: Correct -- and a test added to confirm
