### PR TITLE
fix: Don't use CompileName outside of the compilers

### LINKED ISSUE #1984: Dafny's verifier incorrectly uses :extern names
For example, this is rejected:

```dafny
method {:extern "test"} testInt(i: int)
method {:extern "test"} testBool(b: bool)
```

```console
$ Dafny "git-issue-1984.dfy"
git-issue-1984.dfy(5,24): Error: more than one declaration of procedure name: CheckWellformed$$_module.__default.test
git-issue-1984.dfy(5,24): Error: more than one declaration of procedure name: Call$$_module.__default.test
```

### PR DESCRIPTION
**Pull request by cpitclaudel**
* Source/Dafny/AST/DafnyAst.cs:

  (Declaration.SanitizedName, TypeParameter.SanitizedName,
   TupleTypeDecl.SanitizedName, NonglobalVariable.SanitizedName,
   LocalVariable.SanitizedName, Formal.SanitizedName):
  New property

  (ModuleDefinition.SanitizedName):
  New property (created by splitting off the non-extern parts of CompileName)

  (Declaration.CompileName, ModuleDefinition.CompileName):
  Use SanitizedName

  (TypeParameter.CompileName, TupleTypeDecl.CompileName,
   NonglobalVariable.CompileName, LocalVariable.CompileName):
  Alias to SanitizedName

  (ModuleExportDecl, ModuleDefinition.VisibilityScope):
  Use SanitizedName when creating the VisibilityScope

  (ModuleDefinition.FullSanitizedName, DataTypeDecl.FullSanitizedName):
  Use SanitizedName, not CompileName

  (NonglobalVariable.CompilerizeName):
  Rename to SanitizeName

  (NonglobalVariable.AssignUniqueName, LocalVariable.AssignUniqueName):
  Only assign uniqueName (compileName initialization was duplicated with the
  CompileName getter)

  (FunctionCallFinder.PrintFunctionCallGraph):
  Use SanitizedName, not CompileName

  (ModuleDefinition.RefinementCompileName,
   ModuleDefinition.FullSanitizedRefinementName, MemberDecl.FullNameInContext,
   MemberDecl.FullSanitizedRefinementName, SpecialField.FullCompileName,
   SpecialField.FullNameInContext, SpecialField.FullSanitizedRefinementName):
  Remove unused properties

* Source/Dafny/Verifier/Translator.cs (Translator.Translate):
* Source/DafnyServer/SymbolTable.cs (*):

  Use SanitizedName, not CompileName

* Source/Dafny/Resolver.cs (ResolveProgram):
  Use FullSanitizedName instead of FullCompileName when creating a signature for
  an abstract module (originally changed from .Name to .FullCompileName in
  66b9c19c9692ccece00fb6202bb0d2440999d93b)

Fixes #1984.

### CODE REVIEW

File: Source/Dafny/AST/DafnyAst.cs [hunk 1]
```diff
@@ -4000,52 +3996,53 @@ public class ModuleDefinition : INamedRegion, IAttributeBearingDeclaration {
     }
 
     VisibilityScope visibilityScope;
+    public VisibilityScope VisibilityScope =>
```
Comment (keyboardDrummer) [inline Source/Dafny/AST/DafnyAst.cs:3999]: With .NET source generators we should be able to write this as just 
```csharp
[Memoize] 
public VisibilityScope VisibilityScope => new VisibilityScope(this.SanitizedName)
```

But strangely it doesn't seem like there are NuGet packages with attributes like Memoize.

File: Source/Dafny/AST/DafnyAst.cs [hunk 2]
```diff
@@ -5953,29 +5899,17 @@ public abstract class NonglobalVariable : IVariable {
...
-      if (uniqueName == null) {
-        uniqueName = generator.FreshId(Name + "#");
-        compileName = string.Format("_{0}_{1}", IVariable.CompileNameIdGenerator.FreshNumericId(), CompilerizeName(name));
-      }
-      return UniqueName;
+      return uniqueName ??= generator.FreshId(Name + "#");
     }
     static char[] specialChars = new char[] { '\'', '_', '?', '\\', '#' };
-    public static string CompilerizeName(string nm) {
+    public static string SanitizeName(string nm) {
```
Comment (keyboardDrummer) [inline Source/Dafny/AST/DafnyAst.cs:5912]: Could you add a comment to this method? What does it mean to sanitize a name? Why do we need to sanitize? Apparently the verifier also needs sanitized names. Does SanitizeName remove any characters which are likely to cause issues in verification or compilation back-ends ?

File: Source/Dafny/AST/DafnyAst.cs [hunk 3]
```diff
@@ -4000,52 +3996,53 @@ public class ModuleDefinition : INamedRegion, IAttributeBearingDeclaration {
...
+
     string compileName;
     public string CompileName {
       get {
         if (compileName == null) {
           var externArgs = DafnyOptions.O.DisallowExterns ? null : Attributes.FindExpressions(this.Attributes, "extern");
           if (externArgs != null && 1 <= externArgs.Count && externArgs[0] is StringLiteralExpr) {
             compileName = (string)((StringLiteralExpr)externArgs[0]).Value;
-          } else if (IsBuiltinName || externArgs != null) {
+          } else if (externArgs != null) {
```
Comment (keyboardDrummer) [inline Source/Dafny/AST/DafnyAst.cs:4036]: This case should only happen when `externArgs.Count == 0` right? Maybe be nice to make that explicit.

**Review by keyboardDrummer — DISMISSED** [review]

File: Source/Dafny/AST/DafnyAst.cs (hunk 3 above)
Comment (cpitclaudel) [reply Source/Dafny/AST/DafnyAst.cs:4036]: Also when externArgs[1] is something else than a string, I think?  Though that should probably not be accepted.

File: Source/Dafny/AST/DafnyAst.cs (hunk 2 above)
Comment (cpitclaudel) [reply Source/Dafny/AST/DafnyAst.cs:5912]: IIUC what this does is indeed escape some special chars that shouldn't be emitted into Boogie. (The notion of "sanitized" names already existed, so I just renamed the function for consistency.)

As for compilation versus verification, I'm less clear on that.  We already have idProtect on the compiler side, so I'm guessing SanitizeName isn't strictly needed there.

File: Source/Dafny/AST/DafnyAst.cs (hunk 1 above)
Comment (cpitclaudel) [reply Source/Dafny/AST/DafnyAst.cs:3999]: Agreed, and I was disappointed to not find one :'(

File: Source/Dafny/AST/DafnyAst.cs (hunk 2 above)
Comment (cpitclaudel) [reply Source/Dafny/AST/DafnyAst.cs:5912]: 6e69a31ea0703e3dc35b103a9f85cf0286f4d49b was where it was originally introduced, and that was specifically for C#.  Then the translator was changed to use "SanitizedName" (an alias of CompileName, more or less) in a8b18b984b289be43c112ca6f0fb2283a8ddc13a. IdProtect was introduced in a939eff5 to sanitize language-specific keywords.

Comment (cpitclaudel) [reply Source/Dafny/AST/DafnyAst.cs:5919]: I added a docstring.

**Review by keyboardDrummer — APPROVED** [review]

File: Source/Dafny/AST/DafnyAst.cs (hunk 3 above)
Comment (keyboardDrummer) [reply Source/Dafny/AST/DafnyAst.cs:4036]: > Also when externArgs[1] is something else than a string, I think? Though that should probably not be accepted.

I'll leave it up to you to decide whether to make that more strict :-) From the documentation it doesn't look like a non-string argument is accepted.

Comment (cpitclaudel) [reply Source/Dafny/AST/DafnyAst.cs:4036]: We can fix this separately, I think; I prefer for this PR to not change existing behaviors.

Comment (keyboardDrummer) [reply Source/Dafny/AST/DafnyAst.cs:4036]: > We can fix this separately, I think; I prefer for this PR to not change existing behaviors.

That's fair

**Comment by hirataqdees** [comment]
Hi, 
Does this merged issue solve the error: `modules 'X' and 'X' both have CompileName 'X_Compile'` for
`module {:extern} New.X {},  module {:extern} Old.X {}`

**Comment by keyboardDrummer** [comment]
> Hi, Does this merged fix solve the error: `modules 'X' and 'X' both have CompileName 'X_Compile'` for `module {:extern} New.X {}, module {:extern} Old.X {}` ?

I don't think so, but this fix is available in the latest Dafny so please see if your issue is resolved there.

**Comment by hirataqdees** [comment]
Hi Remy, thanks for letting me know.

**Comment by cpitclaudel** [comment]
That issue was fixed in a different PR: https://github.com/dafny-lang/dafny/pull/1998
