### PR TITLE
Fix: Bitvector shift in `--type-system-refresh`

### LINKED ISSUE #6196: Bitvector issue with `--type-system-refresh`
### Dafny version

Latest nightly

### Code to produce this issue

```dafny
newtype Uint8 = x: int | 0 <= x < 256

type CustomBv16 = bv16

method Main() {
  var x: Uint8 := 2;
  // Correct rendering of expressions that can interpret the first '<' as a generic argument
  var y: bv16 := (x as CustomBv16) << 2;
}
```

### Command to run and resulting output

```code
> dafny run --target=rs --enforce-determinism --type-system-refresh 

...
error[E0277]: no implementation for `u16 << DafnyInt`
  --> src\conversions.rs:57:41
   |
57 |             let mut y: u16 = (x as u16) << int!(2);
   |                                         ^^ no implementation for `u16 << DafnyInt`
   |
   = help: the trait `Shl<DafnyInt>` is not implemented for `u16`
   = help: the following other types implement trait `Shl<Rhs>`:
             `&u16` implements `Shl<&i128>`
             `&u16` implements `Shl<&i16>`
             `&u16` implements `Shl<&i32>`
             `&u16` implements `Shl<&i64>`
             `&u16` implements `Shl<&i8>`
             `&u16` implements `Shl<&isize>`
             `&u16` implements `Shl<&u128>`
             `&u16` implements `Shl<&u32>`
```

### What happened?

This bug appeared since #5653 
I nailed it down to a single line that needs to be updated. Fix will be provided soon.

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by MikaelMayer**
Fixes #6196 

I updated the test to ensure it was breaking and that this PR fixes the test.
Basically, a test was testing if the type was a bitvector type, but this type was a synonym type with the new resolver so that needed to be updated.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/DafnyCore/Rewriters/BitvectorOptimization.cs [hunk 1]
```diff
@@ -44,7 +44,7 @@ private Expression ShrinkBitVectorShiftAmount(Expression expr, BitvectorType ori
   }
 
   protected override void VisitOneExpr(Expression expr) {
-    if (expr.Type is BitvectorType bvType) {
+    if (expr.Type.AsBitVectorType is { } bvType) {
```
Comment (MikaelMayer) [inline Source/DafnyCore/Rewriters/BitvectorOptimization.cs:47]:
```suggestion
    if (expr is { Type.AsBitVectorType: { } bvType }) {
```

File: Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/conversions.dfy [hunk 2]
```diff
@@ -27,10 +29,12 @@ method TestCompile(input: Option<Uint8>) returns (output: Option<Uint8>) {
   return None;
 }
 
+type CustomBv16 = bv16
+
 method Main() {
   var x: Uint8 := 2;
   // Correct rendering of expressions that can interpret the first '<' as a generic argument
-  var y: bv16 := (x as bv16) << 2;
+  var y: bv16 := (x as CustomBv16) << 2;
```
Comment (fabiomadge) [inline Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/conversions.dfy:37]: Is this working around another bug?

Comment (MikaelMayer) [reply Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/conversions.dfy:37]: Excellent question. Thanks for asking.
Looking at the generated code, CustomBv16 is actually rendered as a name as well, and the Dafny-to-Rust correctly generates parentheses around the as expression because otherwise the "<" would be interpreted as the start of a generic argument.
To sum up, I'm still checking the other (already fixed) bug, just adding another kind of type to verify types, which reproduces the same issue I had originally found when compiling this line to Rust:

https://github.com/dafny-lang/dafny/blob/ad994713edde359976bd1e813718fc5292a60e3b/Source/DafnyStandardLibraries/src/Std/Unicode/Utf8EncodingForm.dfy#L180

**Review by fabiomadge — APPROVED** [review]
