### PR TITLE
Fix #2574

### LINKED ISSUE #2574: Crash in `LocalVariable.get_Type` with `/showSnippet` dues to bad token (silent error in vscode)
Input:

```dafny
module Spec {
  type input
  method ReadInput() returns (i: input)
}

module Impl refines Spec {
  class input {}
  method ReadInput() returns (i: input) {
  }
}
```

Output:

```
Dafny /compile:0 /useBaseNameForFileName /timeLimit:30 /showSnippets:1 bug.dfy
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'key'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Dafny.DafnyConsolePrinter.GetFileLine(String filename, Int32 lineIndex) in /dafny/Source/Dafny/DafnyConsolePrinter.cs:line 15
   at Microsoft.Dafny.DafnyConsolePrinter.WriteSourceCodeSnippet(IToken tok, TextWriter tw) in /dafny/Source/Dafny/DafnyConsolePrinter.cs:line 32
   at Microsoft.Dafny.DafnyConsolePrinter.ReportBplError(IToken tok, String message, Boolean error, TextWriter tw, String category) in /dafny/Source/Dafny/DafnyConsolePrinter.cs:line 56
   at Microsoft.Boogie.ConsolePrinter.WriteErrorInformation(ErrorInformation errorInfo, TextWriter tw, Boolean skipExecutionTrace)
   at Microsoft.Boogie.ExecutionEngine.ProcessErrors(OutputPrinter printer, List`1 errors, Outcome outcome, TextWriter tw, ErrorReporterDelegate er, Implementation impl)
   at Microsoft.Boogie.VerificationResult.GetOutput(OutputPrinter printer, ExecutionEngine engine, PipelineStatistics stats, ErrorReporterDelegate er)
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass38_0.<<VerifyEachImplementation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass38_0.<<VerifyEachImplementation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.VerifyEachImplementation(TextWriter output, ProcessedProgram processedProgram, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId, Implementation[] stablePrioritizedImpls)
   at Microsoft.Boogie.ExecutionEngine.InferAndVerify(TextWriter output, Program program, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId)
   at Microsoft.Dafny.Main.BoogiePipelineWithRerun(TextWriter output, ExecutionEngine engine, Program program, String bplFileName, String programId) in /dafny/Source/Dafny/DafnyMain.cs:line 341
   at Microsoft.Dafny.Main.BoogieOnce(TextWriter output, ExecutionEngine engine, String baseFile, String moduleName, Program boogieProgram, String programId) in /dafny/Source/Dafny/DafnyMain.cs:line 279
   at Microsoft.Dafny.DafnyDriver.BoogieOnceWithTimer(TextWriter output, String baseName, String programId, String moduleName, Program program) in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 419
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass17_0.<<Boogie>b__0>d.MoveNext() in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 392
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass17_0.<<Boogie>b__0>d.MoveNext() in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 395
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyDriver.Boogie(String baseName, IEnumerable`1 boogiePrograms, String programId) in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 398
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 311
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 116
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass9_0.<Main>b__0() in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 92
   at System.Threading.Thread.StartCallback()
```

Without `/showSnippets:1`, I get this output instead:

```
(0,-1): Error: out-parameter 'i', which is subject to definite-assignment rules, might be uninitialized at this return point
```

### PR DESCRIPTION
**Pull request by atomb**
One-character fix FTW!

Fixes #2574

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

File: Source/Dafny/Verifier/Translator.ClassMembers.cs [hunk 1]
```diff
@@ -645,7 +645,7 @@ public partial class Translator {
         m.Outs.Iter(p => AddExistingDefiniteAssignmentTracker(p, m.IsGhost));
         // translate the body
         TrStmt(m.Body, builder, localVariables, etran);
-        m.Outs.Iter(p => CheckDefiniteAssignmentReturn(m.BodyEndTok, p, builder));
+        m.Outs.Iter(p => CheckDefiniteAssignmentReturn(m.Body.EndTok, p, builder));
```
Comment (MikaelMayer) [inline Source/Dafny/Verifier/Translator.ClassMembers.cs:648]: Wow... but why is this solving the problem? Won't you have a problem if body is null?

Comment (atomb) [reply Source/Dafny/Verifier/Translator.ClassMembers.cs:648]: The previous call (and some of the following code) would also crash if the body was null, so I believe it's not possible at this point in the code path. If it is, that's a separate thing to fix. :)
